### ISSUE TITLE
Plan AGM

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#112]
- Initial Proposed date is Wednesday August 10.
- Plan the agenda and tasks that lead up to the event
- Relevant documents can found in the folder [AGM](https://drive.google.com/drive/folders/1xC8_hsLHZy5_qQlKaNaeoJgJengtsCdP?usp=sharing)
- Should be done and ready to send out invitations by Friday July 30th.

**Comment by StephMcNeely** [comment]
@smlambert this was discussed on Monday and going with August 10th as Wednesdays generally work ;)
Need to invite the board, Andy, core and other volunteers and other invitees (I asked Marie-France Lalonde's office, Elyse and Sharon from Enviro Centre, CAFES Tree Caucus, etc.)
Thoughts on speakers = 
- Bruno or Cedric from NCC on their Forestry Strategy
- Project plan for the Healing Forest by Alexis at Root in Nature

Thoughts on hands on activiites:
- seed foray or nut tree seed planting (like last year)
- mulching or pruning in Miyawaki area :)

**Comment by natashafcf** [comment]
@StephMcNeely @smlambert I've created a draft document of invitation e-mails for all of the above, please review:

https://docs.google.com/document/d/1n1SI44tc1UYvYcoAdAfvUKXCSFbZ0qXtwUVyIE6-QS4/edit#

**Comment by natashafcf** [comment]
Here is the list of the schedule for review:

https://docs.google.com/document/d/1GP2Kv3DsZb6QE0kRIH78IgZm8H7_H8OeFiOxtzXZJ1k/edit#

**Comment by MartinNesbitt** [comment]
Do we want to send out a call for volunteers to help set up the AGM? if so, I would send it out in the newsletter? The work back plan form last year's AGM mentions a call for volunteers.

**Comment by smlambert** [comment]
I think we should include additional note in the invitation for people who plan to walk the work-in-progress trail to dress appropriately (wear appropriate clothing/footwear for the rugged nature of the site).  Also bug spray isn't a bad idea either.

**Comment by smlambert** [comment]
Field work in prep for AGM

- [ ] Tidy up the site, remove any visible garbage, and move empty pots from tiny forest site to the area near greenhouse (not touching or leaning against greenhouse)
- [ ] Move picnic table from greenhouse area to grass circle (by tree guilds in Field 2) - can try and do this on Friday with trailer
- [ ] Organize and tidy inside and around the greenhouse
- [ ] Whipper-snip around trees in Field 1
- [ ] Whipper-snip 4 demonstration 'front yards' tree guilds
- [ ] Do a finer mowing of the main artery of the walking path (if we get access to the ride-on mower)
- [ ] Print and laminate temporary signage for walking tour
- [ ] Post laminated signs on stakes and install along walking path 
- [ ] Remove dead trees that are visible from walking path (some bur oaks in field 2, 2 apples in field 3)

On Day of AGM:
- [ ] Setup Shelley's bug tent with table and chairs inside for use during official AGM time (by that point bugs will be brutal)
- [ ] Setup snack table (using picnic table?) in grass circle in Field 2 with water container & pump
- [ ] Setup activity table (either in grass circle in Field 2 or by the greenhouse) - activities to include potting up trees

**Comment by smlambert** [comment]
Snack ideas/concepts (should @smlambert have time to achieve):
- simple pizza (pesto base or tomato base with vegetables from food forests & simple cheese)
- fruit muffins (fruit fillings from food forests)
- nuts in shell (activity of cracking and picking them)
- cucumbers (from farm partners) with hummus or eggplant dip
- lemon or cucumber water
- bubly canned water

**Comment by smlambert** [comment]
Temporary signage for AGM tours (and other tours planned in August) is being worked on in this [shared drive](https://drive.google.com/drive/folders/1RjSmofjSyviam39RDp_3s8GQ8TkrZmEw?usp=sharing)

Google map with proposed location of temp signage is [here](https://www.google.com/maps/d/u/0/edit?mid=1NgheyNipqBFj0i9g5d_4BTARN4ZYADII&usp=sharing)

**Comment by MartinNesbitt** [comment]
The AGM invitations have been sent out to all the contacts in the email blast tab of the AGM spreadsheet.
