### ISSUE TITLE
Project Reporting NCC

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#113]

**Comment by smlambert** [comment]
Is this the same as the 365 report tracked by this issue? https://github.com/ForetCapitaleForest/actions/issues/29
If so, we can likely close this one as duplicate.  If not, we should put some description in place to know what it is referring to

**Comment by smlambert** [comment]
Temporarily assigning to @StephMcNeely to determine if its a duplicate of https://github.com/ForetCapitaleForest/actions/issues/29 and if it can be closed.

**Comment by smlambert** [comment]
Will close this issue as a dup of other issue.
