### ISSUE TITLE
Updates to team page on website

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#117]
There are some team members missing from the website https://foretcapitaleforest.ca/about/our-team/

@MartinNesbitt @InnesBuck @Pepe-Fifi - each of you, let's pull together a short bio and photo in preparation to update this page

**Comment by MartinNesbitt** [comment]
Hi everyone, Just updated the "Our Team" page on the website with my information. I used the same information from the social media post a couple weeks back.

**Comment by InnesBuck** [comment]
I have done the same as Marty, using the information that I posted in my social media post.

**Comment by natashafcf** [comment]
@smlambert I'm having difficulties logging into the website builder, I'm using the same password as my Gmail Account and it isn't working. Let me know what I should do :)

**Comment by smlambert** [comment]
@natashafcf - You've been sent a password reset link, the Wordpress password is separate from your gmail account

**Comment by natashafcf** [comment]
@smlambert Thanks! I'm in now :)

**Comment by natashafcf** [comment]
Colin's bio is updated!

**Comment by natashafcf** [comment]
Simona's bio is updated!
