### ISSUE TITLE
Prototype a story map of the farm

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#119]
While this work is likely pending the TD FEF grant, putting it here so we do not lose track of it:

From @MartinNesbitt:

> I was just pondering about the virtual aspect of the Just Food pathway. I know we wanted to include a Q/R code on the physical signage that links to a self-guided and interactive tour of the farm. I was wondering if we already had ideas on how we wanted to do this? 
> 
> If not, I thought maybe we could create a Story Map of the farm. This would be an interactive map where you can go through all the elements at the farm. Here is an example done by Ottawa Biosphere Eco-City https://storymaps.arcgis.com/stories/3bd39ef551fe4b2bb924e75c7dcec0c5. 
> Other examples:
> https://northcentral.maps.arcgis.com/apps/MapTour/index.html?appid=874758bf538444d29b6e080d88736295&webmap=4ec6c9d3942545c486a276d028ab6c88
> https://tnc.maps.arcgis.com/apps/MapTour/index.html?appid=d3fd1deb014f4d9f99b58221463abbf0
> https://esri-ea.maps.arcgis.com/apps/Shortlist/index.html?appid=194277f97cf5436592654b41ae36397
> 

Also see https://github.com/ForetCapitaleForest/actions/issues/81#issuecomment-1189065427 for some cool interactive maps/tools for inspiration.

**Comment by MartinNesbitt** [comment]
In addition to the story map of the Just Food farm, we should have an interactive map of all of our planting locations (Hogs back, aviation parkway, Chelsea, etc.). 

Inspired by [the map from Water Rangers](https://waterrangers.ca/) 

- you would be able to click on each location and learn some insight about each (# of trees, diversity, year planted)
- interesting opportunity for citizen science. (could get people to comment on the condition of the trees, in addition to a paper checklist on-site)

**Comment by MartinNesbitt** [comment]
Link to the story map brainstorm/draft [here](https://docs.google.com/document/d/1XNi9qMmfi_fCbCqpYS48gma_yWAGnDvfprK6bFz0Bog/edit?usp=sharing)

Preview of a draft story map on ArcGIS [here](https://arcg.is/eizfT)

**Comment by smlambert** [comment]
FYI @jduimovich

**Comment by smlambert** [comment]
@MartinNesbitt - while I have not given it a 'thorough' review, on a quick look, the draft story map looks phenomenal!  

I have tagged John also, as we will discuss the mobile experience of a tour plus options on how to best incorporate this and the greater community farm map into 'a centralized website' (I may plan to create a new domain for that, after a discussion with and agreement of Moe).

**Comment by MartinNesbitt** [comment]
@smlambert - Wondering about creating an FCF account for ArcGIS Online. This would allow for anyone to edit the story map and any other online maps for FCF.

**Comment by smlambert** [comment]
I had already created an account and will send details to the comms email.

**Comment by MartinNesbitt** [comment]
Thank you Shelley!
