### ISSUE TITLE
Find contractor/landscaper to do soil prep for BP4SF

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#12]
Ideally find someone who can: 

- assess the soil and determine how early we can get started on site prep
- move leaf mulch from road to plot
- dig in mulch along with several other amendments 
- dig catch ponds at 2 locations 

We would like this work to occur in May timeframe if possible

**Comment by smlambert** [comment]
Connect with landscaper contact provided by Dave.

**Comment by StephMcNeely** [comment]
- [ ] @smlambert to order a chip drop between FCF and Community Food Forest
- [ ] @StephMcNeely to get approval from Just Food for installation of PVC pipe across from Shelley's greenhouse
- [ ] @StephMcNeely to coordinate excavator rental with brother between May 10 and May 22.
