### ISSUE TITLE
Signage Template for Just Food Walking Path

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#120]
This work is already underway, but creating a separate issue for it, so it is easy to track progress.

See work inside of shared folder [WalkingPath/Signage](https://docs.google.com/document/d/1gmE5rUvE2mAN6NQ-q2XPNJaVvBzeEeRVWleYIU26u_8/edit?usp=sharing)

Also refer to Sign and Path Design Requirements [Shared Document](https://docs.google.com/document/d/1gmE5rUvE2mAN6NQ-q2XPNJaVvBzeEeRVWleYIU26u_8/edit?usp=sharing)

**Comment by natashafcf** [comment]
Connected to this issue
https://github.com/ForetCapitaleForest/actions/issues/35

**Comment by MartinNesbitt** [comment]
Note on highlighting the use of Indigenous language in the signage template as mentioned by the project funders (TD FEF) "Upon reviewing the application, the Advisory Board noted that there was a brief mention at the end of the application of incorporating Indigenous language on the signage. The Board wanted to follow up to highlight the importance of this piece and encourages that your group ensure it is not forgotten. The Board would also ask that you consider placing the Indigenous language at the top of the signage." 

We have not engaged with any Anishinabe community members on how to incorporate traditional language into our signs but we need to keep placement in mind as per TD’s suggestion. 

@natashafcf @smlambert

**Comment by smlambert** [comment]
I thought that was part of the Earth Path response from TD, but yes, as we mentioned interest in incorporating this into our signage also, we need to explore the ways we can (and what can be afforded).

The Birch Path Healing Forest engaged with a person that has translated their signage.  

We could see if they would be willing to also help with our translations.  I do not think we can afford to translate all signage, but I think the welcome sign and one or two other signs should feature Anishinaabemowin language, culture, stories.  I was thinking the Welcome sign, the Great Oak Circle sign and perhaps the Foraging Guidelines and/or Keeping it Wild sign. 

> In Anishinaabe traditional belief, everything in the environment is interconnected and has important relationships with the things around it. [[6]](https://en.wikipedia.org/wiki/Anishinaabe_traditional_beliefs#cite_note-:2-6) Non-humans, and ecosystems are viewed as having great worth and importance, in addition to humans.

**Comment by smlambert** [comment]
@KaviGK connecting with Jim W. on what next steps for the broader farm signage.

**Comment by smlambert** [comment]
Marking as closed.
