### ISSUE TITLE
August 2022 Newsletter

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#124]
Potential contents
- Canada Helps Tiny Forests fundraiser
- Thank You posts for the AGM
- Dashboard (continuously evolving)

**Comment by MartinNesbitt** [comment]
Please see this [link ](https://docs.google.com/document/d/1q1WbZIxirjwRtkj_TlE8Hu03rAmZb69Ik164CnXBdwA/edit?usp=sharing)for the August newsletter draft
