### ISSUE TITLE
Red Barn Food Forest Walking Path and Just Food Signage

### ISSUE THREAD

**Issue by natashafcf** [ForetCapitaleForest/actions#126]
This Project consists of two categories of work that already have GitHub issues:

## 1. Charter for Walking Path

Issue: https://github.com/ForetCapitaleForest/actions/issues/81

Working Document: https://docs.google.com/document/d/1Dm85ow-m7hqEQYScQKQHtlMCpkfLbNULx92_6Mbv0wY/edit#heading=h.dhvuvrnaa4yk

## 2. Signage Design and Template (includes way-finding signs for Just Food)

Issue: https://github.com/ForetCapitaleForest/actions/issues/120

Signage Folder: https://drive.google.com/drive/u/1/folders/1sXUhWSO_cEqp9dT_lUx-jmvW-0imxd1z

Proposed SIgnage Design Timeline: https://docs.google.com/document/d/1Miwh9xsT_PHtVKBx-lwnB3sRQll8YsNG0n0kYtFBTus/edit

**Comment by natashafcf** [comment]
@smlambert to review guidelines and content information (as tagged in document)
https://docs.google.com/document/d/19WspV_Wd09o1PxuOCY0zCxylhuSIfSNDMOb1Hiw0XSU/edit

Also to look over current Signage versions (vertical, will be horizontal as discussed in last meeting) for colours. Can also look at wayfinding sign example, see folder "Signage For Review" below:
https://drive.google.com/drive/u/1/folders/1rYPbG8CBlF44NRhENRQzABGijQPWW1KI

**Comment by natashafcf** [comment]
An update by Phil to build our FCF Signs:

    in the barn—accessed through the south sliding door—are 16 bags of concrete, one each for the 16 signs
        along with an unassembled wheelbarrow, also part of that 2019 grant
    in the southwest cargo container under the solar installation are
        eight 8-foot-long sonotubes
            ...to be cut in half, thus producing sixteen 4-foot-long sonotubes, one for each sign
        eight 10-foot-long 4x4 posts
            ...to be cut in half, thus producing sixteen 5-foot-long 4x4 posts, one for each sign
                the posts would be cut on a 45-degree angle
            ...unfortunately, several of these 4x4s were compromised [e.g. cut into small pieces] and are no longer fit for purpose, so more will have to be purchased
    the plan was 
        to dig 16 holes, in the appropriate spots
        put a sonotube in each hole
        Put a post in each sonotube
        mix a bag of concrete, pour it around each post, setting each post at the correct height—with the 45-degree angle up, and 'facing' the path—and allowing the concrete to set
        bring the sign to the appropriate post, and screw it on
    what this would look like when complete can be seen just north of the barn, facing the parking lot, at the Just Food community Farm.
    the height of each sign, when complete, would be 3-4 feet—allowing it to also be read by children and those who are seated

**Comment by natashafcf** [comment]
@MartinNesbitt @InnesBuck see above comment!

**Comment by smlambert** [comment]
I do not intend to provide pictures.

Quick-crete and wheelbarrow (purchased 2 years ago as part of an Tree Canada Edible Trees grant that Just Food and I did for the community food forest) are in the barn, but to be moved by us out of the barn as there will be construction in the barn starting soon.  The concrete can not get wet, so I will plan to move it either to the greenhouse.

We have 8 holes dug, with sonotubes in them now.  Provided its still possible, I _may_ target to cut a post on the weekend and verify with Moe that we are good with the 30" measurement from centre of the 45 degree angle cut.
