### ISSUE TITLE
FOMB 2022 Grant Submission

### ISSUE THREAD

**Issue by natashafcf** [ForetCapitaleForest/actions#127]
FOMB 2022 Grant Submission document below:

Proposal Draft: https://docs.google.com/document/d/1Osg4P15h6A2nnYH-wgKPMhYpXM79OGgl/edit

Proposal Budget: https://docs.google.com/spreadsheets/d/17KP7hk_c2uMSfccd6M89vVjHN04W-c2a/edit#gid=919876558

Supplemental Materials: https://drive.google.com/drive/u/1/folders/10axfvD_bC5i_ESEdXvFkf478YYtWy1vM

**Comment by natashafcf** [comment]
@StephMcNeely @smlambert 
All above for review!

**Comment by MartinNesbitt** [comment]
I've update the grant proposal to include the information we talked about in last week's Thursday meeting. 
Please see the links below for the updated verisons:

Proposal Draft: https://docs.google.com/document/d/1gIdKT1_JlnR6Nwa_dNzp5FQTLpRSGhQJ/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true

Proposal Budget: https://docs.google.com/spreadsheets/d/1P_eSEqN08vld-AZZVAL5wePRkI6RHnhD/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true

Feedback is welcomed for further editing! @smlambert @StephMcNeely

**Comment by StephMcNeely** [comment]
@MartinNesbitt @KaviGK @gabbylajeunesse @smlambert @jodinewman  
Confirmed today that there was no response back from Friends of Mer Bleue regarding our questions as to why the grant was denied.  We should consider this closed and seek other opportunities to fund this same initiative.

Another great project to apply for funding for is: Living Lab in Field 3 for school learning (soil experiments) .

Can someone please create a new issue that tracks grant applications and potentially FCF calendar reminders for grants that are annual (e.g. reminder 3 months ahead of time).  Also check out:
https://www.otf.ca/our-grants
