### ISSUE TITLE
Ottawa Sustainability Fund application

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#129]
Prepare a submission to apply to the Ottawa Sustainability Fund (EnviroCentre fund)

- [x] Make Achillea Endeavours aware of this incoming request ASAP (as they need lots of lead time to process submissions)
- [x] Form to be filled out is found [here](https://forms.gle/Mm5ocHkrKzALkfuh7) 
- [x] Work on a draft in a shared file [here](https://docs.google.com/document/d/1EaCh37X-_GqNOytF7RLMVOrzbTXmZozvlzaCBpTNxtY/edit?usp=sharing)
- [x] Review and approve submission (by Stephanie and Shelley) to send to Achillea Endeavours
- [x] Review changes by Achillea and make final submission

**Comment by StephMcNeely** [comment]
Natasha - link to greenhouse is here:  https://plantagreenhouses.ca/collections/sungrow/products/sungrow-32?c=ca

**Comment by StephMcNeely** [comment]
@natashafcf I had a few minutes to look at the linked draft above.  If you are working in a different doc, can you please send me the link (and update link in GitHub)?  I also couldn't find the Excel sheet for costs.  Are you still planning to send @StephMcNeely a draft tomorrow?

**Comment by natashafcf** [comment]
1) [Project Budget](https://docs.google.com/spreadsheets/d/1b5naC5CuKsiYdw5Zjk1jGDQmkqrDdlsK/edit?usp=sharing&ouid=116907685836575486421&rtpof=true&sd=true) in Excel format
 2) [List of Board Members](https://docs.google.com/document/d/1rvAnMaSY9WtA1hzCVg2Z8P2p5LIyPSdTaWU-t5tQ6-A/edit) (name, position, occupation, email address) in PDF format 
 3) Completed [Workplan](https://docs.google.com/document/d/1eDme4DaFS6tFjAJOze5eJOrUiM0slnY_/edit?usp=sharing&ouid=116907685836575486421&rtpof=true&sd=true) in Word format 
 4) [Charitable Partnership Agreement](https://drive.google.com/file/d/1ZGy9H4GDLZ4CmI5_yKg4ifMfE33Xbxho/view?usp=sharing) (only if there is a charitable partnership as part of the application) in PDF format

**Comment by StephMcNeely** [comment]
Notes:
AE were notified on August 22, 2022 and requested 25 days prior to submission = target of Sept 12 draft; submission on Sept 19.
Draft submitted on Sept 12th... AE comments rec'd on Sept 21 and final documents returned to FCF on Sept 24  (one week later than expected).
