### ISSUE TITLE
Investigate off-grid rainwater collection systems

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#133]
Some examples, for reference:
https://www.instructables.com/Stand-alone-rain-collector/
https://www.grainger.ca/en/product/TARPAULIN-DRAINAGE-CUT-SIZE-5X5FT/p/GGM3ZRU3
https://modernsurvivalblog.com/survival-skills/calculate-gallons-of-rainwater-runoff-from-a-tarp/

**Comment by smlambert** [comment]
We can also do this as a low priority.  I believe we will plan to purchase some mobile water tanks to take to sites that can help fill water totes without relying on water services which have a higher cost than we would like to pay.

https://www.amazon.ca/Collapsible-Large-Capacity-Container-Portable-Emergency/dp/B09YY4LDNL/ref=sr_1_23_sspa

and an electric water pump

**Comment by smlambert** [comment]
Raymond says he can put a 1000L water tote in a trailer and tow it to sites, and I have procured a [water transfer pump](https://www.amazon.ca/gp/product/B0B1HW1X98/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1) to move water from tote to tote.  Getting a couple of short hoses to use.  

@MartinNesbitt - are we ordering a water tote for use as the "in-trailer" one, that Raymond would use over and above those that will be placed at the new sites?

**Comment by smlambert** [comment]
Given we have a story for filling water totes now, this investigation issue can be closed.

**Comment by MartinNesbitt** [comment]
> Raymond says he can put a 1000L water tote in a trailer and tow it to sites, and I have procured a [water transfer pump](https://www.amazon.ca/gp/product/B0B1HW1X98/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1) to move water from tote to tote. Getting a couple of short hoses to use.
> 
> @MartinNesbitt - are we ordering a water tote for use as the "in-trailer" one, that Raymond would use over and above those that will be placed at the new sites?

@smlambert I ordered two totes - one for Aviation and one for Riverside. Perhaps we could use extra totes from the farm as they will be kept at the farm.

**Comment by smlambert** [comment]
Perhaps, we will have to check with Moe and also clean them.
