### ISSUE TITLE
TD Environmental Leaders Grant Reporting

### ISSUE THREAD

**Issue by natashafcf** [ForetCapitaleForest/actions#142]
As this placement has come to an end, we have until December to: 

- [x] Finish the report (written by myself and the student Team Leader - [Can be reviewed here](https://drive.google.com/file/d/1MlPRfHjThwisIQG9SONy0L0yFsx-wl7W/view?usp=share_link)), @smlambert @StephMcNeely 
- [x] Provide Natasha with copy of receipts ([receipts needed here](https://docs.google.com/spreadsheets/d/14fj-2nXCnyh-vOvmhAuWqh8MkzmMfmrbnCEaWBXNR9k/edit#gid=0))
- [x] Provide a [statement of expenditures](https://docs.google.com/spreadsheets/d/18qIYvLoC_PWz-FIiDUIAlicrzhr_cfYarzIcDnKvpG4/edit#gid=0) with invoice and original receipts.

For now, we need to:

- [x] #157

**Comment by StephMcNeely** [comment]
@natashafcf - please see new <modified budget> tab on this spreadsheet and let me know how that might fit with what we discussed on Monday:
https://docs.google.com/spreadsheets/d/1fBfWVVgH8eqPs0SH5LEIRRybtysW3BsK/edit?usp=sharing&ouid=105766462348532382756&rtpof=true&sd=true

We will need yours and @Pepe-Fifi  help to polish this up a bit to turn this into the "event" it needs to be to both fit the Project described to uOttawa/ TD and meet student's outcomes for the work.
Let me know when you're ready to discuss.  Copying Simona and @smlambert

**Comment by natashafcf** [comment]
Awesome, thanks!

**Comment by Pepe-Fifi** [comment]
Hello Natasha, 

Here is a short supply list for seed collection: 

[Seed_Collection_Supply_List.docx](https://github.com/ForetCapitaleForest/actions/files/9569470/Seed_Collection_Supply_List.docx)

Hope it will give you a orientation for budget; I have not included the pricey item in the list, just the more affordable items

**Comment by Pepe-Fifi** [comment]
Hello FCF team,

I am available for discussion tomorrow, either at our regular meeting or
after, as I have not followed the TD grant proposal process and I don't
know if the event proposed is a workshop, a tree planting event or a tree
seed foraging event. If it is the last one, I will be interested to
contribute some ideas, if required.

Thank you:

Simona

**Comment by StephMcNeely** [comment]
Final agenda here:  https://docs.google.com/document/d/1VJ8TCdE38ho1oQr7QElkHLWULBnATHtY/edit
Review by @smlambert @Pepe-Fifi   Send out on Monday, Oct 3 after FCF meeting 

Eventbrite sign up:  https://www.eventbrite.ca/e/430622031087
Can be linked to Facebook - post Oct 3

@natashafcf some changes to budget to discuss - see items in red

**Comment by smlambert** [comment]
Agenda looks good to me.  Recognize that you hope it will be final but knowing that on event day, we can also adjust if needed (based on many variables, like weather forecast etc).

**Comment by natashafcf** [comment]
RECEIPTS

Here's what's still needed for collecting receipts, also updated in highlighted yellow here[https://docs.google.com/spreadsheets/d/14fj-2nXCnyh-vOvmhAuWqh8MkzmMfmrbnCEaWBXNR9k/edit#gid=0]() :

- [ ] Dendrotik Tree Protectors (the ones that were already ordered) @smlambert 
- [ ] Dendrotik Tree Protectors (the second more recent order that was to be purchased) @smlambert 
- [ ] Ritchies Tree Squares @smlambert 
- [ ] FGCA Seed Manuals (the original purchase, ones that Simona used for her training) @StephMcNeely 
- [ ] Lowes Large shovels @smlambert 
- [ ] Straw from local farmer @smlambert 
- [ ] Canadian Tire: ziploc bags, tarp clips, burlap tree and shrubs protection, tarp @smlambert 
- [ ] NVK Nursery Tree Seedlings (also identifying which 200 units) @smlambert 



Two actions/needing approval for receipts already submitted:

- [ ] Hog's back water refill receipt[https://drive.google.com/file/d/141HUaqnfntad9QspGTt2Lor8D-kqYvIP/view?usp=share_link]()  is dated for June 30th, I want to confirm it's okay to use (I think it is because students planted in July too right? Let me know!) @StephMcNeely 
- [ ] For the Nanabush Food Forest invoice[https://docs.google.com/spreadsheets/d/1I7t7ohT0cJaOFc51UDQGDgQu5c9juNYSGqsinyUXFfU/edit#gid=790763898]()  (speaker fee and audiovisual equipment), I'm changing the invoice submitted date for October 15, 2022 to fit with the timeline, but also an address needs to be filled out for Nanabush (once approved/finished I can export as a pdf) @smlambert @StephMcNeely

**Comment by StephMcNeely** [comment]
Already discussed for water tote refill with that date. OK.
Stephanie updated Nanabush invoice as Shelley is not charging gst. Note that event date and invoice dates are almost always different... very few people can do same invoicing ;)

**Comment by natashafcf** [comment]
Okay, I wanted to confirm as the original invoicing date was dated late October, I thought we would want the invoice to be issued before the event date (to be paid on a later date)!

**Comment by StephMcNeely** [comment]
@StephMcNeely  will pull together an FCF invoice for the 90 trees planted at Hogs Back (some planted with students).

**Comment by natashafcf** [comment]
The final parts of the evaluation report will be here FYI:

- [Program Report](https://docs.google.com/document/d/1qmDZm_MK9VBDRivpm4jBXImF3D-et0Z92cvV5AwZvM8/edit)
- [Testimonials Summary](https://docs.google.com/document/d/1lvQBR4w3oDypfyEGH1Yj4sBuaUU2eINLH17inEjnlwA/edit)
