### ISSUE TITLE
Aviation Parkway Workback Plan

### ISSUE THREAD

**Issue by InnesBuck** [ForetCapitaleForest/actions#145]
## This is still going to be worked on

  - Date Oct 17, 4:00 pm to 5:30 pm
  - Prep can occur the day of the event
    - This lessens the amount of time trees need to be left unattended/cared for prior to the event 
  - Delayed start date means that watering the potted trees is very important

| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
| ASAP | &#9745;  Contract review | @StephMcNeely & @Ctaylor405  |
| 4 weeks out | &#9745;  Parking arrangements | @InnesBuck  |
| September 19th | &#9745;  Volunteer numbers brainstorm | @InnesBuck  |
| September 20th | &#9745;  Volunteer email, CAs email | @InnesBuck  |
| September 20th | &#9745;  Contact Raymond in regards to using trailer for event prep | @StephMcNeely, @InnesBuck  |
| September 20th | &#9745;  Contact La Cite in regards to help with event | @StephMcNeely, @InnesBuck  |
| October 14th| &#9745;  Volunteer Reminder, Questions? | @InnesBuck  |
| Oct 17th | &#9745; Moving tree stock to the site, preparing digging sites  | @InnesBuck @MartinNesbitt  |
| Oct 20th | &#9744; Thank you post, event summary  | @InnesBuck |

### Site Preparation

# - One thing that needs to be added to future planting work back plans is the soil assessment of a site (to determine whether we will need a delivery of soil/compost from Greely
- [x] Initial site selection
  - Initial prep will be done by the NCC contractor
  - They will mow the site and spread a layer of mulch over the site
- [x] Day of prep, Oct 17, 2022
  - [x] Bringing trees to site
  - [x] [Shovels](https://www.lowes.ca/product/shovels-spades/scotts-fiberglass-d-handle-round-point-shovel-1633287), gloves, wheelbarrows
  - [x] Setting up H frame signs for clear meeting destination

### Materials and Equipment
- [x] Trees (species/numbers) 
- [x] Compost
- [x] Tree guards
- [x ] Signage
- [x] Hospitality
  - Figuring out where to park for the event
  - This will serve as our meeting site, tables, H frame signs will help too
  - Should make clear with signs and tents/tables perhaps
- [x] Porta-potty
  - Arriving Friday Oct 14, pick up will be Oct 17
  - Key is under right 
- [x] Bring a water jug for refills

### Volunteer Coordination
- [X] Identify volunteer needs and sources @InnesBuck can you please cc the Comms email when you put these email requests out for assistance?
  - Will be useful for site prep the morning of the event, maybe the night before as well
  - Manor Park Community Association is likely source, along with some Orleans groups, others can be contacted too
  - Volunteer list emailed
- Have a volunteer/participant sign-up sheet?

### Promotion
- [x] Finalize and approve signage
  - Will use our H frame signs
- [x] #208
  - After the event

### Event Day Logistics
- [X] Weather forecast (call it)
  - Will check 3 days out before making any calls

### Evaluation
- [ ] Post-event email
  - To volunteer list 
- [x] Post-event social media/blog post; @InnesBuck please ensure these are approved by @smlambert or @StephMcNeely when drafts are ready. NCC needs everything vetted by their Communications team prior to posting

### Planting with a Plan
- [x] Site photography 
  - Can we get John for this event? @smlambert 
- [x] Monitoring and Maintenance Plan
  - Will plan for similar strategy as we have implemented at Hog's Back
    - Water tote, buckets, CA communication/outreach

### Meetings 
- [NCC](https://docs.google.com/document/d/1Wtlt9OxsvyIp-_JI_Fdk450YxYU6hFsLp7UBu-fMPwU/edit) September 12th
- [NCC](https://docs.google.com/document/d/1Wtlt9OxsvyIp-_JI_Fdk450YxYU6hFsLp7UBu-fMPwU/edit) September 23rd

**Comment by InnesBuck** [comment]
The tree species ordered for the planting:
- Yellow birch - 40 ordered (NC) 1’ - 2’ 
- Hackberry - 40 ordered (NVK) 40 cm 1g
- Basswood - 40 ordered (NVK) 60cm 1g
- Ironwood - 37 ordered (NC) 6” to 1 ft
- Black walnut - 40 ordered 40cm 1g
- American mountain-ash (1-2 feet in height) - not yet sourced... (not sure if I can get this one)

**Comment by smlambert** [comment]
and as a note, NCC said to not worry about the American mountain ash, so it can be removed from the list

**Comment by InnesBuck** [comment]
Alternate Boys and Girls Club Event Ideas
- Planting the oaks in the seedling hub at the Farm 
- Seed stratification workshop

**Comment by smlambert** [comment]
Closing this as completed.
