### ISSUE TITLE
Investigate Solar Possibilities at the Farm

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#148]
goal: to see if we could hook up solar to our base of operations (eg to power a saw, or charge the whipper snipper, turn on lights in a greenhouse).  

- [ research]
- [ "business case"] 
- [ presentation]
- [ final report]  

Goal to complete project by early November

**Comment by smlambert** [comment]
Please note there is a solar project at the farm on top of the 4 shipping containers near the large greenhouse, there are many solar panels that power the barn, washstand, honey hut and other things.  A collaboration between Bullfrog, Just Food and possibly some government grant.

If you wish to charge whipper snipper batteries, you can use the extension cord that runs the greens dryers at the wash stand.
