### ISSUE TITLE
Tree Forum 2022: Early Lifecycle of Trees

### ISSUE THREAD

**Issue by natashafcf** [ForetCapitaleForest/actions#158]
**Workback Schedule**

- [x] **October 3rd** - Finalize [speaker list and agenda](https://docs.google.com/document/d/1VJ8TCdE38ho1oQr7QElkHLWULBnATHtY/edit), post Eventbrite
- [x] **October 3rd** - Have [waiver](https://docs.google.com/document/d/16hf_NGZMSDRWCMevaFKssgxFblD9oaPj/edit?rtpof=true) attached to Eventbrite 
- [x] **October 5th** - Order [business cards](https://drive.google.com/file/d/1DFUuoSanBYIwxt4MH5tDRbCmhDPtyiHR/view?usp=sharing) online and Seed Manuals
- [x] Before Friday **October 7th** /thanksgiving - Seed manuals, Participant Kits
- [x] By **October 5th** (to allocate $500 tree stock to speaker fees) - Confirm Budget Change from uOttawa 
- [x] By **October 11th** - Get invoices for Speaker Fees, Audiovisual Equipment, Meeting Venue
- [x] **October 13th** - Purchase Light Refreshments
- [x] **October 13th** - Confirm photographer for event, see [photo album](https://photos.google.com/u/1/share/AF1QipOq-XHg1oJYme-yJ6gUc2gzOasot1W3RfcCkXZAgwKjLDL4QvvrvQDWe6rOWFp2XA?pli=1&key=d211QnRqeG1FRGRWZWFETk5WZUl1Qm81bEE5aFdR)
- [x] By **October 15th** (to be put in central location) - Copy of all presentation slide decks from speakers into [this folder](https://drive.google.com/drive/u/1/folders/1mELlqAXbRGQjprFyWA6yse9oKnvVRMUR)
- [x] **October 16th** morning - Set-up and test run of speakers 
- [x] **October 17th** Confirm rest of purchases
- [x] **October 17th** Place all receipts in this [folder](https://drive.google.com/drive/u/1/folders/1ZfFUArLx1BQPgf4Ygcc2EnKI5baUFSq4)
- [x] **October 17th** [Draft email](https://docs.google.com/document/d/1mVqjmnENaHvwvWE3Kn_aaVxJekfIbsbYUMQdzJ3FYkE/edit) to send out along with poll
- [x] **October 18th** Send out [poll](https://docs.google.com/forms/d/1X7BgG5xvtokdItaCQepkmYGFEOI1Fgldat6wbvC3xoQ/edit) on how the event was, suggestions for topics/speakers next year

**Comment by natashafcf** [comment]
@InnesBuck @smlambert @MartinNesbitt @Pepe-Fifi @StephMcNeely 

Here is a checklist for the draft email to send out tomorrow along with the poll:

- [ ] Ottawa Food Forest survey link
- [ ] Fruit tree arborist information
- [ ] City of Ottawa Trees and Trust Program
- [ ] Annie's Contact information 
- [ ] Links to the slides from the presenters (FCF introduction, Food Forest from Shelley, Seed collection from Simona)
- [ ] Link to Seeds of Ontario Trees & Shrubs

**Comment by StephMcNeely** [comment]
@natashafcf what did you find out from uOttawa about our submission of expenses?  I don't think I was copied on any recent emails

**Comment by natashafcf** [comment]
I haven't heard a response yet, was going to forward once that came in and ensure future responses are "reply all"!
