### ISSUE TITLE
Winter prep at base of operations

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#159]
- [x] Drain and role up hoses
- [x] Whippersnip tall grass around fruit trees
- [x] Tree guards on fruit trees
- [x] Plant remaining large potted trees
- [x] Mulch all trees more to use up remaining wood chips
- [x] Put smaller potted trees into seedling area
- [x] Clean up area around greenhouse 
- [x] Store empty pots into white cubic yard bag outside of greenhouse
- [x] Gather and store tools in shed and white cubic yard bag outside of greenhouse
- [x] Spray tree tops with Bobbex to protect against deer browsing
- [x] Assist rolling up some of the larger irrigation lines
- [x] Add netting to maple/birch tree row in seedling area

**Comment by MartinNesbitt** [comment]
Aviation Planting Site

- [ Tree Guards]
- [ Ensure trees are heavily mulched]
