### ISSUE TITLE
Complete a website audit and fix errors

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#16]
Click into each page and post and fix errors that are found.

Example:
https://foretcapitaleforest.ca/thank-you-south-nation-conservation-and-councillor-catherine-kitts-merci/
has an image in it that does not load.

**Comment by smlambert** [comment]
I have removed the job postings that were out of date (mentioning application deadlines in the path and also referencing Nicole's email address).  Also had images that did not load (were not referencing the right location in the uploaded images location).

**Comment by smlambert** [comment]
I've removed Awelana and Nicole from the "Our Team" page.  Do we want to add others?

**Comment by smlambert** [comment]
Updated the projects page with the text I had written rather than the text that referenced hosting annual festivals (which is not a priority in our capacity building phase versus many other priorities we have).

**Comment by smlambert** [comment]
Events page should be updated to include the 2022 events (like those listed in https://github.com/ForetCapitaleForest/actions/wiki/2022-Tree-Planting-Events-and-Requirements).

**Comment by smlambert** [comment]
Menu & Site map:

**Home**: WIP, static page from our 'About' page, make sure it reflects the updated Vision/Mission from strategic plan
- About: 
  - [Our Team](https://foretcapitaleforest.ca/about/our-team/) - UPDATED, via 
  - [Jobs - Postes](https://foretcapitaleforest.ca/about/jobs-postes/) - WIP, we should likely state we are not hiring atm on the jobs page
  - [Contact](https://foretcapitaleforest.ca/contact/) - WIP, could use some refinement in wording
- [Projects](https://foretcapitaleforest.ca/projects/) - WIP, this used to be Projects & Events, overhaul in process, Events will be just those blog posts in the Events category, Projects page had a minor overhaul, but could use details drawn out of https://github.com/ForetCapitaleForest/actions/issues/103 diagram
- [Volunteer](https://foretcapitaleforest.ca/volunteer-2/) - WIP, goes straight into the volunteer form, but could use more description and we would like to automate the process of capturing the information from it (rethink the approach here), also change the funny form name volunteer-2
- [Donate](https://foretcapitaleforest.ca/donations/donate/) - goes straight into the "Donations" plugin form.  Some work has been done to look at other plugins and approaches via https://github.com/ForetCapitaleForest/actions/issues/14 but nothing completed
- [Resources](https://foretcapitaleforest.ca/resources/) - WIP, we should consider the contents of this page, organized by things we produced and by external resources (and link some form of the Master Plan and Strategic Plan here)
- [Blog](https://foretcapitaleforest.ca/foret-capitale-forest-blog/) - COMPLETE, this page lists all blog posts sorted by most recent and has a side menu to get at the different categories of posts (could consider adding a tag cloud in the side menu)

**Comment by smlambert** [comment]
Other notes:
- Replace random internet image of trees with our own photos (to make it more real)
- We have links to our facebook and instagram on the side menu, and twitter and facebook "share" icons on each post and page, they have different functions but is it confusing?
- Review all content on static pages
- Consider how to lokalize or google translate and give translations of all static pages (and sets it depending on users computer locale). We can leave the blog post language choice up to the author.

**Comment by MartinNesbitt** [comment]
Additional Comments on updating a the website [here](https://docs.google.com/document/d/1pAP7_llbC1Y-viKkvs8obaAjbVNp9tjHx9NM6LxIv4o/edit?usp=sharing)

**Comment by smlambert** [comment]
Consider adding a link to the dashboard from the resources page and additionally add a blog post about metrics and tracking

**Comment by smlambert** [comment]
I've added the hubspot plugin to our wordpress, and linked to our hubspot account.  We can look at using hubspot forms for the volunteer sign up, so that they are automatically added to our contact list.

**Comment by smlambert** [comment]
Mark as closed, we can open a fresh issue with new tasks as resources allow.
