### ISSUE TITLE
The Future of Onboarding Process for FCF

### ISSUE THREAD

**Issue by natashafcf** [ForetCapitaleForest/actions#185]
This action outlines the future of FCF's hiring and onboarding process for new employees.

Within the 'Human Resources' folder, there are three relevant folders:
- 'Hiring' - location for general job posting documents, a template for job postings and letterhead for job offers, as well as a collection of applicant resumes (that will be private).
- 'Onboarding' - location for templates for onboarding of new hires, including documents like emergency contact, a welcome document, a timesheet template, tutorials, and project summaries. The content within this folder is intended to serve as a complete welcome package, of which a copy will be made and placed in an employee's personal sub-folder within the 'Team' folder.
- 'Team' - location for each employee's HR documents and resources, intended to be private for each employee. To onboard a new hire, a folder will be created with their full name, and their job offer letter, and a copy of their timesheet template and onboarding documents from the 'Onboarding' folder will be placed here. One of the first steps for a new hire will be giving them access to their folder, and have them start going through and filling out the documents. In the future, employee timesheets, and paystubs will be recorded and filed within this folder. Once an employee is no longer working with FCF, their employee folder will go in the 'Employee Archive' subfolder that will be private. It should be noted that each employee folder will be private and only accessible to the employee.

**Comment by InnesBuck** [comment]
For the 'Onboarding' folder:
- [Innes' Testimonial](https://docs.google.com/document/d/1rQr14MDaiECBWIj_NTd--xU90agyNr9weFZSPtPNypI/edit)
  - To serve as an example of what tasks/projects I worked on during my time at FCF
  - It also discusses the flexibility of working remotely and in person during the planting season
