### ISSUE TITLE
Review Interactive Map Blog Post to be Published

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#196]
Please review the draft blog post for the city-wide interactive map. The blog post is named ``Interactive Project Map` in Wordpress.

Once published, I can share this page to community associations when reaching out regarding for forest stewardship.

Thanks!

**Comment by smlambert** [comment]
@MartinNesbitt - big thumbs up on the draft blog post.  👍 it's ready to publish (nice that you embedded the map into the page)!
