### ISSUE TITLE
Tree Inventory Planning for Tiny Forest Project

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#200]
https://docs.google.com/spreadsheets/d/1tx_jPAqOD2Geuu5yYULp5n7PkLuhiSvkP2jeauWURQE/edit?usp=sharing

The planning tab for the Tiny Forest project partnering with Envirocentre and OCH is called "OCH planning".

We could regularly update this tab regarding the planning of the stock required for this project. Furthermore, it also outlines a few assumptions for the stock planning.

For the entire project we need 750 trees, 750 shrubs, and 750 forbs (250 each per site).

**Comment by smlambert** [comment]
Thanks @MartinNesbitt - and I will loop you into the email conversation started yesterday with EnviroCentre on how we intend to plan for and procure stock for this project.

**Comment by smlambert** [comment]
Met with folks from Envirocentre and we agreed to start with our existing assumptions of 3 tennis court sized plots (that can each hold ~250 trees, 250 shrubs, 250 forbs).  

One plot to be prepped and planted in late spring, and 2 plots to be planted in fall (and TBD, perhaps they can be prepped in spring, which could simplify booking of equipment, reduce need for separate drops of inputs, etc).
