### ISSUE TITLE
TD Arbor Day Project Timeline

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#209]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Activity Category | Description | Results | Start Date | End Date | Status
-- | -- | -- | -- | -- | --
Planning | Finalize site locations. | Three sites selected in partnership with OCH. |   | February 28 |  
Planning | Pending approval of project, sign and return Grant Agreement and W9 Form. | Signed forms returned to Arbor Day. |   | February 28 |  
Planning | Attend 1-2 planning calls with Arbor Day and other invested parties. | Agreement on plan moving forward with confirmation of dates, addressing any questions. | March | August |  
Planning | Develop planning documents (communications, outreach/engagement, materials, timelines, budgets, etc.) to ensure the project is well planned and achieves the stated outcomes. | One working planning document with all project deliverables and details. | February | April |  
Planning | FCF to contribute to the local application of the Miyawaki Method, inform the site selection criteria, forest design, species selection, planting and monitoring strategy. | Information (to be included in the above planning document) that outlines specificities of each site moving forward. | February | May |  
Planning | Coordinate to host planting days (exact number will depend on various factors and will likely be more than one day per site) to install three tennis sized court Tiny Forests using the Miyawaki Method. | A decision on number of planting days TBD for 3sites. | February | May |  
Planning | Develop a site selection matrix with key indicators to ensure sites achieve the project outcomes and goals. | 1 Site Selection Matrix document. | February | May |  
Planning | Prepare documentation to implement a forest monitoring plan for each site in partnership with FCF, EnviroCentre and OCH. | A three-year monitoring plan, based off of FCF's previous work with the Miyawaki Method and Afforestation Plan | February | June |  
Planning | Prepare documents and training for partners to adopt and manage the Tiny Forest, post project funding. | Information document to be shared with community partners and agreed upon prior to tree planting. | February | June |  
Planning | Prepare Health & Safety training and ensure that all planters (staff/volunteers) are trained in the Miyawaki Method, as well as health and safety protocols and PPE (abiding all public health and safety guidelines regarding COVID-19). | Information document to be shared with all volunteers and community partners, agreed upon prior to tree planting. | February | June |  
  |   |   |   |   |  
  |   |   |   |   |  
Community outreach | Initiate community engagement plan within the Ottawa Community Housingneighborhood where the planting will occur (flyers, information session, presentations,newsletter content, etc), recruiting and training volunteers (from within the communityand through our partners), and coordinating delivery of materials and supplies. | Each site will involve 1 flyer to promote informationsession, 1 presentation to be given at 1information session, 2 newsletters beforeinformation event on social platforms, 1recruitment and training session for volunteers, 1newsletter to coordinate delivery of materials andsupplies. | April | August |  
Community outreach | Host capacity building sessions for community groups (associations, schools,businesses, etc.) to provide training and knowledge sharing about tiny forests,biodiversity, afforestation practices, forest monitoring, and environmental damagerestoration. | A series of capacity building events (exact numberto be determined). | April | November |  
Site Prep | Securing tree stock and materials needed for each planting site. | Tree stock inventory, delivery, storage for eachsite with confirmed dates. | May | September |  
Site Prep | Finalize site preparation activities, including subcontracted services to dig/prepare soil,mix nutrients, lay stray, prepare tree supports, prepare temporary fencing. | Plan and deadlines for site preparation. | May | September |  
Site Prep | Conduct the site preparation activities, including any permit requirements (if required),locates, etc. for the site. | Each site is prepped for activities, ready for treeplanting. | August | September |  
Tree Planting | Plant three tennis court sized (minimum size) “Tiny Forests” using the Miyawaki Methodof Afforestation. Plant 250 native trees, 250 shrubs, and 250 forbs in each Tiny Forest(total of 2,250). | 1 tree, 1 shrub, and 1 forb will be planted persquare meter. | September | October |  
Tree Planting | Finish other design elements within each Tiny Forest. | Each site will have a walking path, one bench, 2signs and temporary fencing (recommend keepingin place for the first three years). | September | October |  
Community outreach | Document increased green space and biodiversity in low income communities which willreduce the heat island effect and contribute to environmental equity in Ottawa. | Develop educational materials, web content,signage, social media content, blogs. | April | November |  
Community outreach | Deliver public tours/educational presentations/webinars about “Tiny Forests” and theMiyawaki Method, as well as the project outcomes, including how the Tiny Forest modelcan be used in a variety of locations and vary in size in order to scale across the region. | A series of public educational tours, exact numberto be determined. | October | November |  
Monitoring and Maintenance | Begin administering the watering plan/strategy at each site once planting is finished. | An established water source for each site, alongwith documentation in place to recordmaintenance activities by community members. | August | November |  
Monitoring and Maintenance | Implement monitoring and maintenance protocols for each site. | To occur after tree planting has concluded at anygiven site. | October | November |  
Evaluating and Reporting | Document preliminary monitoring and maintenance plan to assess and adjust protocolas needed. | Video, sheets, written findings to be assessed byFCF, EnviroCentre, OCH and provide adjustmentsto protocol as necessary. | October | November |  
Evaluating and Reporting | Proposed projects completed, community members to provide ongoing support andmaintenance of sites moving forward. | Tree planting is finished at all sites. | - | November 13 |  
Evaluating and Reporting | Write final evaluation and accomplishment report. | Final report and collection of additional materials is processed/written in by FCF in partnership with Envirocentre | September 1 | December 1 |  
Evaluating and Reporting | Final submission deadline for all evaluation reporting documents. | All final documents have been submitted to Arbour Day | - | December 15 |  

</body>
</html>

**Comment by MartinNesbitt** [comment]
Project Deliverables

- [ ] 1 Site Selection Matrix - May
- [ ] A three-year monitoring plan, based off of FCF's previous work with the Miyawaki method and afforestation plan.  - February
- [ ] Prepare documents and training for partners to adopt and manage the Tiny Forest, post project funding. Information document - February
- [ ] Prepare Health & Safety training and ensure that all planters (staff/volunteers) are trained in the Miyawaki Method, as well as health and safety protocols and PPE (abiding all public health and safety guidelines regarding COVID-19). Information document -February
- [ ] Initiate community engagement plan within the Ottawa Community Housing neighborhood (flyers, information session, presentations, newsletter content, etc), - April
- [ ] A series of capacity building events/workshops (exact number to be determined). -April
- [ ] Develop educational materials, web content, signage, social media content, blogs. Focus on increased greenspace in low income communities - April
- [ ] A series of public educational tours, exact number to be determined. - October
- [ ] An established water source for each site, along with documentation in place to record maintenance activities by community members. - August

**Comment by StephMcNeely** [comment]
@MartinNesbitt this sounds like the project plan for the OCH Tiny Forests... is there something specific to the Arbor Day project written up anywhere?
