### ISSUE TITLE
Wildflower Seed planting / Stratification Event Workback Plan

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#215]
### Planning
| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
| 4 months out | &#9744;  Begin landowner conversations | |

### Site Preparation
- [ ] Initial site selection

### Materials and Equipment
- [ ] Trees (species/numbers)
- [ ] Compost / mulch
- [ ] Tree mats / guards
- [ ] Signage
- [ ] Hospitality
- [ ] Porta-potty
- [ ] Covid related materials

### Volunteer Coordination
- [ ] Identify volunteer needs and sources

### Promotion
- [ ] Finalize and approve signage

### Event Day Logistics
- [ ] Weather forecast (call it)

### Evaluation
- [ ] Post-event email

### Planting with a Plan
- [ ] Site photography
- [ ] Monitoring and Maintenance Plan

**Comment by smlambert** [comment]
Closing as not needed.
