### ISSUE TITLE
2023 Hiring

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#225]
- [ ] create general manager/ exec director job description
- [x] #226
- [x] post one Ag Canada Youth job - https://agriculture.canada.ca/en/programs/youth-employment-and-skills
- [x] Consider an Apprenticeship job (Eco Canada)
- [ ] Consider EHRC as of April 1st for a first-year apprentice in a Red Seal trade OR is registered as a full- or part-time student at a Canadian post-secondary institution (Empowering Futures)

**Comment by StephMcNeely** [comment]
@smlambert see the Ag Canada link. Might work for the FCF/ Birch Path shared position

**Comment by smlambert** [comment]
- for the Ag position, I think we are a fit, as the eligibility criteria also mentions
  - Agricultural businesses, such as **greenhouses**, **orchards**, vineyards, or vegetable producers
  - Businesses who supply **agricultural** products or **services**
  - Food processors
  - Agricultural related non-governmental organizations (**NGOs**)

- Assist in carrying out the soil and biodiversity study is being conducted on Tiny Forest demonstration plots that were designed to be food-bearing focused (taking samples, collaboration with U of Guelph)
- help develop and gather a few other metrics of interest for such systems like edible tiny forests and community food forests (some ideas: approximations on amount of food harvested, time it takes to harvest, quality of food harvested in this system / brix, etc).  
- assist with propagation of more food-bearing shrubs/trees
- help create a demonstration agriforestry alley in the far field (we could have Aviva and/or tour groups participate also)
- gather information on indigenous examples of food forest systems (like the one mentioned in https://ottawafoodforests.com/2021/05/27/inspirational-indigenous-forest-gardens/)
- periodic site visits to the Red Barn food forest and Birch Path Healing Forest to assist with seasonal tasks

**Comment by smlambert** [comment]
Presume we can mark this as closed.
