### ISSUE TITLE
Create Supporters page for the website.

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#228]
Begun a [draft](https://foretcapitaleforest.ca/wp-admin/post.php?post=1318&action=edit) 

Need to gather the list of supporters (orgs, companies, individual), and their logos.  Also, consider categorizing into levels of support (gold, silver, bronze, in-kind), or some thing like that.  Consider how to handle this page in terms of yearly support. 

Look at other examples out there:
https://www.khanacademy.org/about/our-supporters
https://www.marsdd.com/supporters/
etc

**Comment by smlambert** [comment]
Related to the rework of the website (being done on the staging server at capitalforest.ca).

**Comment by jodinewman** [comment]
Separate funders from partners
