### ISSUE TITLE
Host capacity building sessions for community groups (associations, schools, businesses, etc.) to provide training and knowledge sharing about tiny forests, biodiversity, afforestation practices, forest monitoring, and environmental damage restoration.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#246]
A series of capacity building events (exact number to be determined).

Iteration 4.

To be completed after the planting?

**Comment by smlambert** [comment]
Status?  Which project / grant / funder is this for?

**Comment by smlambert** [comment]
Assigning a bunch of stuff to you @MartinNesbitt as I think much of it may now be completed and leave it to you to assess and close.
