### ISSUE TITLE
Securing tree stock and materials needed for each planting site.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#247]
Tree stock inventory, delivery, storage for each site with confirmed dates.

inventory to be conducted once snow melts (seedling area). confirm numbers (and set aside/pot up) and ensure backups.

**Comment by smlambert** [comment]
For our potted stock (trees, shrubs and forbs), we can start to group them by our species selection and fall planting plans per site (after our July 7th site visits).  

| Site | Number of species | Soil notes | 
| --- | --- | --- |
| OCH 1 (Riverdale) |  | 
| OCH 2 (Esson) |  || 
|  OCH 3 (xxxxxx) |  || 
|  York school | ||

**Comment by jodinewman** [comment]
Closing as duplicate of #353
