### ISSUE TITLE
Print and procure signage

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#254]
Print and procure permanent signage for the OCH Tiny Forests. The signage is planned to be installed in the spring alongside the other community amenities (birdhouses, community libraries). 

Requires approval/consultation with OCH on final placement of the community amenities and final signage procurement from the printing company.

**Comment by smlambert** [comment]
Status?

**Comment by smlambert** [comment]
This is signage for OCH Tiny Forests, anything more needed here?

**Comment by MartinNesbitt** [comment]
Moving this to 2024 Q2 project as we plan to pick it up in April.

**Comment by smlambert** [comment]
Can you add more detail into the title and description about what signage this issue refers to (good to be very specific in both places to avoid confusion and make it very easy to understand when looking at items in a project plan table).
