### ISSUE TITLE
Add Master Plan to the website

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#26]
Add as a permanent resource, but also a blog post announcing it (see [shared doc](https://docs.google.com/document/d/1AY8Uh6gyTwgk44QX0sI7wKPIxpi0bhCMnl82-msVnSw/edit?usp=sharing) for blog post content), and master plan pdf in [shared drive](https://docs.google.com/document/d/1AY8Uh6gyTwgk44QX0sI7wKPIxpi0bhCMnl82-msVnSw/edit?usp=sharing).

**Comment by smlambert** [comment]
There is a draft page ready to publish https://foretcapitaleforest.ca/wp-admin/post.php?post=572 but we have a page bloat on the website, and we should revisit the site map to make sure pages and forms remain organized and tidy before more sprawl.

**Comment by natashafcf** [comment]
- Thank FOMB when publishing online
- Board of Directors to review and confirm Mission and Vision

**Comment by natashafcf** [comment]
I've decided we should post our Afforestation Framework Concepts to the website as a blog post instead of the whole master plan. @smlambert is this something I can just make on the website builder and wait to post?

**Comment by smlambert** [comment]
What I presume we should do is if we are hosting a file called Afforestation Framework Concepts, to add it to a new page on the website, then create a draft post (to be reviewed) that points to it with some extra description around the creation of the Master plan and what it is to our organization.

**Comment by natashafcf** [comment]
Perfect, starting a draft word document linked below:
https://docs.google.com/document/d/13vuWsXmkGKuZeQUzXecXXFf3UEfUikXjDJxsL2UA4HI/edit

**Comment by smlambert** [comment]
Consider not referring to it as "master plan" but prefer "afforestation plan".

**Comment by smlambert** [comment]
Uploaded and updated https://foretcapitaleforest.ca/resources/, closing as complete.
