### ISSUE TITLE
Document preliminary monitoring and maintenance plan to assess and adjust protocol as needed.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#261]
Video, sheets, written findings to be assessed by FCF, EnviroCentre, OCH and provide adjustments to protocol as necessary.

Iteration 13-16

**Comment by smlambert** [comment]
Watering plan: 
- water weekly if not 1" rain in the week, until dormancy of trees
- weeding at least 2x per year (as per Miyawaki method)
- site audits in spring and fall, where we take photos and take some simple measurements of plant growth

**Comment by smlambert** [comment]
@MartinNesbitt - is anything still owed to EC and OCH?  and if so, please give details on what is needed to mark as complete.

**Comment by MartinNesbitt** [comment]
Yes, after a discussion with EC earlier this week. We can send over any monitoring and maintenance documents we've already created. I'm thinking the infographics and care instructions we've created for the other sites. In addition, they've also requested a very brief outline of a monitoring and maintenance plan (bulleted list format). These would be resources that OCH and the community would use.

**Comment by MartinNesbitt** [comment]
Draft Document ready for review: https://docs.google.com/document/d/1zLvjDTn742WubLlHrtEFyWY-3FcaAQqldFF1gKv2YUA/edit?usp=drive_link @smlambert

**Comment by smlambert** [comment]
Thanks @MartinNesbitt - I have added some comments and updates.

**Comment by MartinNesbitt** [comment]
Thanks @smlambert ! I've sent EC a copy adjusted from your comments. Marking as closed
