### ISSUE TITLE
Determine date for the Arbour day project launch event

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#269]
A project launch event will be held in conjunction with one of the planting events to garner media attention and generate public awareness and support of the Tiny Forest projects. 

- [ ] Coordinate with EnviroCentre and OCH to determine a date for the media event/planting date 
- [ ] #270 (MUST be confirmed 6 weeks in advance)

**Comment by jodinewman** [comment]
@MartinNesbitt Do we have a date selected yet?

**Comment by smlambert** [comment]
October 26th is the suggested date - but Brodie from EnviroCentre is actioned to ask for confirmation from OCH that they are okay with the event (which will be open to the public) and the date.
