### ISSUE TITLE
Write out CIMA+ event scenario to send to CIMA+ and NCC

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#289]

**Comment by StephMcNeely** [comment]
@MartinNesbitt here are my notes from April 3, 2023 meeting with NCC. Can you include these 4-5 activity options within the Event Scenario?  https://docs.google.com/document/d/1yj9VWJXv1336-YLNsm_sJuKyncYUrJr4Ff2qUuivYPk/edit?usp=sharing

**Comment by MartinNesbitt** [comment]
Thanks Stephanie!

Please see the link to the event scenario outlining the 5 activity options. https://docs.google.com/document/d/1tQTC66zC4dgEbZIXs-ZwQY3lRUqS9fb70agvscb_RBg/edit?usp=sharing

@StephMcNeely @smlambert

**Comment by StephMcNeely** [comment]
Great job Marty - I made small edits and sent to NCC :)
