### ISSUE TITLE
365 Report template due June 2023

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#29]

**Comment by MartinNesbitt** [comment]
365 Report Working Document: https://docs.google.com/document/d/1KOZ34EZ6kbSVP-1MjHLLI6BSS8xsplNX5abDjC5Aqdo/edit?usp=sharing

**Comment by StephMcNeely** [comment]
@MartinNesbitt 
The NCC is asking about our 365 report (which is now late for Site 2 and very late for Site 1). I checked the working doc and this is very thin.

The questions to answer are really what’s the story on what was originally planted (Site 1 and Site 2), what additional trees were planted, if any. What interventions did we have (with details on watering care, whipper snipping, etc).

Just need a couple pages long, perhaps with a few photos.

Also note to @KaviGK and @gabbylajeunesse to start working on these for any new sites (Tree Canada plantings don't technically count but may be a good practice)

**Comment by MartinNesbitt** [comment]
@StephMcNeely Thanks for the update. Yes, the document only had a few initial notes in it. I will write it up the reports for the two sites today. 

Also, a note to @KaviGK and @gabbylajeunesse, the FCF Staff tree stewardship checklist will keep track of our activities/interventions and help us write up the reports. So it's useful to fill it out whenever we go onsite. Thanks!

**Comment by MartinNesbitt** [comment]
@StephMcNeely please see the draft 365 Report for:

- [Hog's Back 2021](https://docs.google.com/document/d/1KOZ34EZ6kbSVP-1MjHLLI6BSS8xsplNX5abDjC5Aqdo/edit?usp=sharing)
- [Hog's Back 2022](https://docs.google.com/document/d/1V_VzRRlFiXqJZjfYYKXEuptYzOtqznfjDuE4hCl2jC4/edit?usp=sharing)

**Comment by StephMcNeely** [comment]
@MartinNesbitt or @jodinewman please see what Andy's comments are and make similar changes to HB2022 before I review.  Thanks

**Comment by MartinNesbitt** [comment]
Thanks Stephanie, I've made some edits and suggestions to Andy's comments. I've uploaded and edited a copy of the report that has Andy's comments on it to the Shared Drive: [Report with Andy's Comments](https://docs.google.com/document/d/1s8rzLklzlaCavIjyPhxZCy71exLQXe02/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true)

There are few comments/questions from Andy that I've tagged @StephMcNeely and @smlambert as they will be able answer them.

**Comment by MartinNesbitt** [comment]
@jodi to start 365 report for HB2
