### ISSUE TITLE
Write an OSCAR write up for the Ottawa Centre Tree Planting Initiative

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#291]
Write an OSCAR write up for the Ottawa Centre Tree Planting Initiative. This would be for the May edition of the newspaper. And garner interest from the community for the tree giveaway and mass planting stewardship.

**Comment by MartinNesbitt** [comment]
switch this up for the june/july edition of the oscar. it will be a recap of the mass planting event along with a call for stewardship. 

The messaging can be  "hey! your community has a new urban forest here. It relies on your help to grwo into maturity." along with a call for stewardship.

**Comment by MartinNesbitt** [comment]
@MartinNesbitt to add relevant info to write up the blurb

**Comment by KaviGK** [comment]
Have submission ready for the September edition before August 18. In the mean time draft a social media post to share with the community facebook page

**Comment by KaviGK** [comment]
[OSCARS social media post & September edition draft](https://docs.google.com/document/d/1dgGIXQhqwpowPLsjYld8iOzBbAlH1IPuDhgyl937Rv0/edit)

**Comment by MartinNesbitt** [comment]
need to approve first

**Comment by KaviGK** [comment]
Closing as it was not followed up. To pick up again for 2024 spring issue
