### ISSUE TITLE
Set up drip irrigation in seedling area. use grey hose behind the FCF shed.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#300]
Currently most of the seedling area can get watered by the hose that runs to it, so that can be happening (and the farthest part hand-watered) until this can be setup.

**Comment by MartinNesbitt** [comment]
Planning to do this on Tuesday, July 18th. Correct me if I'm wrong or that time doesn't work.

**Comment by smlambert** [comment]
The grey hose by the greenhouse is for the hugel mound.  I will defer putting drip hose in the seedling area until after we create the raised beds, since that will involved tilling and would shred the drip lines.

**Comment by MartinNesbitt** [comment]
Closing this issue as the we may not need to install it this fall.
