### ISSUE TITLE
Transplant Y number of select trees for spring plantings into 1g pots (PIPCI_Gatineau/BalsamPoplar, TinyForestsSite1/multipleSpecies)

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#303]

**Comment by smlambert** [comment]
Rockland did a bunch of work on this during their visit.

Some still remain, and we will try to complete them with the June 15th Aviva group.

**Comment by smlambert** [comment]
More completed by Aviva.  Still more to go.  

Check if we need to get more pots and what remains.  We should push to complete the rest before July.

**Comment by smlambert** [comment]
Closing as dup of #335
