### ISSUE TITLE
Clean out Logo folder on Drive

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#34]
[Logo folder](https://drive.google.com/drive/folders/1z5_frsyljKKixcYNP1zI_cjltQ3YKI1h?usp=sharing ) contains dozens of files, including a subdir called Final Logo, which contains dozens of different files.  We should discard or clearly mark those that are NOT the official logo to avoid people from inadvertently using incorrect ones.

**Comment by natashafcf** [comment]
@smlambert @StephMcNeely @InnesBuck @MartinNesbitt 
Logo Folder is now organized in the following sub folders https://drive.google.com/drive/u/1/folders/1TGy8XBch0ywJV1dKnNPxiL2WgK4XJRbJ

## For Printing
Transparent Background
White Background
Dark Background

## For Screens (at a lower dpi)
Transparent Background
White Background
Dark Background

## Original Illustrator File
Contains the Illustrator file design
