### ISSUE TITLE
June 14th- All Volunteers Meeting/Event 

### ISSUE THREAD

**Issue by KaviGK** [ForetCapitaleForest/actions#344]
Hi everyone, here is the draft of our All Volunteers meeting plan.  
Please review and add any more ideas or tasks volunteers can help out with this summer/fall. 
Thank you! 

https://docs.google.com/document/d/12ireJTG7cU7iekOopXmANekgDH9J67DYNGLSfbZUWzM/edit?usp=sharing

**Comment by MartinNesbitt** [comment]
Thanks @KaviGK , I've made some comments to the document

**Comment by KaviGK** [comment]
Thanks @MartinNesbitt !
