### ISSUE TITLE
Prep for Volunteer event

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#346]
- [x] post Eventbrite link
- [x] create PowerPoint
- [x]  create [Volunteer Sign up sheet](https://docs.google.com/document/d/1WOkzQJrtuN92G0lubJyI5Pj7RCXSt84Jgdd0Hw58BrM/edit?usp=sharing ) for seed and sign up tables  
- [ ] sort through volunteer skills and expertise

**Comment by smlambert** [comment]
Can reuse parts of the powerpoint created for CIF and Synapcity talks

**Comment by gabbylajeunesse** [comment]
https://docs.google.com/presentation/d/1hPCz5hkcxzY1XdoAakEOTgAVCXV815Ih/edit?usp=sharing&ouid=103415159868210384503&rtpof=true&sd=true

**Comment by KaviGK** [comment]
**Tuesday Staples run for Volunteers event.** 
Please add anything else needed. 

@StephMcNeely  @smlambert  

https://docs.google.com/document/d/1d_S5cnddkPdk3p88YgGyEubfpse8Gknj8-XcrEm2F7w/edit?usp=sharing
