### ISSUE TITLE
Comms and Marketing 2-pager

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#349]

**Comment by StephMcNeely** [comment]
@gabbylajeunesse is this the 2-pager we need for attracting a new board member?

**Comment by gabbylajeunesse** [comment]
@StephMcNeely Yes it is

**Comment by gabbylajeunesse** [comment]
https://www.canva.com/design/DAFlVxwpi_E/9lBSiAT-HLo0QZglX8kdDQ/edit?utm_content=DAFlVxwpi_E&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by StephMcNeely** [comment]
Hi @gabbylajeunesse, the Canva looks nice but not complete until it gets a review.
We don't typically move out of Word until we have a finished, approved product.  Can you convert to Word and action the review to me please?  I have some edits to suggest.  Thanks!

**Comment by gabbylajeunesse** [comment]
https://docs.google.com/document/d/1-cw7-Ynb2yEgjk40jczYq887ukxo2c7JN-OOTMStCwk/edit?usp=sharing
