### ISSUE TITLE
2023 Invoices

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#350]
Finalize a number of outstanding invoices

- [x] Mothers Day Invoice 1 to Forests Ontario
- [x] Mother's Day Invoice 2 to CAFES for event hosting
- [x] #351
- [x] #364

**Comment by StephMcNeely** [comment]
@smlambert the invoices for both ECo Echo were sent and paid, same with Magnolia:  sent & paid 
Let me know for OCH - or add extra 20 trees here:  https://docs.google.com/spreadsheets/d/1Ea96-yWVTmACSM4a8MBqFIOx6c33UU0Pflgf8cOzE80/edit?usp=drive_link

**Comment by StephMcNeely** [comment]
@smlambert or @MartinNesbitt can you confirm the price for Mothers Day Ironwood trees from Ferguson? and if so, is there a receipt?  Otherwise, @smlambert can you provide a suggested list price please ?(e.g. $10 each).
(https://docs.google.com/spreadsheets/d/1T6viPloHkHOA0YCdUb_4m3nPihCk7qoBwrX5H7v6bXw/edit?usp=sharing)

**Comment by StephMcNeely** [comment]
Yes, I have been using yours and Marty's expenses spreadsheets. Thank you. The Ferguson rate for Ironwood seems to be $1.55 (in case Forests Ontario needs a receipt). I didn't think that was correct...

**Comment by smlambert** [comment]
re: https://github.com/ForetCapitaleForest/actions/issues/350#issuecomment-1582470487, that is why I have been doing massive orders of this type of stock from Ferguson.  It saves us the extra step of collecting/stratifying/germinating, and we have healthy good sized seedlings to care for, pot up and use, in some cases for very reasonable rates.

**Comment by MartinNesbitt** [comment]
I`m not able to see the spreadsheet from above - I don`t have access so I think it may be the Directors Shared Drive. Although, the we didn`t receive any Ironwood trees for the Mothers Day Project. We had ordered them from NVK [see the 2nd page](https://drive.google.com/file/d/1XEvCB_KcRi_u6qWodlWknB5gdTTa3qgE/view?usp=drive_link) but they were backordered. All the trees as part of the project came from that order.

**Comment by StephMcNeely** [comment]
RE: OCH invoice  @MartinNesbitt thx for updating invoice. I grouped all same species together in invoice (so you know for next time). @smlambert we should likely break even with this as I'm not sure delivery was factored into pricing. Please confirm what you told Ernesto for maples in 2g pots...  I didn't see that price point in the list you sent him  https://docs.google.com/spreadsheets/d/10WlfxBonV14mtCtyhcDwSn5gC04DY3Ir/edit?usp=sharing&ouid=105766462348532382756&rtpof=true&sd=true

**Comment by smlambert** [comment]
I think there are some errors in that invoice
not all Japanese Lilac are 10g, there are Japanese Lilac 15g x 4
the 2 extra Serviceberry are 10g  not 2g 

You can see the prices that I expected to tell Ernesto in our Core Team Chatroom (Thursday, June 8th).
