### ISSUE TITLE
Create a species list of trees, shrubs, forbs that may be used in fall plantings

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#353]
A request to bring the potential list of species to the public consultations, with the food-bearing, food-producing ones marked with an asterisk.

The sites have different profiles, so will vary slightly in the species list, but not much.  For example, one of the sites is naturally "wetter", so will have species that are more tolerant to those conditions.  One site has more sandy soil, and even though we are amending the soil, this will be a consideration and species will be selected that are more drought resistant and tolerant of faster-draining soils.

**Comment by MartinNesbitt** [comment]
Thanks Shelley for putting this in Github. I was going to use this [document ](https://docs.google.com/document/d/16b9Ye4K4AYUEf7CWEVxWQOJPBw95yIWpzgxZ5cg9hfM/edit?usp=sharing)as a reference and make edits to the species. Most of the trees here are from the seedling area so we'll have to change them to the trees we ordered a few weeks ago.

**Comment by smlambert** [comment]
Plantings that I **know** we will supply trees for (in the order we may need them):
- TC_Siemens2023
- OCH_Riverdale
- OCH_Cutts
- OCH_Esson
- FCF_NationalTreeDay2023
- OpenNCC
- OCH_LargeCaliperFall2023
- YSPS
- OCH_Riverdale_EdibleFringe

Other ones that I **think** we need trees for:
- CIMA_Jacques-Cartier
- LCBO_Aviation

Do not think we need trees for these:
- TC_TwinElm
- TC_RocklandCommunity
- TC_Tanglewoods

**Comment by smlambert** [comment]
Closing as completed
