### ISSUE TITLE
Replace the oak in the picnic circle 

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#355]
Replace the oak in the picnic circle (raise it up out of the blue clay, just as we did for the apples in field 2)

Can either use one of the extra bur oak purchased with Mother's Day order, or pull one of the 2 that are heeled in behind the Nanabush greenhouse.

**Comment by MartinNesbitt** [comment]
Used a bur oak that was heeled in behind the nanabush greenhouse. Planted on June 14th with TC Aviva Group.
