### ISSUE TITLE
NCC sites for Fall 2023

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#361]
See notes here for meeting with NCC on June 12:  warning it is half french/ half english
https://docs.google.com/document/d/1Ia5REdCkht-cwoCtQ8rnvaP91qoqcWzEImR_I8bEi_0/edit?usp=sharing

@MartinNesbitt  to review action list and create Issues as required and assign to other team members if possible
@smlambert there are some items related to tree orders (Sept 23 for Hogs Back Site 3, need a team discussion on Jacques-Cartier park for Sept 30 and potentially involve EnviroCentre)

**Comment by jodinewman** [comment]
[Meeting minutes](https://docs.google.com/document/d/10x6AQS630IbodzQ6VQgm1Pzrjk4zZk50DIxIclYBG_8/edit?usp=sharing) for July 26th. 
@MartinNesbitt could you please review and add anything missing? Thanks!

**Comment by MartinNesbitt** [comment]
Thanks Jodi! I've added some more comments to the meeting minutes

**Comment by smlambert** [comment]
Not sure what action this particular "issue" was supposed to cover, but presume this issue can now be closed?
