### ISSUE TITLE
Thank you to Youth leader Ali

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#363]
Need to write a thank you letter on FCF letterhead to Ali for her fundraising.
We don't know what exactly the funds will go toward but should figure out how many trees that will buy.
Letters here to use as template (for format) - please start a new one (or create a letterhead template for us!)
https://drive.google.com/drive/folders/1vQhGrv7sXXqdDRj-axO01vjt850FWZUa?usp=drive_link

Let's ask Ali if she would be a Youth Leader with FCF and you would commit to meet with her and her friends to see how they want this to evolve (e.g. into a specific project in their neighbourhood, into fundraising for tree seedlings that we grow out at the nursery, etc.).

@MartinNesbitt to pick this up or assign to @KaviGK or @gabbylajeunesse 
Please get a draft letter out to @StephMcNeely by June 20 so I can review and mail it to Ali (I have her address)

**Comment by KaviGK** [comment]
@StephMcNeely , here is the draft of the[ thank you letter ](https://docs.google.com/document/d/123uOQQIZ2pa_klHtTu8MWsPwguKDJZD3tfVE-YDOmmc/edit)

Please review and I can make any changes. Thanks!

**Comment by KaviGK** [comment]
Thank you letter completed last week.  I emailed Ali and Katie to arrange a time this month to talk about next steps.

**Comment by StephMcNeely** [comment]
Letter finalized and in the mail.  @KaviGK see final version here:
https://docs.google.com/document/d/123uOQQIZ2pa_klHtTu8MWsPwguKDJZD3tfVE-YDOmmc/edit?usp=sharing
