### ISSUE TITLE
Enviro Centre for Tiny Forest Project with OCH

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#364]

**Comment by smlambert** [comment]
For awareness, all Tiny Forest Project tasks/issues are labelled with `project:tinyforest2023` and can be viewed by filtering on that label, here is the [current list](https://github.com/ForetCapitaleForest/actions/issues?q=is%3Aopen+is%3Aissue+label%3Aproject%3Atinyforest2023).
