### ISSUE TITLE
TC LCBO fall planting 2023

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#370]
Looks like we need to find a site for this event in East Ottawa. @MartinNesbitt can you confirm?

- [x] Need to find a suitable date. October 17th
- [x] Order trees
- [x] Find community steward, if possible
- [x] Plan planting event

**Comment by jodinewman** [comment]
As per meeting with NCC on July 26th, Sites 2 and 3 at Aviaiton Pkwy are avaiaible for planting. 
@MartinNesbitt to #438

**Comment by smlambert** [comment]
Prior to ordering trees, can we get a confirmation of the number and species for this one?

**Comment by MartinNesbitt** [comment]
The species and counts for the 1st Aviation planting are:
Yellow Birch 40
Common Hackberry 40
Basswood 43
Ironwood 37
Black Walnut 40Therefore, we can assume it's roughly the same count for all
the species. Also, all the species at Aviation #1 have done daily well. I
think we can use the same for the next planting.

Need to confirm with the NCC on this though.
Also, need to confirm with NCC on mowing the area before October 17th and
possibly a mulch/wood chip drop.

Martin Nesbitt

Sustainable Forestry Lead

Forêt Capitale Forest
