### ISSUE TITLE
Add new planting sites to FCF City-wide project Map

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#373]

**Comment by smlambert** [comment]
Moving to Iteration 17

**Comment by MartinNesbitt** [comment]
Updated the City wide project Map. Although, the new map does not have the ability search for the closest projects to you. All the projects are simply visible on the map where you can click on each for more information on the project. 

When making the first edition of the map, I believe we had a free trial which has since been expired, resulting in the inability to add more locations to the map. As a troubleshoot, I used an ArcGIS story map as an alternative.
