### ISSUE TITLE
Update Master Grant List

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#376]
-update master grant list with new prospective grants and opportunities

- [x] - Highlight any upcoming grants
- [x] - begin brainstorm of project ideas specific to grants
- [ ] - Update the list to help us make decisions on upcoming grants (Ex. conditional formatting, notification, etc)

**Comment by gabbylajeunesse** [comment]
https://docs.google.com/spreadsheets/d/1soSRtF1pgGc4J8X6DnGHXSg_aL-bHvq7/edit?usp=sharing&ouid=103415159868210384503&rtpof=true&sd=true
