### ISSUE TITLE
order Chip Drop to site between May 25 and June 3

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#38]

**Comment by smlambert** [comment]
I see this is related to the Hogsback contract, adding details that this issue is to order chip drop to Hogsback site.  I will create a second issue for ordering chip drop to Just Food Farm.

**Comment by StephMcNeely** [comment]
- [ ] @StephMcNeely to confirm Greely Sand order for Hogs Back (mix of topsoil & compost) by Tuesday, May 31
- [ ] @StephMcNeely to confirm with NCC that wood chips will be delivered by June 3rd

**Comment by StephMcNeely** [comment]
@MartinNesbitt , I placed an order for soil delivery at Hogs Back.  it will be delivered Thursday June 2 sometime between 7am and 7pm.  Can you plan to get there if it arrives before 11:30am and I'll try to cover if it arrives after?

**Comment by MartinNesbitt** [comment]
Sure, I can plan to be there if it arrives before 11:30 am. Will they shortly call shortly before it arrives similar to NVK tree deliveries?

**Comment by smlambert** [comment]
This can now be closed as completed.
