### ISSUE TITLE
Tree Canada Invoices

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#382]
I've put together working invoices for the two tree canada projects:

1.  [Queen Elizabeth Public School CTG](https://docs.google.com/spreadsheets/d/1BGMaZX9fnA8JPj8esK19pTCpYllFrgqVTvt6A2MOMdU/edit?usp=sharing)
Linked above is an invoice for our participation and guidance for a TC Community Tree Grant. It is only for our attendance and guidance on the grant recipient's planting day.

I wanted to confirm everything with you before I submit this Invoice to Rebecca.

2. [TC Aviva](https://docs.google.com/spreadsheets/d/1eDv_6NrquPrCvSYylpNAIdvgryhiA-QT/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true)

I've written a report for this event using tree canada's Forestry Specialist reporting tool. I need to include an expense form and invoice before I submit  the report. I have a few questions for the both of you regarding the expenses for this project. You'll be able to see them as comments on the second page of the spreadsheet.

**Comment by MartinNesbitt** [comment]
@StephMcNeely , I've added some more details on the Aviva contract. we have a budget of $4500. I'm assuming it's the same breakdown as the PIPSC Gatineau contract where $3500 can go towards material expenses and $1000 towards our staff coordination.

Also looking for a final confirmation of the CTG invoice to submit to Tree canada.

**Comment by StephMcNeely** [comment]
@MartinNesbitt thanks for these two invoices.  Just sent you an email follow-up to finalize.

**Comment by MartinNesbitt** [comment]
Both invoices and associated final reports have been submitted.
