### ISSUE TITLE
TC Aviva Event Blog Post

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#384]
https://foretcapitaleforest.ca/wp-admin/post.php?post=1638&action=edit

Blog post for the TC Aviva event at the BoO on June 15th.

**Comment by smlambert** [comment]
I have made a few minor edits, otherwise LGTM (looks good to me).  Is it something we should also get a review from Tree Canada on?  I know that there is likely some wording in our Forestry Specialist agreement with them regarding communications.
