### ISSUE TITLE
Follow Up with UoGuelph regarding NCC particpation of the biodiversity study

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#391]
Would we ask NCC to join the uGuelph soil study for a fee? If so, what is fee, would FCF do soil samples, etc.? (Action: FCF to follow up with uGuelph).

https://docs.google.com/document/d/1Ia5REdCkht-cwoCtQ8rnvaP91qoqcWzEImR_I8bEi_0/edit

**Comment by smlambert** [comment]
Where is this request coming from?  
Presuming it is regarding including a Tiny Forest biodiversity study as part of the proposed Tiny Forest in Jacques-Cartier park?

**Comment by MartinNesbitt** [comment]
the request is coming from the discussion with the NCC. If we were to build a Tiny Forest with the NCC and CIMA+ at Jacques Cartier Park. We may want to get that forest involved in the biodiversity study.

**Comment by jodinewman** [comment]
Closing this issue as NCC/CIMA+ have turned down the Tiny Forest proposal at Jacques Cartier.
