### ISSUE TITLE
Mine volunteers for greenhouse build

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#398]

**Comment by MartinNesbitt** [comment]
#366 #367 Instructions to the greenhouse build are found here. Highly recommend team of volunteers to look through this before starting

**Comment by smlambert** [comment]
When you read those instructions you will also see that we may need to purchase a few extra supplies (for a wood base).

**Comment by jodinewman** [comment]
A few volunteers found [here](https://docs.google.com/spreadsheets/d/1OeyXDKzfxkQoCo2TeyjT1_LSJBAZfK2z/edit?usp=sharing&ouid=116630060506976781411&rtpof=true&sd=true)
