### ISSUE TITLE
Consider 2 more 1000L water totes

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#40]
The current 2 are lent by Shelley, but we should consider to purchase two more totes, 1 for Hogsback and 1 for Miyawaki plots

**Comment by smlambert** [comment]
Since we can borrow some of the Just Food totes for the farm solution, we will not need to get more totes immediately.  We could take one of the 2 totes I am lending to FCF to Hog's Back if needed.

**Comment by smlambert** [comment]
@StephMcNeely and @MartinNesbitt have organized to purchase an additional tote from the boyscout sale (at https://rainbarrel.ca/69thscout/) which will get delivered to Hogsback from the organizers by the end of the week.

For the Miyawaki location, we can borrow another tote from Just Food, as they appear to have spare ones available to borrow.

Marking as complete.

**Comment by StephMcNeely** [comment]
Need to locate a pallet or two

**Comment by smlambert** [comment]
There is one pallet at the FCF plot at the farm (where straw bales used to sit) and one at Shelley's Nanabush plot at the farm.  Just need to get them over to Hogsback now.

**Comment by smlambert** [comment]
Reopen until we get the tote setup at Hogsback.

**Comment by StephMcNeely** [comment]
@MartinNesbitt i was able to locate 3 available pallets in my neighbourhood via BuyNothing. I will try to pick them up by end of week and drop at Hogs Back

**Comment by smlambert** [comment]
This can be closed as the tote is in place and filled with water.
