### ISSUE TITLE
Plant Shagbark Hickory from seedling structure in Nut Grove Way

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#403]
@smlambert do you suggest planting level to the ground or above ground similar to the apple and pear trees?

**Comment by smlambert** [comment]
I think we can put it in Nut Grove way and based on the other Shagbark hickory that is in there, which is planted at ground level, that section seems to be less clay, so should be good at ground level.

Before doing this, I would like to find and whipper snip around the existing trees (there are several very small beech trees lost in the grass at the moment).  That way we will know where is the right spot for this hickory.
