### ISSUE TITLE
Research for Tree Cards

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#404]
Research content to be used for the tree cards of trees found in Fields 1 & 2. The cards can be used for workshops and school group tours, and content can be used for the walking path website.

Task assigned to Ahrianna

**Comment by smlambert** [comment]
We should contact and get a quote for how much https://loudmouthprinthouse.com/ would charge for re: finessing the final design template and printing of the cards (and let's do that early, in case the turnaround time is long... we would like these cards for Oct 26th event if possible, though they will be counted as amenities in the project budget, so could get delivered later if too tight of a deadline).  We will also print enough to share with the other sites (Esson and Cutts).

**Comment by jodinewman** [comment]
Contacted Loudmouth Printhouse today for a quote!
