### ISSUE TITLE
Organize and Modify Seedling Structure 

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#406]
- organize the contents of the seedling structure so that it can be used to house germinated seeds from the Tree Seed Collection Team.

1. take all the pots out of the seedling structure and bring them to the large white bags in front of the greenhouse. #431 
2. move all the cardboard in the structure to tree guild 4(the largest tree guild). The cardboard should be placed flat on the ground with the plastic tape and metal staples removed where we are intending to build the patio (there is already cardboard there to help identify where to place the cardboard) #430 
3. Move the the wooden posts to the side of the structure. There should be a clear path/working area in the structure that has not tripping hazards and other safety risks.

**Comment by jodinewman** [comment]
1. Empty pots have been inventoried/organized by greenhouse. Inventory results can be found here: #431 
2. Cardboard has been moved to the area in tree guild 4. Still needs to have tape/staples removed and be broken down.
3. Wooden posts have been moved to the side of the structure. 

The seedling structure could also likely benefit from a quick weeding to clear out the weeds growing inside.
