### ISSUE TITLE
Post Upcoming Volunteer Opportunities

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#407]
- [x] create list of activities for volunteers
- [x] set date for weekly volunteer opportunities
- [x] update the FCF Public calendar with events

**Comment by jodinewman** [comment]
List of volunteer events and prospective dates [here](https://docs.google.com/spreadsheets/d/1yksBjkAjCGI4pENY3lk2DVZzU1jWNvHPYPXQZMlhaHc/edit?usp=sharing). Would prefer to have everyone check over the events and dates prior to me posting them in the public calendar to ensure I am not missing anything and that there are no schedule conflicts. 
@MartinNesbitt @gabbylajeunesse @KaviGK

**Comment by MartinNesbitt** [comment]
Thanks Jodi. Please coordinate with Gabby as she'll put this into the July newsletter that'll go out this week.

**Comment by MartinNesbitt** [comment]
I made some comments to document you sent. Thanks!

**Comment by smlambert** [comment]
Also please cross-reference this [list](https://github.com/ForetCapitaleForest/actions/wiki/2023-Event-List) that is listing some of the known other events happening (in case of overlapping events happening in the same space).  We will also hopefully decide on a date for the AGM this week.
