### ISSUE TITLE
Prep High level budget for Mothers Day planting project 2.0

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#408]
- [ ] Look through current report
- [ ] put together a high level budget for a 2.0 project. Collaborate with Phillippa at CAFES. Have it prepped for mid August
   - dream bigger
   - heavy with the staff

**Comment by MartinNesbitt** [comment]
High Level Budget is currently a WIP. [High Level Budget](https://docs.google.com/spreadsheets/d/10kZbVPVfDiZIld4DY7ZHU7H51Kgv4QQRwi1f8RtwXKU/edit?usp=sharing)

**Comment by smlambert** [comment]
Moving all remaining open issues from 2023 project to 1Q to review and close.
