### ISSUE TITLE
Update Grants spreadsheet with Interesting grants.

### ISSUE THREAD

**Issue by gabbylajeunesse** [ForetCapitaleForest/actions#409]
- [ ] Check master grant list to see which deadlines are approaching within the next 6 months 
- [ ] Choose a grant to focus on and determine what we need to qualify or fill out the grant 
- [ ] Work through selected grant

**Comment by gabbylajeunesse** [comment]
https://docs.google.com/spreadsheets/d/1soSRtF1pgGc4J8X6DnGHXSg_aL-bHvq7/edit?usp=sharing&ouid=103415159868210384503&rtpof=true&sd=true

**Comment by smlambert** [comment]
Tree Canada grants are open right now and close in December: https://treecanada.ca/grants-awards/community-tree-grants/

To apply, we can use the `fcf@foretcapitaleforest.ca` account, which is already registered in their portal.
