### ISSUE TITLE
Tiny forest cost research

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#415]

**Comment by MartinNesbitt** [comment]
@StephMcNeely Please see revised budget for the Jacques Cartier Tiny Forest and event scenario. The prices included more accurately reflect some of expenses list in the event scenario. [CIMA+/NCC Jacques Cartier Preliminary Budget](https://docs.google.com/spreadsheets/d/1WkbkZuEcX58wXuej6z2tIwepDmcYLI09D-CZQcG2Mkg/edit?usp=sharing)
