### ISSUE TITLE
Research phytoremediation methods

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#428]

**Comment by smlambert** [comment]
See also mycoremediation as a cost-effective, efficient method for removing environmental pollutants.

I have oyster (Pleurotus) mushroom mycelium on-hand should we wish to trial it.

**Comment by StephMcNeely** [comment]
We should also be looking at grants for this type of research and/or pilot
project/ study.
Or partner with a research team at a college or university...
For example FCM :  https://greenmunicipalfund.ca/

**Comment by smlambert** [comment]
Need to update due date.
