### ISSUE TITLE
Social media post: New resources available

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#429]
A callout to our friends at EcoEcho who have been hosting a wonderful series of events over the past year

and have now shared video excerpts and educational material from those events at their youtube channel
https://www.youtube.com/@OutaouaisEC

Special callout to the 2 events that Foret Capitale Forest participated in:

Right tree, right location: https://www.youtube.com/watch?v=TAf80yxocBQ
Care and consideration of food-bearing trees: https://www.youtube.com/watch?v=j0PU3c9CZxY

There will be a 3rd video resource produced shortly and available to the channel where we have participated in also.

**Comment by StephMcNeely** [comment]
Slight update to last line.

**Comment by smlambert** [comment]
I wasn't suggesting this is the wording we use for a blog post, just putting ideas here so that a proper blog post can be written.  :)

**Comment by smlambert** [comment]
https://www.youtube.com/watch?v=RVwDZRJtt68&t=7s (Planting a Food Forest) Ooak Productions

https://www.youtube.com/watch?v=1-4ZYfkLr28&t=32s (Right Tree, Right Location-April 22) Gillian Kirkland

https://www.youtube.com/watch?v=j0PU3c9CZxY&t=3s (Care and Consideration of Fruit Bearing Trees-March 25) Gillian

**Comment by smlambert** [comment]
Added to this post https://foretcapitaleforest.ca/food-bearing-trees-in-your-personal-edible-landscapes/, closing as completed.
