### ISSUE TITLE
Move cardboard from seedling structure to tree guild 4

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#430]
We want to lay a heavy layer of cardboard onto a square on tree guild 4 (where we will eventually put an arbor).  We also want to clean up the seedling structure.

To achieve both of these goals, we need to move all of the cardboard from tree seedling structure to tree guild 4 (you will already see there is some cardboard there).  Remove tape and staples from cardboard, break it down so it is completely flat and place it onto the arbor square.

**Comment by jodinewman** [comment]
Cardboard has been moved to arbor area in tree guild 4 > still needs to have staples/tape removed and be broken down

**Comment by AhriG** [comment]
Staples have been removed & Cardboard has been broken down
