### ISSUE TITLE
Purchase spare battery for transfer pump & whipper snippers

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#433]

**Comment by smlambert** [comment]
Status? 

Also, the tranfer pump is owned by Shelley.  Determine if we liked that approach and if we would use the same approach next year.  If so, purchase a pump for FCF.

**Comment by jodinewman** [comment]
Will be purchased as part of TDFEF grant.  
(And pump as part of Mer Bleue)
