### ISSUE TITLE
BoO: Establish the ditch crossing sites for the walking path

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#435]
We have 5 10ft (12" diameter) HDPE drain pipes purchased.  In order to have safe and passable by people and tractors crossings, we will put 
- 2 10' pipes in the ditches to cross from Field 2 to Field 3 (near the seedling area)
- 2 10' pipes in the ditches to cross from Field 3 to Field 4 (closer to Innes and the back corner of the Tiny Forests Demonstration Plots)
- 1 pipe to be cut in half to give 2 5ft pipes for use to enter Field 2 (just past the blue shipping container) and Field 3 (just before the long hugel that runs parallel with the road)

To properly establish these crossing sites:
- Dig shallow trenches for the pipes
- Put an amount of gravel on either side of the pipe (up to 6" depth, halfway up the side of the pipe
- Top with soil
- Compact the soil
- Plant grass seed into the soil 

This will give us a contiguous walking path, that can be mowed and crossed with tractor, lawn tractor and safely by walkers.  We should remove all wooden crossings at the same time, as these are degrading quickly, slippery when wet and a growing hazard to cross (liability to our organization).

**Comment by smlambert** [comment]
- 2 crossings are in place between Field 2 and 3.

TODO:
- 2 Crossings between Field 3 and 4
- 1 crossing from road into Field 2 (just past the blue shipping container)
- 1 crossing from road into Field 3 (just before long hugel that runs parallel with road)

We also decided that we will make the last 2 crossings listed as full 10ft ones (and not cut the pipe into 5ft lengths) as it allows for easier access into the site by tractor and ride-on lawn mower.  This means we should purchase an additional pipe.  We should also look into Field 5, and determine if we should install another crossing somewhere out there (as we build out the various activities in that space).

**Comment by jodinewman** [comment]
Include small pipe under soft spot by shipping container to put irrigation hose through

**Comment by smlambert** [comment]
> Include small pipe under soft spot by shipping container to put irrigation hose through

Does someone want to source a 4" HDPE pipe for this purpose or shall I?  Would also recommend getting a second 4" one for the entry from road into Field 3 (near the long hugel mound) where the ditch is too shallow for a larger diameter pipe.

**Comment by jodinewman** [comment]
We ended up using a different method for the irrigation pipe crossing the road.

There is a 4" HDPE pipe that can be used for the entrance to Field 3 from the road.

**Comment by Matthewtennant** [comment]
could benefit from purchasing additional 2 pipes (for entrance into seedling structure and into tiny forest) as well as purchase of gravel (half a load, not much needed)
