### ISSUE TITLE
Secure a sponsor

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#437]
Need to secure sponsors for the following projects:

- [ ] Hog's Back Site 3 
- [ ] Mer Bleue

Plan for planting in 2024.

**Comment by smlambert** [comment]
Tree Canada interested to help for Mer Bleue - which of their grant programs is this under and what next action is needed by us to secure funding?

**Comment by StephMcNeely** [comment]
@Martin Nesbitt ***@***.***> needs to prepare a
draft budget as per email request from Tree Canada
Draft needs to be reviewed by @Stephanie McNeely
***@***.***>  prior to submission

**Comment by smlambert** [comment]
Consider also a Treemendous Community Grants

**Comment by smlambert** [comment]
Need to assign this to one or more folks.

**Comment by jodinewman** [comment]
Funding for Mer Bleue Phase 1 applied for through Tree Canada's Operation ReLeaf (#492) and Treemendous Communities grants (#505).
Discussion in Dec 8th meeting regarding CIMA+ as a potential funder for Hogsback Site 3 (to be discussed in meeting with NCC #559)

**Comment by smlambert** [comment]
A list of other funding for planting projects:
https://networkofnature.org/Community-Planting-Grants.htm

Should check if they are the same set as in our spreadsheet or not.

**Comment by Matthewtennant** [comment]
funder secured for all projects listed. community planting grant link copied to potential partner doc for future use.
