### ISSUE TITLE
Communicate with NCC tree inventory

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#44]
We will be short some Ironwood for the June 4th planting.  Ferguson plans to pot more up for fall 2022, but does not have any available this spring.

Here are the numbers of what we have for June 4th, 291 trees in total:
https://github.com/ForetCapitaleForest/actions/wiki/2022-Tree-Requirements#hogsback-with-cimancc

Red Maple 38 x 1g (NVK1)
Beech 1 x 1g (NVK1) + Beech 25 x 2g (FCF)
Bur Oak 30 x 1g (NVK1)
Red Oak 30 x 2g (NVK1&NVK2)
Sugar Maple 50 x 1g (H. Richardson)
Balsam poplar 50 x 1g (Ferguson)
Yellow birch 17 x 1g (NVK2)
Basswood 50 x 1g (NVK2)
Still need Ironwood and want more yellow birch. 

Recommend that we finish / fill in with Ironwood in the fall when we can get some additional stock for Hogsback.

**Comment by StephMcNeely** [comment]
Shelley, I think 250 is all we committed to so that should be plenty. We can infill the ironwood later. I'll let NCC know

**Comment by smlambert** [comment]
Okay perfect, thanks @StephMcNeely !

**Comment by StephMcNeely** [comment]
@StephMcNeely emailed Cedric at NCC with this list:
Red Maple (35), 
Bur Oak (30), 
Red oak (30), 
Beech (25), 
Sugar Maple (40), 
Balsam poplar(40), 
Yellow birch (15), 
Basswood (30), 
Ironwood (0) - pas disponible - en planter cet automne.

Total of 250 trees to plant with CIMA plus 30-40 trees from 2021 to replace with:  Sugar Maple (10), Balsam poplar(10), Yellow birch (2), Basswood (15).  Roughly 287 trees for CIMA to plant on both sites.  FCF to return in fall with Ironwood

**Comment by StephMcNeely** [comment]
****### June 2 update:**  @MartinNesbitt copying you for double checking as we load **
Red Maple (38) - all located at CFF (Community Food forest)  [3 at Site1]
Bur Oak (30) - 20 at CFF + 10 large bare root @Greenhouse/ picnic table
Red oak (30) - 10 at FCF plot + 20 at CFF
Beech (25) - 15 new potted at FCF plot; 11 + 1 grouped at CFF [+2 for Site#1]
Sugar Maple (50) - @Greenhouse with 5 per pot (need to repot @Hogs Back) - [10 for Site #1]
Balsam poplar(50) - potted @Greenhouse  [40 at Site2; 10 @Site 1]
Yellow birch (15) - 17 @FCF plot [2 at Site #1]
Basswood (30) - bring 40 1 gallon + sub in 10 in 2 gallon pots @Greenhouse - [35 at Site2; 15 @Site 1]
Ironwood (1) -FCF plot... need to return to Hogs Back to plant in fall
= 251 trees at Site#2 and 47 for Site#1 = 293

Also pack:  shovels, 250 coco mats, 30 empty 2 gal pots, 
May not need wheelbarrow... What about water tote?
Shelley will bring paw-paw seedlings, cups and possibly fungi + wood chips

**Comment by smlambert** [comment]
Marking as complete, any further / future inventory activities can be done under a new issue.
