### ISSUE TITLE
EPIC: TD FEF Grant

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#441]
Workplan for the TD FEF grant. Relevant documents can be found in [this folder](https://drive.google.com/drive/folders/1PGJOyf2d0kWj5VLBGKp4KYbgXQ0UKGaB?usp=drive_link).

### Planning
| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
| 4 months out | &#9744;  Begin landowner conversations | 

###Finances
- [ ] create working expense tracking sheet

### Signage Designs
- [x] #442
- [x] #443
- [x] #444
- [x] #445

### Build Signposts
- [ ] #446
- [x] #447

### Community Engagement
- [x] #448
- [x] #449

### Plan Celebratory Event
- [x] #450
- [x] #451
- [x] #452
- [x] #453
- [x] #454

### Evaluation and Maintenance
- [x] #455
- [x] #456
- [x] #457
- [x] #458
- [x] #459

**Comment by KaviGK** [comment]
TD FEF submitted on November 17th, 2023. Report submission conformation can be [found here.](https://drive.google.com/file/d/15mwowkPkPUBSpCNjvdS_morAB9Eeas5i/view?usp=drive_link) 

Closing as Done. To follow up with  updating the Redbarn loop website in December/January, digging the rest of the sign pots in spring 2024.
