### ISSUE TITLE
Finalize signage descriptions

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#442]
- [x] Finish edits to draft signage descriptions
- [x] Finalize descriptions. Confirm the content found on the signages as well as identifying key words for translation.
- [x] Send quote to Win Translation for [indigenous translation](https://docs.google.com/document/d/1Pyokg6KxJmsl6jRNLNPGCOu6g4R3rnNdeGIMWYo0qUE/edit)

**Comment by jodinewman** [comment]
[Link to signage document](https://docs.google.com/document/d/1c5s-_jul3wFaH6fwy6n1kSiro6ndmwqsNHDCmmHuFLQ/edit)

**Comment by KaviGK** [comment]
@smlambert @MartinNesbitt  @jodinewman @gabbylajeunesse 

Please review [edited signage](https://docs.google.com/document/d/1c5s-_jul3wFaH6fwy6n1kSiro6ndmwqsNHDCmmHuFLQ/edit?pli=1) starting on **page 7**. Use this[ map](https://www.google.com/maps/d/edit?mid=13YMargIqrHqo_8njCgVDbi4RYQQz3gE&ll=45.42756490834726%2C-75.5784827701599&z=18) to see location of signage as you read . 

All descriptions have been edited to 90 words and 45 words for ones with diagrams.  Expect for the Welcome & Map sign. 

 Indigenous key terms are highlighted in yellow. Please suggest better key themes.  Once finalized I will compile the JF project key terms [here](https://docs.google.com/document/d/1Pyokg6KxJmsl6jRNLNPGCOu6g4R3rnNdeGIMWYo0qUE/edit) , along with the other common 10 terms for future FCF projects. 

Thx!

**Comment by KaviGK** [comment]
@StephMcNeely 

Please review [French translations](https://docs.google.com/document/d/1c5s-_jul3wFaH6fwy6n1kSiro6ndmwqsNHDCmmHuFLQ/edit)  when you get the chance. I'am hoping to pass on the document to Natasha and  finalize the temporary signage for next week. Thx!
