### ISSUE TITLE
create survey to track progress on qualitative outcomes

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#456]
https://docs.google.com/forms/d/e/1FAIpQLSdBe2wqHtqKQDn5Izmygo_ep2fdwewmOvYTnwhhWpG4mPS_fw/viewform?usp=sf_link

**Comment by smlambert** [comment]
Status?

**Comment by KaviGK** [comment]
[Walking Path survey](https://docs.google.com/forms/d/e/1FAIpQLSdBe2wqHtqKQDn5Izmygo_ep2fdwewmOvYTnwhhWpG4mPS_fw/viewform?usp=sf_link)

**Comment by KaviGK** [comment]
Closing as complete
