### ISSUE TITLE
Begin writing notes and drafting the TD FEF final report

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#458]

**Comment by jodinewman** [comment]
[Draft report document](https://docs.google.com/document/d/1b4iOCEN9_CiUf5__ZU5iaDBRyHXjA0mwf6a6o8PrRuM/edit?usp=sharing)

**Comment by smlambert** [comment]
Being reviewed by @StephMcNeely

**Comment by KaviGK** [comment]
TD FEF submitted on November 17th, 2023.  Report submission conformation can be [found here. ](https://drive.google.com/file/d/15mwowkPkPUBSpCNjvdS_morAB9Eeas5i/view?usp=drive_link)
