### ISSUE TITLE
Check in on and water Hogsback trees

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#46]
As we head into a 2 week hot/dry spell, someone should stop by and check on the trees (and water them with hauled in water if necessary).

**Comment by StephMcNeely** [comment]
@StephMcNeely checked trees on May 25 and removed all tree guards. Leaves sprouting beneath. At least 20 trees to be replaced.  Have about 38 that can be added to Hogs Back planting to replace dead ones. 

- [ ] @MartinNesbitt to help Stephanie inventory trees at Hogs Back Site1 before June 4th
