### ISSUE TITLE
Create an "Our Impact" page for the website.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#462]
This page can be used for fundraising and company engagement.

It can be inspired by [Earth trust](https://earthtrust.org.uk/about/our-impact/) page .

Can include wording similar to "this is what your support helps...". 
Can be backward looking or forward looking. Also use and showcase the dashboard.

**Comment by MartinNesbitt** [comment]
"Our Impact" Page Draft has been created on WordPress and is linked here: https://foretcapitaleforest.ca/wp-admin/post.php?post=2162&action=edit

**Comment by smlambert** [comment]
Moving from 2023 plan to 2024 1Q plan

**Comment by MartinNesbitt** [comment]
The "Our Impact" page will be published to the website once the new website is live. Back up [google doc](https://docs.google.com/document/d/1kyfhLsnQr0XLJZzMDZldf57wOTLrSdwxYAuTg36_ngo/edit?usp=sharing). Adjusting the iteration and deadline accordingly.
