### ISSUE TITLE
Create a case study to show how to build a tiny forest 

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#466]
Similar to EnviroCentre's [case study](https://www.envirocentre.ca/stormwater/) on rain gardens

See #170 - some overlap

**Comment by jodinewman** [comment]
[Draft](https://docs.google.com/document/d/1l2UIEMnW0mBs0tA4ASnDmhlzO5GxLW2VbjpooRywu20/edit?usp=sharing)

**Comment by smlambert** [comment]
See also the Green Communities Canada [Mini Forest training materials](https://drive.google.com/drive/u/0/folders/1-c3dRK3VYQk-djmEoqONrIUUfEhCR5y-) they put out this past spring (which will beg the question, how we de-duplicate effort).

**Comment by jodinewman** [comment]
closing as a duplicate of #170
