### ISSUE TITLE
Create educational brochures 

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#467]
Create educational brochures on tiny Forests/Miyawaki Method to be distributed at tours, presentations, and at the launch event

**Comment by jodinewman** [comment]
[Brochure draft](https://docs.google.com/document/d/1R27Oq3pqWIpunw0IB0pcMYFls7N0qEFUVh1Xg3-nJuM/edit?usp=sharing)

**Comment by smlambert** [comment]
Budget for this item went to producing video.  Will collapse this with #466 and update of resource page to create one document that can help answer the common questions that come in to our org around TinyForests.
