### ISSUE TITLE
Parc Lac Leamy Event Workback Plan

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#478]
### Planning
| Timing | Activity &#9744; &#9745;| Owner | Status |
| --- | --- | --- | --- |
| 4 months out | &#9744;  Begin landowner conversations | |

[Date Set for September 30th.](https://drive.google.com/drive/folders/1C4qlZhBTmlnu2JSUEqYQ5NOBb6LoFGTP?usp=drive_link)
### Site Preparation
- [x] Initial site selection. Parc Lac Leamy was chosen. [Site Map ](https://drive.google.com/file/d/1DAXk0DIEzljfCKnjldaE8TICo9vbWkMl/view?usp=drive_link)

### Materials and Equipment
- [x] Trees (species/numbers).[ Species list](https://drive.google.com/file/d/1DAXk0DIEzljfCKnjldaE8TICo9vbWkMl/view?usp=drive_link) provided by NCC. 
- [x] Compost / mulch. Need to check with NCC to confirm who is supplying the mulch
- [x] Tree mats / guards. Tree guards available at FCF Base of Operations
- [x] Signage. FCF H-signs available
- [ ] Hospitality. Responsibility of CIMA+ to organize. Still awaiting confirmation whether a lunch or a snack.
- [x] Porta-potty. Public washrooms available at [Parc Lac Leamy ](https://ncc-ccn.gc.ca/places/leamy-lake-park)
- [ ] Covid related materials

### Volunteer Coordination
- [ ] Identify volunteer needs and sources

### Promotion
- [ ] Finalize and approve signage

### Event Day Logistics
- [ ] Weather forecast (call it)

### Evaluation
- [ ] Post-event email

### Planting with a Plan
- [ ] Site photography
- [ ] Monitoring and Maintenance Plan

**Comment by MartinNesbitt** [comment]
Thanks Shelley,

We have all those species present at the farm that we can possibly
supplement. The basswoods look good, balsam poplars not so much, and I'm
not sure of the mountain ash.

Marty

Martin Nesbitt

Sustainable Forestry Lead

Forêt Capitale Forest

**Comment by smlambert** [comment]
Okay, well the sooner we can sort and organize all trees into potted groups, the easier it will be to tell what remains to be sourced.  

The mountain ash that was potted up already is now slated for an OCH planting (unless we change the list), and I do not know what remains, if any in the seedling area.  TBD :)
