### ISSUE TITLE
Fall newsletter

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#486]
Newsletter wrapping up fall activities in lieu of a monthly newsletter

**Comment by smlambert** [comment]
Moving to current iteration (17)

**Comment by smlambert** [comment]
Some topics for Fall Newsletter / Yearly Wrap-up:
- OCH / ADF event
- Walking Path update
- Greenhouse photo
- Winterizing, and rolling up irrigation tasks
- Upcoming Holiday Market & year-end fundraiser
- Summary of highlights of the year / dashboard
- Thanks to volunteers for a great year

**Comment by jodinewman** [comment]
Newsletter [draft]( https://docs.google.com/document/d/1bCx9_4oRDPwpzrYLGdvukG9szj8Q9Hb2fVy62BUWMQM/edit?usp=drivesdk), still in progress

**Comment by ShellCrabtree** [comment]
It's posted on the website [here.](https://foretcapitaleforest.ca/fall-2023-newsletter/) @jodinewman was it sent to our list of subscribers as well? Thanks!
