### ISSUE TITLE
Create redbarnloop.ca website

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#490]
For our walking path, we purchases that domain, now needs a website hosted somewhere.

Establish a simple wordpress website with static pages at first (so we can have permanent pages for the walking path QR codes to point at).

**Comment by smlambert** [comment]
Links for QR codes are found in this [document](https://docs.google.com/document/d/18rCxNGz_l9XnABLBqV78hcQcHkn7T8PP2fpO21jJbOM/edit), it may take up to 72 hrs for those to be live (in the meantime the temporary URL is redbarnloop.wordpress.com).

FYI @KaviGK

**Comment by KaviGK** [comment]
@smlambert  Thx! I have send it over to Natasha to create high res QR codes in Red.

**Comment by smlambert** [comment]
redbarnloop.ca is live so I will close this issue.  We will still create tasks to fill in content on each of the pages for each sign, but that can be done later in the year (for now they just repeat what is said on the current signage, but later we will change that to be far richer content).
