### ISSUE TITLE
Operation ReLeaf Proposal

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#492]
Create a Mer Bleue project proposal to send to Tree Canada. TC is totally onboard with the project and have $21,000 available to fund. We are looking at a spring 2024 start for planting.

Materials needed for the proposal:

- [Expected Project Timeline](https://docs.google.com/spreadsheets/d/1x_r3vKv4sAYHXyyB5dafaDtnp1utfA7QKim84sHXjig/edit?usp=sharing)
- [Project Budget](https://docs.google.com/spreadsheets/d/1l8PIBSQFitM_bpuOEWSC1frNkGuSwnNF/edit?usp=sharing&ouid=104658172105924753645&rtpof=true&sd=true) (10% for Admin, 5-10% for site maintenance, 80% for plant stock).
- [Project Proposal/Description](https://docs.google.com/document/d/1nbcFgsMOVJpUa74uY_CO03jdaiWTeDxVzOsKkYUXIJw/edit?usp=sharing)

**Comment by StephMcNeely** [comment]
Thanks for participating and putting the github item in Marty - please let
me know who is assigned to this task.  Add me.
Also add:
-  the one week turnaround to TC
- SM to contact NCC about tornado or derecho damage
- 3rd component is the Plan... which is pretty much what the powerpoint
presentation describes (and that you heard me detail verbally). Needs to be
put into words.
- Plan fall site visit with NCC and TC team
- planting to occur in Spring 2024 and deadline to complete is fall 2024

Thanks,
Stephanie

**Comment by MartinNesbitt** [comment]
Draft documents are ready for review before sharing with Tree Canada @StephMcNeely

**Comment by MartinNesbitt** [comment]
Proposal Submitted
