### ISSUE TITLE
Create sample air pruning boxes

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#498]
To experiment with this approach, would like to create at least one air pruning box for stratifying nut seeds in this fall.

See https://www.youtube.com/watch?v=ab67eKU0ZeY&t=63s as one resource for how this can be done.

**Comment by jodinewman** [comment]
Sample air-pruning box is in greenhouse, will make a new issue to get this set up and seeded

**Comment by jodinewman** [comment]
Sample air-pruning box is in greenhouse, will make a new issue to get this set up and seeded

**Comment by jodinewman** [comment]
Sample air-pruning box is in greenhouse, will make a new issue to get this set up and seeded
