### ISSUE TITLE
Cardboard and compost to the spots in the food forest where future trees will be planted

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#50]
To help restrain the growth of grass.  Not needed for recently plowed areas.

**Comment by MartinNesbitt** [comment]
~35-40 spots placed just west of fruit tree guilds. 05/25/22

**Comment by smlambert** [comment]
Excellent, by the time we go to plant in those spots, the cardboard/compost cover should have killed some of the grass below it, and cardboard will have softened/disintegrated, making it easy to plant through.
