### ISSUE TITLE
Update CanadaHelps page

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#501]

**Comment by KaviGK** [comment]
- [Canada helps page](https://www.canadahelps.org/en/charities/foret-capitale-forest/) as been updated. 

- [Fundraising page ](https://www.canadahelps.org/en/pages/support-ali-and-her-friends-plant-more-trees/) for Youth leader Ali created  
-  Youth leader Canada helps page created by this new group email :  fcf-youth-leader@foretcapitaleforest.ca 
- Youth Leader Ali [QR code poster](https://www.canva.com/design/DAF1Aov9Tn8/-DG7BuKl2XUAiNgalRWIdA/edit) to donate
