### ISSUE TITLE
Finish winterizing BoO

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#502]
- [x] Roll up hose that is laying alongside road
- [x] Final emptying of water totes
- [x] Lock for water pump
- [x] move all items away from sides of greenhouses (to make it easier to shovel snow from the walls)
- [x] Proper tidy storage of empty pots (away from 2 parking spots in front of Nanabush greenhouse)
- [x] Remaining potted trees in trenches or planted
- [x] Wood chips around Baker trees on hugel mound in Field 3
- [x] Check all food forest trees have tree guards (some still missing, some may not be applied properly)
- [x] Whippersnip around food forest trees that are overgrown to reduce mice pressure 
- [x] Fix fence around Tiny Forest demonstration plots
- [x] Add 2 lines of fence to seedling area (to discourage dog walkers entering from Pepin to enter that field)
- [x] plant forbs in Field 2
- [x] reorganize FCF shed, related #509

**Comment by smlambert** [comment]
- not sure but think we still have several hundred potted trees that are not trenched

**Comment by MartinNesbitt** [comment]
All the potted trees in the nursery have been moved to the seedling area apart from some that are still BR in the ditch and the paw paw. @smlambert I was wondering what you want to do with the paw paw? I know you mentioned planting them behind the shipping container. Also, should we place the BR in the seedling area or heal them behind the greenhouse?

**Comment by smlambert** [comment]
We can plant the paw paw by the other pawpaw at 2 locations, behind the shipping container along the cedars and at the Nanabush plot, with the hope some grow larger, we can consider relocating.

For the BR, we can heal in also in the seedling area.  I will be up at the farm tomorrow, so can help guide / do this work.

For the area behind the Nanabush greenhouse, I am finalizing the planting of that space.  
For the area behind the FCF greenhouse, I will be creating a staff garden.
