### ISSUE TITLE
Apply to Tree Canada Grant (Dec 2023)

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#505]
Look at the different Tree Canada grants on their website and begin an application. Ideally to add funding to Mer Bleue project if possible, since we are using different Tree Canada funding (ReLeaf) to fund Mer Bleue. Applications due in December.

**Comment by smlambert** [comment]
Rebecca mentioned that she is happy to answer any questions we have as we prepare a proposal.  Details at: https://treecanada.ca/grants-awards/community-tree-grants/

I've sent the info to @Matthewtennant for logging into the TC portal https://tree-canada.secure-platform.com/a with the fcf@foretcapitaleforest.ca account.
