### ISSUE TITLE
Create a list of upcoming projects that still require funding

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#506]
Will help with matching sponsors or grants to different projects.

**Comment by smlambert** [comment]
Adding short bullet points to trigger/stimulate memory:
- Mer Bleue - Larose Forest corridor project (large, multi-site, multi-year on both public/private lands, requires relationship building and soliciting land owners along the corridor)
- Agroforestry Demonstration project 
  - Soil Living lab "forest floor theatre" (including microscope & projector attachment)
  - Finish 4th Lawn Conversion guild (with arbor and simple path) - https://github.com/ForetCapitaleForest/actions/issues/472
  - Nut / oak tree lines with bulbous ends / healthy tree stands for future seed collection
- Walking Path development
  - 2 x Log bench seating at 3 to 4 stops along the walking path
    - Welcome sign / place for groups to gather/meet
    - Cedar Song stories stop / place for listening to indigenous stories shared via oral tradition (including funding for knowledge keepers honorarium) 
  - Soil living lab seating (outdoor classroom inside living willow fencing that opens towards the willow tunnel
- Tiny Forests
  - Pocket Forest necklace (a string of 4m x 4m tiny forests through the city to form a set of small gems) /  EC collaboration
  - Prepare 1st response materials for enquiries from individuals and groups who are new to the concept
  - Finish development of the Tiny Forest Board Game (with criteria cards)
- Capacity-building 
  - Citizen Forestry Service Program
    - Building a larger Tree seed collection team / sponsor 12 more collectors
    - Develop a solid program for forecasting and collecting native tree seeds
    - Develop a fun/gamified badging system for volunteer citizen forestry team members as they 'skill up'
  - Infrastructure for capacity-building
    - Air-pruning beds in seedling area
    - Large area of seedling area with temporary shade cloth (commercial size)
    - Work with Just Food and NCC to open gate on end of Pepin as the route in/out for tree pickup/dropoff
    - Large-scale Compost program (possibly in collaboration with Box of Life)
    - West-end seedling area / community tree hub

**Comment by jodinewman** [comment]
I have updated a previous [document](https://docs.google.com/spreadsheets/d/1B_R3ynTaIw2dzQOhTq6Br-yRkqRFDt0ah9dNI-O5u1s/edit?usp=sharing) to include these

**Comment by smlambert** [comment]
This one is marked as 'Done' in the project plan, but not closed.  I will close the issue, feel free to re-open if it is in fact not completed.
