### ISSUE TITLE
Send out attendance sheet to board members for Christmas market (to be done by week of Nov 13-17)

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#507]
Find attendance sheet from last year and edit to apply to this year's Christmas market. Send it out to board/team members to see who is available to assist.

**Comment by smlambert** [comment]
Holiday Market runs for 2 days on Dec 9 and 10th

![Saturday   SundayDec9and10HolidayMarket](https://github.com/ForetCapitaleForest/actions/assets/2836948/cbb272b5-5ec2-47d8-bd4b-94865ac715c0)

**Comment by jodinewman** [comment]
[Attendance sign up sheet](https://docs.google.com/spreadsheets/d/1p7HubY5-7b2pNoYhv6O39AHfXy_Wox6BFfzGX9FOnnw/edit?usp=drivesdk)
