### ISSUE TITLE
BoO: Organize and purchase new shed

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#509]
Some steps in preparation for installing a new shed:
- [x] Get preapproval from Moe / JF that we can put a larger shed in place of the other one - Shelley sent email on Nov 12
- [ ] Move small shed behind the FCF greenhouse
- [ ] Level a spot for a 10x12 or 10x16 shed in front of the water pump
- [ ] Price out pre-built Amish sheds (from Brockville and area Amish sheds amisheds@gmail.com) 
  - this 10x16 is 4200 not including hst + delivery
<img width="476" alt="Screenshot 2023-11-12 at 1 45 05 PM" src="https://github.com/ForetCapitaleForest/actions/assets/2836948/48343cb8-66f8-4f48-9e03-84c1b0667f29">

- [ ] Determine with supplier how late in the season they could deliver
- [ ] Await the news of our OCF submission as to whether that grant is approved and can cover the cost (estimated 10,000 in that submission, which needs to include cost of gravel base, and some hooks and shelving for inside).

**Comment by jodinewman** [comment]
I have submitted a request for quotes from a few different suppliers.

**Comment by smlambert** [comment]
- www.macsheds.com
- kodiaksheds.ca
