### ISSUE TITLE
Prepare for Local Flavours Holiday Market (fundraiser)

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#511]
For purchase with certain level of donation (need to finalize donation level):
- FCF branded Charcuterie boards with 3 x 125mL "forestGrown" jars from Nanabush + recipe suggestion card with cellophane & ribbon wrap
- Collectible card deck (cellophane & ribbon wrap) - need to determine how many we bring
- Single jar of forestGrown Nanabush product
- Single tree card 
- Possibly an FCF calendar
- forestGrown baking 
- Mulled apple cider

Open Questions:
- Where do the current donation card QR code link to?  Is it to another charitable organization's Canada Help page directly, or to fcf webpage or CanadaHelps page?  Does it mean we need to print new cards?
- Does everyone know how to use the Square appliance and can login in and have verified all is working as expected?
- Who has the tablecloths, will want them for the event?

Other things to prepare:
- Advertising the market through social media channels 
- Determine an estimate of target fundraising goal
- Finalize schedule for assistance at the market (related: https://github.com/ForetCapitaleForest/actions/issues/507)
- Bring some fundraising 'goods' to the Westboro AGM on Nov 23

**Comment by ShellCrabtree** [comment]
QR code link on the blue card here leads to the website: https://drive.google.com/drive/u/0/folders/1LX5VAn0CePCEn76DEhJK1oc5_ihRiG4m
@KaviGK Can we update that QR code to lead to: https://www.canadahelps.org/en/charities/foret-capitale-forest/ and have some printed for the market?
