### ISSUE TITLE
2BT Capacity Building submission (Due Nov 30, 2023)

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#513]
These are the focus areas and eligible activities are:

The focus of activities under any proposal for Capacity Building should primarily be related to:

- capacity building to encourage and facilitate involvement in planning and undertaking tree planting, including knowledge building and transfer, training and outreach;

- capacity building related to management, protection, and monitoring of trees and forests, including knowledge building and transfer, training, and outreach; and

- planting and management of trees and forests as part of capacity building.

 

This is also interesting to note:

The 2BT program will prioritize capacity building projects that includes a concrete plan for new work (rather than implementing existing activities) and demonstrates that the funded activities will directly support future 2BT planting activities.

For example, the 2BT program has previously funded capacity-building projects that:

- Included pilot tree planting projects led by organizations with relevant or related experience or partnerships that can test and refine strategies for a future project that could be funded under 2BT.

- Addressed local supply chain issues (e.g., seed collection).

- Addressed specific barriers to participating in future 2BT funded projects, or that made an existing plan actionable. For example: 
  - Engaging and/or recruiting professionals or specialists (e.g., Registered Professional Foresters (R.P.F.s), tree planters, project managers etc.,) to manage resources, or start/scale up operations.
  - Purchasing planting related equipment (e.g., specialized shovels, bags, etc.)

- Increased knowledge and participation in tree planting activities through targeted outreach and engagement efforts (e.g., training, creating jobs, and building community relationships), rather than general informational or awareness campaigns.

 
[1. FAQs - 2BT_Oct_2023.pdf](https://github.com/ForetCapitaleForest/actions/files/13355636/1.FAQs.-.2BT_Oct_2023.pdf)
[i. Capacity Building Applicant Guide.pdf](https://github.com/ForetCapitaleForest/actions/files/13355637/i.Capacity.Building.Applicant.Guide.pdf)

**Comment by StephMcNeely** [comment]
I have GCOS portal access and registered FCF for 2BT.  I downloaded the Working version of the application.  Saved here:  https://docs.google.com/document/d/1l6X5jl_YI7V_QXQ-lvtY6NQ4f7sxDqmy7Sh_YNP5EPU/edit?usp=sharing

Please use this version as it was created so that copy pasting into the portal later would be easier.

**Comment by smlambert** [comment]
Tagging @jodinewman @ShellCrabtree to assist with this submission (along with Elyse from EnviroCentre).  I will book time on Tuesday after our team call to meet with Elyse, but prior to that, we should familiarize ourselves with the grant.  Jodi and Stephanie have already looked at some stuff and shared them in the shared drive ([here](https://drive.google.com/drive/folders/1zHEWhPqLo6OzNMB1vgSHkxRtPGGAkVGq?usp=drive_link)).

**Comment by jodinewman** [comment]
Application submitted Nov 30 2023
