### ISSUE TITLE
Prepare CSJ submissions

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#514]
The annual Call for Applications for the Canada Summer Jobs (CSJ) program will be launched during the week of November 20th, 2023, and will end on January 10, 2024 at 11:59 p.m. (Pacific time).

For 2024, CSJ is maintaining its regular parameters and will offer quality jobs during the summer season with an aim to fund over 70,000 jobs for youth.

Not-for-profit employers can receive a wage subsidy up to 100% of the current provincial or territorial minimum hourly wage. Whereas public and private sector employers are eligible to receive a wage subsidy of up to 50% of the current provincial or territorial minimum hourly wage.

Are you ready to:

·         create quality work experiences for youth?
·         provide youth with opportunities to develop and improve their skills?
·         respond to national and local priorities to improve access to the labour market for youth who face unique barriers?

If yes, don’t wait until the last minute to apply! Each year over 60% of employers wait until the last week of the Call for Applications to submit their application. Don’t risk missing the deadline and apply early for the Canada Summer Jobs funding!

Already have an existing Grants and Contributions Online Services (GCOS) account? Then log in to your account to apply once the Call for Applications is open.

Visit: [Canada.ca/esdcgrantscontributions](http://www.canada.ca/esdcgrantscontributions)
Call: 1-800-367-5693 (7:00 a.m. to 8:00 p.m. ET, Monday to Friday)

**Comment by smlambert** [comment]
Adding Stephanie as one of the assignees (since she will likely be the one to push things to the portal with the GCOS key), and moving this to 2024 1Q plan.  Deadline is in 6 days.

**Comment by jodinewman** [comment]
@ShellCrabtree to prepare job descriptions

**Comment by smlambert** [comment]
Moving this to next iteration, and we should update the due date also (currently set to Jan 10).

**Comment by smlambert** [comment]
Oh, I see it is marked as Done, so I will close this issue.
