### ISSUE TITLE
Add a Funders/Supporters page with logos

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#515]
Add logos to Website once done: OSF, TD, FEF, Arbor Day, FOMB, etc.

EnviroCentre's page looks like this: https://www.envirocentre.ca/supporters-2/

**Comment by smlambert** [comment]
What is the entire list and where are the logos, and will this be updated on a yearly basis (as to who is supporting us in a current year)?

- JJ Foundation [logo](https://drive.google.com/drive/folders/1X7FwfcNR_gPqv8q6UT4tLcIlkqTpyZ1z?usp=drive_link)
-

**Comment by smlambert** [comment]
Page added here: https://foretcapitaleforest.ca/our-supporters/ - need to answer the questions raised in https://github.com/ForetCapitaleForest/actions/issues/515#issuecomment-1812636224 to complete the page.

**Comment by ShellCrabtree** [comment]
I will prepare a sheet with logos pulled from the drive.

**Comment by ShellCrabtree** [comment]
Should TD logo be this one? https://drive.google.com/drive/u/0/my-drive
Partners page for new edition of the site? 
Just Food, Women Warriors, Birch Path Healing Forest
TO request logos from:
[NCC](https://ncc-ccn.gc.ca/contact-our-media-team)
Tree Canada - https://treecanada.ca/about-us/contact-us/ (coms team request)
CAFES - https://cafesottawa.ca/?doing_wp_cron=1700825984.0688199996948242187500
Ferguson - https://www.fergusontreenursery.ca/about-us
Baker's Nursery Ltd. - https://bakersnursery.ca/index.php/about-us/
U of Guelph, U of Toronto
Ecology Ottawa
