### ISSUE TITLE
Write blogpost advertising Holiday Market

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#519]
A blogpost advertising the holiday market details and our fundraising plans, to be referenced in fall newsletter

**Comment by MartinNesbitt** [comment]
Draft Blog Post [Here](https://foretcapitaleforest.ca/wp-admin/post.php?post=2144&action=edit)

**Comment by MartinNesbitt** [comment]
Blog post published. This is the first blog/social media post of many leading up to the Holiday Market.
