### ISSUE TITLE
Broadfork around the 2 apple trees in the FCF plot

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#53]
One of the 2 apple trees looks particularly unhappy, we should loosen the soil around both as its like to be heavily compacted.  We may also want to dig in some compost at the drip line of the tree to allow the roots to have a place to go.

**Comment by smlambert** [comment]
Simona completed this today (May 30th).

**Comment by Pepe-Fifi** [comment]
HI Shelley, I think you were so right about the soil being to compacted (wet clay) for the two apple trees to survive. I had a good workout with the broad fork today (glad that the ground was not dry)  and I wish for the trees to be happier/healthier from now on :-).
