### ISSUE TITLE
MB: Complete site assessment and species selection

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#530]
Develop a complete species list and a breakdown of quantities

**Comment by MartinNesbitt** [comment]
The species selection for the site include trees from the [Treemendous communities grant budget](https://docs.google.com/spreadsheets/d/1CzJD70Q0Dar-nYAEiUdy3y-H9_-qNuAH/edit#gid=109441434) and species selected from the [Ferguson order](https://drive.google.com/file/d/1EBr_YPI-XA7KrHXryok8TffFO3ZoqZ_F/view) and [Treetime order](https://drive.google.com/file/d/19RiHZTt5fNFq-vv7-VL2qW1Fb_OH1yDk/view)

**Comment by jodinewman** [comment]
Site visit to be completed by Shelley and Matthew Dec 21st with Cedric. 
Species list in progress in progress in 2024 planning tab of the [Working Tree Inventory.](https://docs.google.com/spreadsheets/d/1tx_jPAqOD2Geuu5yYULp5n7PkLuhiSvkP2jeauWURQE/edit?usp=sharing)

**Comment by smlambert** [comment]
<img width="868" alt="Screenshot 2023-12-20 at 4 20 07 PM" src="https://github.com/ForetCapitaleForest/actions/assets/2836948/c39a8894-c6f8-4ba1-905c-b4f8d5f11303">

**Comment by jodinewman** [comment]
[Matthew's notes](https://docs.google.com/document/d/1SvKJ3TPzgplXGhr2RBOMCnlorf8zrfB_JqJ3nL9rqkE/edit?usp=sharing) from December 21 site visit.

**Comment by Matthewtennant** [comment]
species selection complete, list sent to NCC for approval.

**Comment by jodinewman** [comment]
Species list approved with minor adjustments
