### ISSUE TITLE
MB: Develop watering solution

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#531]
Develop a formal strategy for watering in relative remote areas | December 2023 | March

**Comment by MartinNesbitt** [comment]
- placement of water tote to occur in early spring before first plantings
- role of FCF staff/FCF core team volunteers to fill water totes when needed with pumps that transfer water from creek to water tote.
- watering instructions placed on the tote. volunteers, stewards have the role of watering the trees when needed. It is anticipated that watering won't be needed until summer (July-August) as the site is in a flood plain and is very wet in the spring and fall.
- role of volunteer stewards to notify FCF staff that water tote needs filling
-

**Comment by jodinewman** [comment]
NCC has advised that a water tote is not suitable for this site. We will need to determine a different watering solution (using electric pump).

**Comment by Matthewtennant** [comment]
Will be purchasing a battery-powered pump to fill tote on site, watering will be done by pre-approved group selected for project.
