### ISSUE TITLE
MB: Community group outreach

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#532]
Develop a list of groups and volunteers to participate in planting events | December 2023 | November

Begin discussions with groups

**Comment by MartinNesbitt** [comment]
[A list of potential groups to participate in planting and stewardship](https://docs.google.com/spreadsheets/d/1-yaDe_aqaDlps6XUGUxGuVPkn6SVuEaNB0gcaM0s0UU/edit?usp=sharing)

**Comment by jodinewman** [comment]
Next steps: begin discussions with groups on the list.

**Comment by KaviGK** [comment]
**List of potential groups to follow up** 

- Prasanna Siva ( [prasannasiva@icloud.com](mailto:prasannasiva@icloud.com) ) = FCF volunteer who can help recruit 20-30 active volunteers from his [faith community](https://sathyasai.ca/trees-of-love/)  
- Reconnect with Uottawa outdoors club ( Maya Tuchenhagen [mayatuchenhagen@gmail.com](mailto:mayatuchenhagen@gmail.com) ) ( https://www.outdehors.com/) 

**New groups to reach out to** 
- Carleton Outdoors club ( [outdoors.carleton@gmail.com](mailto:outdoors.carleton@gmail.com)) https://carletonoutdoorsclub.com/#comeplay
- Ottawa Field-Naturalists’ Club ( [ofnc@ofnc.ca](mailto:ofnc@ofnc.ca)) https://ofnc.ca/contact-us
- Ottawa Outdoor Club ( president@ ottawaoutdoorclub.ca) https://www.ottawaoutdoorclub.ca/  https://www.facebook.com/groups/ottawaoutdoorclub 


**_Online communities to promote recruitment ( Private message and ask permission from admins first)_** 
- Friends of the Fletcher Wildlife Garden https://www.facebook.com/groups/48901132335/ 
- Master Gardeners of Ottawa https://www.facebook.com/groups/819730788084134/ 
- Ottawa Wildflower Seed Library https://www.facebook.com/groups/393209995421040/ 
Mélanie Ouellette = is founder and chairperson , she knows about FCF and has helped promote our Rockland fair event
