### ISSUE TITLE
MB: Community group coordination

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#533]
Ongoing coordination with community groups to prepare for planting opportunities | December 2023 | November 2024

**Comment by jodinewman** [comment]
Coordinate planting opportunities with the groups determined in #532

**Comment by jodinewman** [comment]
Leann & I have began outreach. List of groups we are targeting available [here](https://docs.google.com/spreadsheets/d/1dHxRFn-PtZ_3AJ3C9-ofVuVtJ-gTZCLKpDL5AWY5NsI/edit?usp=drivesdk).
