### ISSUE TITLE
MB: Begin administering the watering plan/strategy at each site once planting is finished.

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#538]
An established water source for each site, along with documentation in place to record maintenance activities by community members. | April | November

**Comment by StephMcNeely** [comment]
Sorry for any confusion… we can definitely plan for a water tote here,
especially if hoses don’t reach or it takes awhile to pump water

By the way, we need to figure out who the conservation authority is in this
area and potentially have a meeting with them to discuss the water
approach. Suggest some light research on “permit to take water” regulations
so you are informed before engaging on this topic..

Research deadline : late Jan
Meeting with SNCA : mid Feb

**Comment by jodinewman** [comment]
The conservation authority is South Nation, but unless there have been changes to the regulation in the last year, I believe you only need to apply for a PTTW if you are taking > 50,000 L of water in a day, which I can't imagine we would be doing.

Either way, we should still look into any specific rules SNCA may have
