### ISSUE TITLE
Prepare for March 3rd, 2024 Rockland Sustainability garden tradeshow

### ISSUE THREAD

**Issue by KaviGK** [ForetCapitaleForest/actions#546]
FCF to host a event table & possibly present a seminar topic 
- [x] Follow up with Stephanie Marcil ( stephanie.marcil@gmail.com) ( rocklandgarden22@gmail.com)  to confirm  event details
- [x] Follow up  with Arianne Cantin  ( arianne.pepin@gmail.com) about seminar presentation - settle on a topic : our afforestation projects and or tiny forest focus

**Comment by ShellCrabtree** [comment]
CONTENT NEEDED TO SEND IN ACCORDING TO EMAIL: 

What do you need to do now? 

- To ensure we adequately plan and prepare the venue space, all participants must fill out this [Participant Registration Form](https://docs.google.com/forms/d/1yHOfpqhaXA-mjuB93b1LD7HjOtSPVcJ_uQLvEQArxDQ/edit) no later than January 15, 2024.
- Ensure you read the [Participant Agreement](https://drive.google.com/file/d/1WxX5RUorm9SH3lqIRpWySVlrdj2Q8bQZ/view?usp=drive_link). 
- If you're a vendor, e-transfer your $40 registration fee to [rocklandgarden22@gmail.com](mailto:rocklandgarden22@gmail.com) no later than January 31, 2024. Ensure your business name and our event title, “Growing Green”, are indicated in the e-transfer.

Email me a **web-ready logo** (full file required for quality; must be a square) as soon as possible. If you are leading a seminar or workshop and would like your photo posted, please provide that as well. 

Consult our[ media kit](https://drive.google.com/drive/folders/1tmadKT3NPzjvSeSKfxmAFpGEjXVx4zpq?usp=drive_link) and use our social media templates to help you advertise the event **(starting Jan 7th).**
Check out the [event page on our website](https://www.rocklandcommunitygarden.ca/growinggreen) (it will evolve as we add participants and receive your info)!

What's next? 
We will begin advertising the event via **social media on January 7th,** so please get your logos and/or bios and photos in asap and be active on social media along with us!
I will provide additional details about space allocations closer to the date and anything else that may arise between now and then.

**Comment by KaviGK** [comment]
Completed tasks 
- [ ] Participant Registration ( completed & followed up with Stephanie Marcil ) 
- [ ] Read Participant Agreement & ID any questions 
- [ ] $40 registration fee ( submitted by Shelley Lambert on January 5th) 
- [ ] Email FCF logo, Shelley bio & picture 
- [ ] Send Seminar title and description ( Listening to a Forest to Improve Community Health) 

January tasks

- [ ] Create a Social Media post advertising event & Seminar registration ( Consult Media Kit) 
- [ ] Advertise event to our volunteers group & ID two-three volunteers who can help with Event day
- [ ] Update Donation cards 
- [ ] Reconnect with the teacher at the Rockland High School 
- [ ] Follow up with Rockland Media TV oppuntunity? 
- [ ]  Create materials we can present at table ( brochures,  infographic on our Ottawa East corridor plans) 
 
February tasks
- [ ]  Send Donation cards to print  
- [ ] Print & laminate other event day materials 
- [ ] Seminar presentation assistance 
- [ ] Early Feb Social Media post & volunteer email follow up 
- [ ] Follow up & confirm Volunteers who can help on event day 
- [ ] February Follow up with Stephanie Marcil ( confirm event day logistics) 
- [ ] Last reminder Social Media post & volunteer email ( February 26th post) 


EVENT DAY  PREP CHECK LIST 
- [ ] table & chairs ( 6x6 space) 
- [ ] donation cards 
- [ ] QR codes page ( volunteer, social media )  
- [ ] Seminar presentation

**Comment by smlambert** [comment]
Thanks for the checklist @KaviGK - I can bring all 4 items in my list, plus I will bring a spare projector and cables (just in case of the Rockland one not working out, as was the case when I went to the Westboro AGM).
