### ISSUE TITLE
add a separate form to website for corporate groups to fill out

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#549]

**Comment by MartinNesbitt** [comment]
A [draft](https://docs.google.com/document/d/1IDJ0JxgJXpJ3s4zFV0-nIBQBy4eW7ulZV6d0ENE9wmE/edit?usp=sharing) of an updated volunteer form is ready for review. 

Questions:
Where is the location of the form in Hubspot to allow edits?
Where is the location of the form submissions in Hubspot to allow analysis?

**Comment by MartinNesbitt** [comment]
[Location ](https://docs.google.com/spreadsheets/d/1OeyXDKzfxkQoCo2TeyjT1_LSJBAZfK2z/edit#gid=1087867940)of volunteer form survey
- submissions are manually inputted in the google sheet from Hubspot
- submissions are manually added to the volunteer google group, and site-specific google group from hubspot submission.
-

**Comment by MartinNesbitt** [comment]
The [form](https://foretcapitaleforest.ca/volunteer-2/) has been updated on the website.
