### ISSUE TITLE
Coordinate a modest crowdsourced fundraiser to help fund part of the tiny forest demo plots

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#55]
As discussed in May 26th meeting, we think it would be good to do a little campaign to ask for donations for people to 'buy a square', essentially fund the planting of 1 square metre of a tiny forest at the Just Food Community Farm.

As per the planting density that we will be doing, this means they will be helping to fund 1 tree seedling, 1 shrub and 1 forb (perennial plant) which will be planted into 1 square metre.  To keep things simple, 1 square = $20 donation.  They are welcome to buy as many squares as they like, we will try to 'sell' 500 squares (of the 3000 squares in total, some of the remainder are already covered by other funding).  People will be welcome to also come and plant the items that they have helped to sponsor, or have our team of volunteers plant it for them.

This work is dependent on first updating the donations page on the website #14 

We can do a Facebook/Instagram call out for this campaign, as well as a blog post on the website.

**Comment by InnesBuck** [comment]
This is the fundraising page on [Canada Helps](https://www.canadahelps.org/en/pages/tiny-forest-demonstration/)
- Making a few blog/social media posts regarding the fundraising campaign
  - post at different times of day and different days 
  - add fun facts about Tiny Forests, covering their many benefits and previous projects
 - Post in Newsletters
 - Plan for a mulching event to promote the fundraiser and to get the community engaged with the project
