### ISSUE TITLE
add an FAQ page to the website

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#550]
[FAQ Draft](https://docs.google.com/document/d/1k3zP24Mrss5iQ7yCslNrUp53-Z6Xp3TSL7UO_twfugI/edit?usp=sharing)

**Comment by MartinNesbitt** [comment]
Initial Draft of the FAQ page is ready for review @KaviGK @ShellCrabtree @smlambert [FAQ Draft](https://docs.google.com/document/d/1k3zP24Mrss5iQ7yCslNrUp53-Z6Xp3TSL7UO_twfugI/edit?usp=sharing) . This is a general FAQ page that has questions under 3 headings: General Questions, Afforestation Questions, and Tiny Forest Questions. Please provide feedback on the questions (adjust or add any that you feel we've missed) and answers.

Note: The questions related to Tiny Forest are rather basic I will plan to direct readers to our more detailed Tiny Forest page.

**Comment by MartinNesbitt** [comment]
Edits made following feedback. FAQ is planned to be published to the updated website. Adjusting iteration and deadline accordingly.

**Comment by MartinNesbitt** [comment]
Survival Rate context questions added to the FAQ

**Comment by MartinNesbitt** [comment]
Draft complete. Only thing that remains is creating the accordion in WP.

**Comment by MartinNesbitt** [comment]
FAQ page published on wordpress https://foretcapitaleforest.ca/frequently-asked-questions/
