### ISSUE TITLE
designate roles for next years operations

### ISSUE THREAD

**Issue by Matthewtennant** [ForetCapitaleForest/actions#551]
separate year's duties into roles to specialize staff for next year

**Comment by jodinewman** [comment]
[List](https://docs.google.com/document/d/1HVyN76jrpMKcXcZfSJWhCX0rkM90W_--oDFNE_Eqigo/edit?usp=drivesdk) of roles

**Comment by smlambert** [comment]
@kevin-fcf - see the link to the roles document in the comment above
