### ISSUE TITLE
Explore Catherine Donnelly Foundation Grant

### ISSUE THREAD

**Issue by Matthewtennant** [ForetCapitaleForest/actions#553]
### Deadline for letter of inquiry is Feb. 1, 2024. 
- Foundation wants to support educational and environmental projects that focus on equity.
- Application guideline document available in Grant Drive: https://drive.google.com/drive/u/3/folders/1k_sDCUZ6nRxSaCGX9_O5wEa5YxYNKSpE

### Possible ideas: 
- living soil lab
- future OCH Tiny Forests
- Alternative High School event

**Comment by smlambert** [comment]
Moved to 2024 1Q plan and added due date, but if I recall some investigation on this grant has occurred and possibly the result of that investigation may mean we do not pursue this funding source?   Need to confirm that recollection.

**Comment by jodinewman** [comment]
It was decided that we wouldn't have time to apply to it for the Agroforestry project ([Dec 19 meeting](https://github.com/ForetCapitaleForest/actions/discussions/568)). But I don't think we have another project  at the moment that would fit in the timeline. If I am correct, we can close this issue for now.
