### ISSUE TITLE
submit TD FEF grant

### ISSUE THREAD

**Issue by Matthewtennant** [ForetCapitaleForest/actions#555]
will be used for Aviation Pkwy phase 3
Deadline for submission January 15, 2024
https://www.td.com/ca/en/about-td/ready-commitment/funding/fef-grant

**Comment by Matthewtennant** [comment]
project budget completed, working on write-up now.
working drive found here:
https://drive.google.com/drive/folders/1e2Mq1Tom88-xScbZS4nT-owOERK8OaNo?usp=drive_link

**Comment by Matthewtennant** [comment]
write up and budget completed, sent to directors for internal approval as of Dec. 22, 2023

**Comment by smlambert** [comment]
Moved this to the 2024 1Q plan and added the Jan 15 due date.

**Comment by Matthewtennant** [comment]
grant bid officially submitted!
