### ISSUE TITLE
Prepare for upcoming meeting with NCC

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#559]
- [Sample meeting agenda](https://docs.google.com/document/d/12G6wR1IVABnXjiSNSikaTwWl7utT7_yGvmbrbiSaDuc/edit?usp=drivesdk)
- [Sample meeting minutes](https://docs.google.com/document/d/10x6AQS630IbodzQ6VQgm1Pzrjk4zZk50DIxIclYBG_8/edit?usp=drivesdk) 
- [Draft list of questions](https://docs.google.com/document/d/1x6qC0PE3qr9sxyfqaAlMEg9UdYuRonErPoDuuXUkLQQ/edit?usp=drivesdk)

**Comment by ShellCrabtree** [comment]
Meeting minutes and action follow up included in the [minutes](https://docs.google.com/document/d/1SW7S_7a9ZnjzQ7AkJo5xlitxQw-Q-_Po/edit).
