### ISSUE TITLE
Plant row of raspberries at FCF base of operations

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#56]
We have 25-35 raspberry canes that can be planted in the trench where last year's Hog's Back trees were temporarily living.  I have mowed the clover alongside the trench to make it easier to see where it is.  

The raspberries are currently heeled in behind the small greenhouse.

**Comment by Pepe-Fifi** [comment]
Hi Shelley, I will try to do this task on Thursday, after helping the preparation for the Saturday planting ( if Thursday is not too late).

**Comment by smlambert** [comment]
Thursday's is not too late.  There is a pot of 25 raspberry canes that I have placed by the greenhouse door so it could be more easily found.  It has a tag on it that says "25 Polana".  We will start with those, spaced a foot apart.

**Comment by MartinNesbitt** [comment]
The raspberry plants have been planted today (05/31/22)
