### ISSUE TITLE
Explore funding opportunities for Tiny Forests 2024

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#561]
- [ ] Trees For Life: Shelley L met with them before, they previously funded Little Forests Kingston (see https://www.treesforlife.ca/projects-and-partners)
- [x] TD Ready Commitment Vibrant Planet Grant: recommended to us by 2 TD representatives

**Comment by jodinewman** [comment]
JRJJF is funding 3-4 Tiny Forests in partnership with EnviroCentre. These funding opportunities could be used for other projects or 2025 projects.

**Comment by ShellCrabtree** [comment]
Online application [form](https://www.treesforlife.ca/request-project-support) - projects/land to be identified.

**Comment by Matthewtennant** [comment]
funding secured for all 2024 tiny forests. online application form for trees for life saved in potential collaborators doc for future use.
