### ISSUE TITLE
Create fundraising social media posts advertisng tree cards and benevity

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#567]
Prepare some social media posts and images for this week:

1.  inviting folks to donate to FCF and providing the option of using our cards. Shelley C id waiting to hear if we can use Marianne's story as a testimonial. See group message for possible photo to use.
2. Also a post to say we are signed up with Benevity where their donations can be matched by employers.

**Comment by smlambert** [comment]
may want to take a look at what are the e-cards that CanadaHelps offers

**Comment by MartinNesbitt** [comment]
social media posts for tree cards and benevity have been scheduled in Meta Business Suite up until Christmas.
