### ISSUE TITLE
Aviation 365 Report 

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#570]
Complete Aviation Parkway 365 Report 365 to be reviewed by Stephanie before submission to NCC.

365 Report to be completed and sent in and invoice – include trees planted on an Excel for carbon capture calculation purposes by NCC.

[Aviation 365 Report ](https://docs.google.com/document/d/1_oHnscKqrnu4ODOZkMQGGq6aEzyi0W1UG7pTGMFYPZ4/edit).

**Comment by StephMcNeely** [comment]
Report reviewed.  Good job, looking very professional!  A number of comments to address that should be followed for all subsequent 365 reports. Table references, use of metric, etc. Do we have any good photos to append (4 to 5 suggested)? The burdock issue alone warrants a visual ;)

**Comment by KaviGK** [comment]
Here are some [photos ](https://drive.google.com/drive/folders/10EbUKfu8LzTcdr8vr0FmSfx2Bbd4mW9y?usp=drive_link)that can be attached to the report. These photos were taken in June & July prior to any biweekly weeding events.

**Comment by StephMcNeely** [comment]
Are the report revisions complete and ready for one final read-through?  Note that a photo appendix should have a description of what each photo is (e.g. weeds in August, look west from xx location).  I would add more that show actual trees looking good (e.g. post-weeding).

**Comment by MartinNesbitt** [comment]
The report isn't ready for one final read-through. I will create an appendix for the photos with a description. I will let you know when it's ready! Thanks!

**Comment by MartinNesbitt** [comment]
The report is ready for a final read-through @StephMcNeely.
