### ISSUE TITLE
Close out bid for Rapides Deschenes and 2 other NCC Sites

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#572]
NCC has funds to plant in the area. 
ACTION: FCF has questions, but we can resend an estimate to NCC. DUE – BEFORE January 20th 2024
Site is challenging, must bring in soil; can be done says Cedric but good for staff plantings; have some volunteers also that are well trained. 

[Folder with project information and draft bid](https://drive.google.com/drive/folders/1NCuRQgiGvDOEQ3wcciQFVaBayk_Hkbwr?usp=drive_link)

- [ ] ACTION: FCF has questions, but we can resend an estimate to NCC. DUE – BEFORE January 20th 2024

**Comment by Matthewtennant** [comment]
updated tree costs, staff costs for bid, need to visit site to get accurate estimate of soil needed. will email cedric to set up visit

**Comment by jodinewman** [comment]
Requested meeting with NCC to discuss bid.

**Comment by Matthewtennant** [comment]
NCC happy with bid, have adjusted tree selection to meet their internal budget. Now looking into water sensor material on their request.
