### ISSUE TITLE
MB: Request for permit/support letter needed from NCC for FCF funding application 

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#573]
A permit or written permission is needed from the NCC to confirm funding for TC Operation ReLeaf and the Treemendous Communities grant for MB.

**Comment by ShellCrabtree** [comment]
[DRAFT ](https://docs.google.com/document/d/1PFgvc-Tji0Nawt1BNE3JCAGF5QWeNov9aaKzJFiKVqs/edit)prepared

**Comment by MartinNesbitt** [comment]
@ShellCrabtree the draft looks great, thank you! We could send this to the NCC along with the questions regarding Rapides Deschenes coordinates/specific site conditions, and confirming species for the confirmed and tentative 2024 plantings.

**Comment by ShellCrabtree** [comment]
Request for signed LoS sent. Frederique off until Jan. 8th

**Comment by ShellCrabtree** [comment]
@MartinNesbitt @Matthewtennant[ LoS ]([url](https://drive.google.com/drive/u/0/my-drive))received.

**Comment by Matthewtennant** [comment]
support letter sent to TC, they have indicated that it has been added to our application
