### ISSUE TITLE
Green Municipal Fund 2024

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#576]
Start looking at what is required for GMF 
https://greenmunicipalfund.ca/growing-canadas-community-canopies

Shared drive created [here](https://drive.google.com/drive/folders/1OyZqDB8k0f04o4kaAk8VFf3jz2JVJaqo?usp=drive_link)

**Comment by smlambert** [comment]
Shared that folder with Moe and Kate from Just Food / Community Gardening Network, as we have briefly discussed potential collaboration for this fund (they already have a relationship with the city and they have a national entity that can be incorporated into such a bid).

**Comment by smlambert** [comment]
Creating the feedback doc to share with FCM and setting the timeline to finish it by Jan 21

**Comment by jodinewman** [comment]
FCF edits are complete, Moe will add her edits. Call to be arranged by Moe with FCN.

**Comment by jodinewman** [comment]
Meeting with FCN completed, individuals providing comments on proposal. Moe will be meeting with Tree Canada on Mar 9.
