### ISSUE TITLE
Outline the Training Programs described in our 2BT Capacity Building grant submission

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#580]
We described different categories of training and badging that is buried in a grant submission.  We should surface it and clearly start describing it, as it can form the basis for an FCM bid, the Swords to Plowshares program (with Women Warriors Healing Garden) where we will offer some urban forestry training). 

Describing it should include categories of training, levels of badging (what skills we need, what workshops/training we offer), what outcomes/work output we expect from people with certain badges.

**Comment by jodinewman** [comment]
[Working Document](https://docs.google.com/document/d/1pBePyUITPCwqEk9TivVAtUmKaRG1Rk49qplndrTQKco/edit?usp=drivesdk)
