### ISSUE TITLE
Effectively communicate FCF leadership in Tiny Forest work in Ottawa

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#582]
### 1. Create a list of Tiny Forests
Properly list and articulate our participation in existing Tiny Forests in Ottawa (chronological order)
- we have been involved in 9 Tiny Forests in Ottawa, we know of no others in Ottawa that were created following the complete Miyawaki method (others skipped soil investigation and soil preparation steps)
- data to include, who was responsible for each of the 6 steps of the Miyawaki method who funded it, who prepped the site, who planned the planting, who planted it, who is maintaining the site, what research is happening at the site, size of site, number of plants at site, when planted, any other additional notes of interest

1. **FCF BoO Tiny Forest Demonstration Plot 1** (Field 4)
2. **FCF BoO Tiny Forest Demonstration Plot 2** (Field 4)
  - 2 tennis court-sized Tiny Forests at the Base of Operations in 2022 as "Demonstration Plots" prepped to 3 ft depth
  - Funded by Tree Canada Treemendous Communities grant + CPGEP + donated trees
  - planted over the course of several months by FCF staff and FCF volunteers
  - late on mulching (as free mulch was in short supply)

3. **FCF BoO Tiny Forest Demonstration Plot 3** (Field 4)
4. **FCF BoO Tiny Forest Demonstration Plot 4** (Field 4)
  - 2 tennis court-sized Tiny Forests at the Base of Operations in 2022 as "Demonstration Plots" prepped to 1 ft depth
  - Funded by Tree Canada Treemendous Communities grant + CPGEP + donated trees
  - planted over the course of several months by FCF staff and FCF volunteers
  - late on mulching (as free mulch was in short supply)

5. **OCH Tiny Forest at Riverdale**

6. **OCH Tiny Forest at Cutts-Patola**

7. **OCH Tiny Forest at Esson**

8. **Tiny Forest at York Street Public School**

9. **Tiniest Tiny Forest at FCF BoO** (Field 2)

Could potentially mention other tiny forest candidates in the city and whether or not they followed all the "Miyawaki method".  This differentiation is important when it comes to overall performance of sites (do sites that do not follow the proper soil prep perform as well as sites that do less prep or no prep).

### 2. Publish/broadcast videos and presentations on the website and YouTube channel
- related is the work Gillian is doing
- rebroadcast TV coverage
- record the edited "Listening to a Forest" talk and push it to the Youtube channel

### 3. Take advantage of new opportunities to speak and share on the topic
- Rockland Sustainability Fair event
- Ottawa Public Library talk (connect with Sarah L. / librarian)
- Consider creating a "tourist" event at the BoO that includes a tour of the Tiny Forest (perhaps incorporate collectible cards & game)
- Potentially a webinar

**Comment by smlambert** [comment]
From the data perspective, the listing should include:

- address
- geolocation coordinates
- species list
- size of site
- density of planting 
- dates of planting
- research happening at the site
- compliance to Miyawaki method (perhaps a % based on what steps were followed)
- notes (such as delay on mulch)

- people: funder(s)
- people: soil investigators
- people: soil preppers
- people: planting planners
- people: planters involved in each planting date
- people: maintainers/stewards 
- people: researchers 
- events: organized community event(s) related to the site (including but not limited to the planting event)

**Comment by smlambert** [comment]
**FCF BoO Tiny Forest Demonstration Plot 1 (Field 4)**
- 2391 Pepin Court (Just Food Community Farm, FCF Base of Operation)
- geojson:
- land [public]
- species list  [[list](https://docs.google.com/spreadsheets/d/1kwoH17cD_euiUZ1HqfAaGwicZnZ5iA2BwaDzIAE3pw4/edit?usp=sharing)]
- size [xx sq metres] 
- density [ 3 / sq m ]
- planting dates [spring-fall 2022]
- research [UofGuelph biodiversity study / above ground (spring 2023 start) & soil (fall 2022 start)]
- compliance [6/6, 100%]
- notes [ due delay on mulching increased weed pressure ]
- estimated cost per square metre [ x ] 
- people: landowners [NCC owner, Just Food leaseholder]
- people: funders [partial Treemendous Communities / Reactine, check small amount for path work under CEPGP, Nanabush in-kind]
- people: soil investigators
- people: soil preppers [ FCF & #2 ]
- people: planting planners [FCF]
- people: planters involved in each planting date [FCF staff & volunteers, check also TC events, Rockland High, UofT forestry students]
- people: maintainers/stewards [FCF staff & volunteers]
- people: researchers [UofGuelph [Centre for Biodiversity Genomics](https://biodiversitygenomics.net/), Dirk Steinke, Kathryn Austin, Julia Workman]
- events: organized community event(s) related to the site (including but not limited to the planting event)

**Comment by jodinewman** [comment]
Related to creating a Miyawai How-to (#170 and #466), which I will get started on soon!

**Comment by ShellCrabtree** [comment]
[DRAFT Tiny Forests Communications Plan](https://docs.google.com/document/d/1HLygAIuID6-Bp4t54nSN9tz0InRwPl0E/edit?usp=sharing&ouid=115341068546283062901&rtpof=true&sd=true) now available for comment/input.

**Comment by MartinNesbitt** [comment]
Draft completed in document linked above. Only materials that remain are the Tiny Forest How-to Guide that can be included after the page has been published, and the Tiny Forest videos.

Only task that remains is creating the page and accordion in WP.

**Comment by ShellCrabtree** [comment]
[Tiny Forest Videos completed ](https://drive.google.com/drive/u/0/folders/140T6vouaIbbXZ1li5A1BfKRFtTEJ8tuP)to be added to Website page (embedded) and YouTube channel @MartinNesbitt

**Comment by MartinNesbitt** [comment]
Wordpress post published https://foretcapitaleforest.ca/fcf-leadership-in-tiny-forests/
