### ISSUE TITLE
Legion Grant in partnership with WWHG

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#583]
Meeting today to discuss opportunities for collaboration between WWHG and FCF and make a plan to submit for a Legion grant that may help to cover salary to hire 1 CAF veteran.  This grant is time-sensitive.

We would intend to reuse urban forestry training components that we included in the 2BT capacity building grant.

**Comment by jodinewman** [comment]
[Meeting Notes](https://docs.google.com/document/d/17J1uWNnR2o2nARN_86NUk5xHwRgBBk4sBnDiaIw1fUs/edit?usp=drive_link)

[Link to Drive](https://drive.google.com/drive/folders/1X36v-JQnOzBpHewWJz8EhOWDCdSD2VF9?usp=drive_link)

**Comment by smlambert** [comment]
After speaking with the LNF grant folks directly, this one is not well-suited to us, so will close as not in plan.
