### ISSUE TITLE
Tree Canada Meeting Prep - Jan 25

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#594]
1. Prepare notes on Tree Canada relationship and current roles, responsibilities
2. Prepare agenda for meeting happening on Jan 25 - Due Jan 23

**Comment by MartinNesbitt** [comment]
@ShellCrabtree Preliminary [meeting agenda](https://docs.google.com/document/d/1kYj2RI603RnlYdEAFUTTic_hkiu_LIPqKIDFFBFexA0/edit?usp=sharing) is ready for more input.

**Comment by MartinNesbitt** [comment]
Notes on TC relationship, roles and responsibilities:

- [Forestry Specialist meeting notes](https://docs.google.com/document/d/19FuA6KjVGJvMRYQlmQ4lMJtOb78bwbP0V3_FmwQFjEE/edit?usp=drive_link)
- FCF current boundaries for FS is the National capital region. Perhaps increase the boundary to Eastern Ontario to allow for more projects?
- Typical process for PIPs and CTGs: TC comes to us with a potential project (project description, project funder, and budget (if applicable)) a few months ahead expected project date. Depending on the project, we then begin to look for land and connect with the project sponsor to coordinate the event details.
- From the 2023 FS meetings, TC is looking to share a renewed 2-year forestry specialist contract in 2024 Q1 with details on First Aid/CPR Training, Incident Reporting, and TC event procedure.
- 2 different kinds of projects: 1. PIPs - we are given a project budget (typical range $3-$4.5k for tree stock and other planting materials) ($1500 FS fee for our labour) to organize a tree planting event (we must find land and source trees); 2. CTGs - we are helping community tree grant recipients carry out their tree planting projects. As FS, we are consultants that help the recipients with forestry-related questions (Species selection, tree sourcing, tree planting technique, best management practices). We are required to attend a planting event to ensure the tree planting runs smoothly and trees are planted properly. we are paid a $500/project.
- For TC projects, we receive our funds by submitting an invoice after the project/event is over. A project report is required for PIPs, grant recipients fill out the project reports for CTGs.
-

**Comment by ShellCrabtree** [comment]
[January 25 meeting with TC's Caitlin Dixon notes](https://docs.google.com/document/d/1kYj2RI603RnlYdEAFUTTic_hkiu_LIPqKIDFFBFexA0/edit
)
