### ISSUE TITLE
Draw grid lines in gypsum onto the 4 miyawaki plots

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#60]
To guide volunteers we should draw a grid (1 square metre sized) onto the plots using a soil amendment called gypsum (calcium/chalk), so that it is easy to direct people where to plant and has the added bonus of adding calcium to the soil.

**Comment by smlambert** [comment]
We may need the first of 4 plots marked off as early as June 10th, if that planting date gets confirmed.  Awaiting news from Mike Petryk if that date is viable with Reactine folks.

**Comment by smlambert** [comment]
<img width="791" alt="Screen Shot 2022-06-06 at 8 41 12 PM" src="https://user-images.githubusercontent.com/2836948/172272054-0d339624-8e22-41a5-92db-6cdcdd9b7f8b.png">

A connected path will run through each of the 4 tiny forests, with a small space embedded for people to pause in the middle of the tiny forest (perhaps with simple seating, made from tree stumps).

<img width="525" alt="ShowingOneWithPath" src="https://user-images.githubusercontent.com/2836948/172272678-f2425615-9c5a-4c29-94d9-64a2a37fd5ce.png">

<img width="525" alt="Screen Shot 2022-06-06 at 8 54 02 PM" src="https://user-images.githubusercontent.com/2836948/172273102-ef8248fa-d186-4b34-8f11-0ed07813b63d.png">

This will slightly reduce the number of trees/shrubs/forbs needed for the planting (which is good, as we do not have full funding for the entire planting and will be using donated plants for part of it.

**Comment by MartinNesbitt** [comment]
Ok thanks for the clarification. I can meet you there this afternoon to help out.

**Comment by smlambert** [comment]
https://www.google.com/maps/d/u/0/edit?mid=1NgheyNipqBFj0i9g5d_4BTARN4ZYADII&usp=sharing - for a rough map of the proposed walking path...

**Comment by MartinNesbitt** [comment]
The grid of the first plot (closest to the road) was completed. The gypsum purchased was grey-coloured, so it wasn't very visible. Therefore, mulch was used to draw the grid. Better to evenly disperse the gypsum across whole area instead of just grids.

The walking path from plot 1 to plot 2 and the small sitting space for plot 1 and 2 were lightly mulched. 

The walking path and siting remove ~12-15 sqm. from area.

**Comment by smlambert** [comment]
Using wood chips instead of gypsum, will close this issue as well understood, with a working solution and with 1 plot remaining to complete.
