### ISSUE TITLE
OCF Grant - Spring 2024

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#610]
Working [directory](https://drive.google.com/drive/folders/1IKJoHlLWPZfcrJ3kx45UzmtvpDtqjBUy?usp=drive_link)

**Comment by smlambert** [comment]
Putting this here, can move to whatever issue encompasses the soil living lab concept

### Soil Living Lab wooden frame for the "window into the forest soil" 

Similar to this ["root window" plan](https://www.researchgate.net/figure/Custom-designed-root-window-construction-at-the-experimental-field-site-of-the-DFG_fig1_356593710), we would like to build a way to look at some tree roots and mycorrhizal underground network.  

We will likely build a hugel mound of material that will decay and then plant into it, so we may not need to have the window fully below ground level, but in any event, plan to use rot-resistant wood or possibly [timber-tech](https://www.timbertech.ca/products/decking-timbertech) for frame.

![rootWindow_soilLab](https://github.com/ForetCapitaleForest/actions/assets/2836948/c047ff7d-72db-4d81-b280-144af2c4a3a8)

**Comment by smlambert** [comment]
Also, at some point [rainfall simulator](https://www.sciencedirect.com/science/article/abs/pii/S0167198712001201) for one of the living lab stations / experiments

<img width="1013" alt="Screenshot 2024-02-28 at 1 11 07 PM" src="https://github.com/ForetCapitaleForest/actions/assets/2836948/c6dad939-a64d-48ad-ade8-69f1a723b66c">

Video [link](https://www.youtube.com/watch?v=i0ENNMky1sc)

**Comment by smlambert** [comment]
[Herb spiral](https://www.permaculturenews.org/2015/04/17/the-magic-and-mystery-of-constructing-an-herb-spiral-and-why-every-suburban-lawn-should-have-one/) for bearberry 'slide'

![image](https://github.com/ForetCapitaleForest/actions/assets/2836948/668b0035-d414-4768-84c7-d841ca5d3993)

Alternate designs [here](https://savvygardening.com/herb-spiral/)

**Comment by MartinNesbitt** [comment]
OCF Grant Information Session Notes can be found in the working directory linked above.

**Comment by jodinewman** [comment]
Final application submitted March 28 2024
