### ISSUE TITLE
Develop site audit and maintenance process

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#615]
Develop an inventory reporting process for volunteers and FCF staff, and maintenance process (when to have volunteer callouts, how often to perform maintenance on each site)

Part of #593

**Comment by MartinNesbitt** [comment]
[Organizational Processes](https://drive.google.com/file/d/1_M7anuasE0SPs_yZNNRfNAOaIBlB2gIj/view?usp=drive_link)
[Site Visit Checklist Template](https://docs.google.com/spreadsheets/d/1m3Bmq_HHhe-Rs_0MqnTt6VwCCynypOj_YbOaM5Gdy00/edit?usp=sharing)
[Site Visit Checklist](https://docs.google.com/spreadsheets/d/1isKFHDD6voYTEzLWevea8sfQUPqDzB7q2nxgS2LYMJE/edit?usp=sharing)
