### ISSUE TITLE
Aviva Canada PIP Workback Plan

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#618]
### Planning
| Date | Activity &#9744; &#9745;| Owner | Issue # |
| --- | --- | --- | --- |
| Late April | &#9744; Receive Tree Delivery | @Matthewtennant |
| three weeks out (May 29th) | &#9744;  Send out first Aviva email | @ShellCrabtree @MartinNesbitt   |
| three weeks out (May 29th) | &#9744;  Pick tree order to acclimatize | @Matthewtennant  |
| one week out (June 5th) | &#9744; Week Before email to LCBO| @ShellCrabtree @MartinNesbitt   |  |
| one day before | &#9744; Reminder email to LCBO | @ShellCrabtree @MartinNesbitt   | |

### Day of Event -Wednesday June 12th , 2024
 | Activity &#9744; &#9745;| Owner | Issue # |
 | --- | --- | --- |
 |  &#9744; last-chance weather cancellation |  |  |
 | &#9744; Aviva Event  | @MartinNesbitt @KaviGK  | |
| &#9744; Post to Social Media | @KaviGK  |  |
| &#9744; Site photography |  @MartinNesbitt @KaviGK  |  |
### Post-Event
 | Date | Activity &#9744; &#9745;| Owner | Issue # |
| --- | --- | --- | --- |
| day after | &#9744; Event post-mortem/TC PIP Report | @MartinNesbitt @ShellCrabtree   |  |
| week after | &#9744; thank you email to Aviva | @ShellCrabtree @MartinNesbitt   |  |
| month after | &#9744; tree after-care campaign | @MartinNesbitt @KaviGK  |  |
|  | &#9744; Site photography |  @MartinNesbitt @KaviGK  |  |
|  | &#9744; Monitoring and Maintenance |  @MartinNesbitt  |  |

**Comment by MartinNesbitt** [comment]
[Project Budget](https://docs.google.com/spreadsheets/d/1zWiDyIfSz2VIMJzMz4fnTwsX-iqUH_O_NWCEwW5Q_is/edit?usp=sharing)

**Comment by jodinewman** [comment]
| Species | Quantity | Location | Source | 
| -------- | ---------- | -------- | 
| Silver Maple (_Acer saccharinum_) | 20 | TBD | Baker's | 
| White oak (_Quercus alba_) | 15 | TBD | Baker's | 
| Bearberry (_Arctostaphylos uva-ursi_) | 20 | Cedar song stop | NVK | 
| Basket willow (_Salix purpurea_) | 15 | Willow tunnel by soil living lab | NVK | 
| Eastern white cedar (_Thuja occidentalis_) | 10 | Cedar song stop | NVK | 

Delivery early April (Baker's) and late April (NVK)

**Comment by MartinNesbitt** [comment]
Tentative Agenda and Event Description:

The planting site is a (street / roadway, park, facility / institution, conservation area, other – please specify)
Volunteers will participate in (digging holes; planting [trees, shrubs, other native plants]; watering; mulching; invasive species removal; urban gardening; other – please specify)
The goal of this event is to (Maximum of two sentences).
The species being planted are (native, non-invasive, a mix of native and non-invasive).
A brief agenda for the event is:
Time: Welcoming remarks from Tree Canada
Time: Planting demonstration and safety instructions
Time: Planting activity
Time: Group Photo, tear down and clean up
Amenities available on site are (washrooms, water fountains, parking lot, etc; if parking is off site, please note the walking time to the meeting point)
Difficulty of the terrain: (easy – flat terrain; medium – some incline / decline; challenging – inclines / declines and obstacles to avoid)
