### ISSUE TITLE
LCBO PIP Workback Plan - Aviation Site #3

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#620]
### Planning
| Date | Activity &#9744; &#9745;| Owner | Issue # |
| --- | --- | --- | --- |
| May 1 | &#9744; Receive Tree Delivery | @Matthewtennant |
| three weeks out (May 7th) | &#9744;  Send out first LCBO email | @ShellCrabtree @MartinNesbitt   |#629 |
| three weeks out (May 7th) | &#9744;  Pick tree order to acclimatize | @Matthewtennant  | #630
| May 23  | &#9744;  Confirm mulch delivery to site | @ShellCrabtree @jodinewman  | #623
| one week out (May 21st) | &#9744;  Reach out to Nick and Raymond about tree delivery | @KaviGK @MartinNesbitt  |#631
| one week out (May 21st) | &#9744; Week Before email to LCBO| @ShellCrabtree @MartinNesbitt   | #632 |
| one day before | &#9744; Reminder email to LCBO | @ShellCrabtree @MartinNesbitt   | #633|

### Day of Event - Tuesday May 28th, 2024
 | Activity &#9744; &#9745;| Owner | Issue # |
 | --- | --- | --- |
 |  &#9744; last-chance weather cancellation |  |  |
 | &#9744; Tree Transport | @Matthewtennant @MartinNesbitt  |  |
 | &#9744; Aviation Site 3 Event  | @MartinNesbitt @KaviGK  |#634 |
| &#9744; Post to Social Media | @KaviGK  |  |

### Post-Event
 | Date | Activity &#9744; &#9745;| Owner | Issue # |
| --- | --- | --- | --- |
| day after | &#9744; Event post-mortem/TC PIP Report | @MartinNesbitt @ShellCrabtree   |  |
| week after | &#9744; thank you email to LCBO | @ShellCrabtree @MartinNesbitt   |  |
| month after | &#9744; tree after-care campaign | @MartinNesbitt @KaviGK  |  |
|  | &#9744; Site photography |  @MartinNesbitt @KaviGK  |  |
|  | &#9744; Monitoring and Maintenance |  @MartinNesbitt  |  |

**Comment by MartinNesbitt** [comment]
Sponsor:  LCBO
Local Sponsor Contact Name and Email:  Natalia Martinez-Nagles | C: 437-230-7114 | E: natalia.nagles@lcbo.com
Preferred Location: Ottawa; last year they planted at the Aviation Pathway, is there a possibility to do so again?
Preferred Dates / Timing: the week of May 27th if possible, avoid week leading up to Victoria Day long weekend
Anticipated # of Volunteers:  25
Stock Budget:  $3550
Forestry Specialist Fee:  $1000
 
Rebecca Chow is the Development lead for LCBO. She will send out an introductory email between you and their local contact. 
 
When the event date, time, and location are confirmed, please fill out the information below and share it, along with a map of the project site and meeting point, with the Local Contact in your confirmation email to them.  
 
The planting site is a (street / roadway, park, facility / institution, conservation area, other – please specify)  
Volunteers will participate in (digging holes; planting [trees, shrubs, other native plants]; watering; mulching; invasive species removal; urban gardening; other – please specify)  
The goal of this event is to (Maximum of two sentences).  
The species being planted are (native, non-invasive, a mix of native and non-invasive, non-native*).  
A brief agenda for the event is:  
Time: Welcoming remarks from Tree Canada  
Time: Planting demonstration and safety instructions 
Time: Planting activity 
Time: Group Photo, tear down and clean up 
Amenities available on site are (washrooms, water fountains, parking lot, etc; if parking is off site, please note the walking time to the meeting point) 
Difficulty of the terrain: (easy – flat terrain; medium – some include / decline; challenging – inclines / declines and obstacles to avoid) 
 
Please reach out to the local sponsor contact three weeks prior to their event date to determine their participant numbers. Once we have this, Rebecca will work with you to determine the best course of action to take depending on the result.

**Comment by jodinewman** [comment]
| Species | Quantity | Source | 
| -------- | ---------- | -------- | 
| _Acer saccharinum_ (Silver maple) | 20 | Baker's | 
|_Celtis occidentalis_ (Hackberry) | 20 | Baker's | 
| _Picea glauca_ (White spruce) | 20 | NVK |
| _Thuja occidentalis_ (Eastern white cedar) | 20 | NVK |
| _Juniperus virginiana_ (Eastern red cedar) | 20 | NVK | 

Delivery early April (Baker's), end of April (NVK)

**Comment by MartinNesbitt** [comment]
Tentative Agenda and Event Description:
- The planting site is a park
- Volunteers will participate in (digging holes; planting [trees, shrubs, other native plants]; watering; mulching; invasive species removal)
- The goal of this event is to (Maximum of two sentences).
- The species being planted are (native ).

A brief agenda for the event is:
10:00-10:05 am : Welcoming remarks from Tree Canada
10:05-10:15 am: Planting demonstration and safety instructions
10:15-11:00 am: Planting activity
11:00 - 11:55am: Tree Care and Maintenance (watering, mulching, removal of competing vegetation)
11:55 am -12pm: Group Photo, tear down and clean up
Amenities available on site are (washrooms, water fountains, parking lot, etc; if parking is off site, please note the walking time to the meeting point)
Difficulty of the terrain: (easy – flat terrain)
