### ISSUE TITLE
Tree Canada - National Greening Program Project Proposal

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#669]
Tree Canada has to replant 2000 seedlings in the NCC region. May be a potential project at Mer Bleue.

General Notes:

- TC is looking to plant 2,000 seedlings in NCR in 2024. Due to low surivival rate from previous NGP planting in NCR.
- Proposed MB as potential location
- TC is willing to fund the project at $2.5/tree. $5000 for whole project
- TC is organize and fund an arborist/forester to perform site assessment  in year 1,3 & 5
- No requirement contractually from TC for us to maintain the site but if we plant the trees, it is our mandate to provide care and maintenance.
- No requirement by TC on the type of tree stock and species. But at that price and quantity of trees planted we are looking at plugs.
- No requirement by TC on who plants the trees (can be FCF staff, volunteers, can contract a tree planting group)
- Required to plant trees in 2024
    - proposed planting in the fall

[Folder](https://drive.google.com/drive/folders/1HytVvG2U4WeZle0Y_S0GP59TXFO0gTK4?usp=drive_link) created for work and resources dedicated to project proposal/feasibility.

**Comment by Matthewtennant** [comment]
denied this as not possible to source trees at price given. have offered to look at possibility of project in 2025
