### ISSUE TITLE
List of extra activities for Norman Johnson students 

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#688]
We will have help from the Norman Johnson High School students every Monday morning from 9:30am - 12:15pm to the end of June.  There are lots of manual labour tasks on-site and we will blend in some educational opportunities as well.

- [ ] build a hugelkultur mound (in corner of Field 2)
- [ ] build hugelkultur mound at Birch Path healing forest
- [ ] tidy up and finish planting an edible hedge (in Field 2)
- [ ] heavily mulch the edible hedge along Field 2 (after we whippersnip the grass along side it)
- [ ] install the culverts and crossings on the remaining ditches along the walking path
- [x] dig and install the culvert for the hose to cross the road at the greenhouse
- [ ] empty and move the existing shed to a spot in the staff area behind the greenhouse
- [ ] find, flag and assess any butternut trees still alive (in Field 2)
- [ ] re-apply compost/natural fertilizer/bone&blood meal, mulch and mycorhyzzal inoculant to trees in Fields 1 and 2
- [x] clear weeds away from trees/shrubs in Field 1 and 2
- [x] weed Lawn Conversion sites 1-3
- [x] weed strawberry beds
- [x] prune/cordon the grape vines
- [x] grafting practice and grafting onto crabapples in Field 2
- [ ] finish the Lawn Conversion / Guild 4 site
- [ ] help assemble arbor at Lawn Conversion / Guild 4 site
- [x] interplant the annual vegetables and herbs into Lawn Conversion sites for the season
- [ ] plant tree seeds into air pruning beds (once they are assembled and put out into the seedling area)
- [x] shade cloth roof over cattle panels for seedling structure
- [ ] tidy seedling structure 
- [x] assist with any final work needed to prep for bench installation at Birch Path Healing Forest
- [x] prep site for bearberry spiral at the cedar song site
- [ ] prep areas where benches will go along walking path
- [ ] build a natural-looking trellis structure for blackberries along walking path
- [ ] weed Tiny Forest Demonstration plots
- [ ] help install a tall post for trail cam for Tiny Forest Demonstration plots
- [ ] help install 2 posts/spots for crowd-sourced walking path photos
- [x] edible mushroom cultivation (shiitake logs in amur maple, blue oyster in straw, wine cap in wood chips)
- [ ] create a mushroom growing shade tent near the front corner of Field 1 (to put cultivation projects (to water and care for)
- [ ] once a bit drier, move large amounts of leaf mulch over to where we intend to build the large hugel pile for the soil living lab
- [ ] sort and organize remaining pots, separate damaged pots into a pile for recycling, tidy up around the greenhouses
- [ ] plant a black raspberry patch
- [x] plant donated serviceberry and eastern redbud trees from Stephanie P.
- [ ] plant donated apple and pear trees from Nanabush (one is memorial tree for Dan V., to have cayenne peppers planted around it)
- [ ] build an asparagus bed in Field 2 & plant donated asparagus from Nanabush 
- [x] set up posts and trellis lines for potted tree support in seedling area
- [x] lay down weed suppression fabric in seedling area
- [ ] pick June berries (haskaps, Saskatoons, strawberries) following harvest protocol
- [ ] assess food-bearing trees at the farm at mid-June (after June drop) to pinch off % of fruit

**Comment by smlambert** [comment]
Apr 22
- pot up trees
- remove tree guards
- practice grafting

Apr 29
- pot up more trees
- plant Saskatoons and haskap in hedgerow
- tidy up Lawn conversion guilds
- remove plastic labels from Tiny Forest Demonstration plot trees
- mulch the long hugel in Field 3
- graft 7 different types of apple onto the 2 crabapples at the edge of Field 2

**Comment by smlambert** [comment]
May 6 (try to get as much of this done as possible)
- Birch Path Healing Forest (BPHF) work to prep for delivery of benches
  - remove remaining soil to get the inner circle level
  - level a path from the bridge to the inner circle
  - move small logs to create a serpentine hugelkultur to the west of BPHF (for berry path)
  - move the removed soil to form part of the serpentine hugel
  - cover the serpentine hugel with wood chips


May 13
- mushroom cultivation

**Comment by jodinewman** [comment]
Closing for now as NJ students have finished for the summer. Although some of these cns be sued for future volunteer events @Matthewtennant @leannbyatte 

I have moved the important ones into their own issues and added to #642
