### ISSUE TITLE
Answer questions to be featured in the OCF annual report 

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#691]
OCF asked if we'd share our story regarding, who is FCF and our relationship with JJFoundation to be featured in their annual report.  Answers are due May 3rd.  The questions and working document are [here](https://docs.google.com/document/d/13Ugb8UNm1xNpusJVbfrtntvPWGbhIRuC/edit?usp=sharing&ouid=112063872730204900099&rtpof=true&sd=true).

**Comment by ShellCrabtree** [comment]
@smlambert please take a look at the answers provided - I'm a little stuck on the question of challenges we faced. Thanks!

**Comment by ShellCrabtree** [comment]
Completed and sent. Here is the [Doc](https://docs.google.com/document/d/13Ugb8UNm1xNpusJVbfrtntvPWGbhIRuC/edit)
