### ISSUE TITLE
Apply for WSIB

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#70]

**Comment by StephMcNeely** [comment]
From WSIB (June 13) - We have received your business details to start the registration process.   Your confirmation number is OTE008H0H. Please keep the confirmation number if you need to check the status of your registration.

When the registration is complete, you will receive an email with your WSIB account number.

**Comment by StephMcNeely** [comment]
- [ ] provide Charitable status and NCC contract to employeraccounts@wsibon.ca    REF; 9177814  Attention matthew, Account Specialist

**Comment by smlambert** [comment]
@StephMcNeely - we have received 2 pieces of mail from WSIB indicating that we have signed up.  One appears to be a form.  Not sure what next action is to take.

**Comment by StephMcNeely** [comment]
@Shelley can you send me a copy of the form? Or is it just in case there is a WSIB reportable incident?

**Comment by smlambert** [comment]
I will scan them and put them into this [FCF_Directors/HR/Insurance](https://drive.google.com/drive/folders/1b6_pG0h-NqgXOgEzL8rzccLVb41guZFa?usp=sharing) shared folder later today.
