### ISSUE TITLE
Transfer folders to new shared drive

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#73]
Transfer folders from the old shared drive "FCF" to the new shared drive "Foret Capitale Forest 2022". This is part the drive reorganization.

**Comment by natashafcf** [comment]
https://docs.google.com/spreadsheets/d/1bVGn6mN1xguqJGPTpJevI89qFy8osBsBt4puXv9mTV4/edit#gid=0 

@MartinNesbitt  @StephMcNeely  @smlambert I've created a folder of files/folders that need to be moved by the board because of accessibility restrictions so that we can track them more easily!

**Comment by natashafcf** [comment]
@smlambert @StephMcNeely Sending a notification as a reminder for this task :)
