### ISSUE TITLE
Build the Guild 4 pergola

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#734]
Instructions for building the Toja Grid pergola kit can be found at:
https://tojagrid.com/pages/how-to-build-your-toja-grid-pergola-kit

(pdf manual [here](https://cdn.shopify.com/s/files/1/2568/0730/files/English.pdf?8940530499732687773))

The top is assembled first, then legs, then mounted to the base.  Since we do not have a wood or concrete base, I purchased Toja ground anchors that will be used to mount onto.

FYI @Matthewtennant

**Comment by smlambert** [comment]
Claims that it will take approximately 45 min to build.

**Comment by Matthewtennant** [comment]
arbor has been installed, however is not very solid. Could be reinforced with beams going 45 degrees between the pillars and frame.
