### ISSUE TITLE
Determine set up of Red Barn

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#739]
Visit the Red Barn to determine set up and needs for fundraiser lunch

**Comment by leannbyatte** [comment]
- Projector screen to be placed in back right corner
- 8 double tables to be set - 6 for guests, 2 for staff/volunteers (create path between tables leading to food area)
- 1 table to be set in front of projector screen (to place projector)
- Food tables placed in back left corner
- Purchasing tables on left side wall

![IMG_4875](https://github.com/user-attachments/assets/878ee091-87a7-42f6-a2ba-5b661c99ec5f)
![IMG_4874](https://github.com/user-attachments/assets/85ad190d-8f42-433e-87db-2a96106fd665)

**Comment by smlambert** [comment]
BTW, if we want to sell Nanabush preserves (all funds donated to FCF) we can plan to do so.

**Comment by jodinewman** [comment]
We do :D
