### ISSUE TITLE
Send Welcome emails to volunteers/automate process

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#74]
it seems that a bunch of volunteers had not received a welcome email sent to them. 
Perhaps we could send that out to them soon if they were never sent it. 

I wonder if there's a way to automate the process.

**Comment by MartinNesbitt** [comment]
Here is a draft of the automated Welcome email for new volunteer sign ups.

https://docs.google.com/document/d/1wj9Z-cW9y0-v4g-MnoE_7BwUgOy0WogI7jg5DIqubkc/edit?usp=sharing

**Comment by smlambert** [comment]
Now when one signs up through the volunteer web form, upon submitting, they see this response:

<img width="592" alt="Screen Shot 2022-06-26 at 10 42 46 AM" src="https://user-images.githubusercontent.com/2836948/175819987-3ee8287e-773e-4af0-8100-6b153bec801f.png">

And their form submission is forwarded to the comms@foretcapitaleforest.ca team.

Do not see an easy way to also put their entries into the spreadsheet or add them to the volunteers group, that will remain manual and is done in batches at the end of a week (or we look at the listing in the wordpress forms list for the full set).

Mark this as closed.
