### ISSUE TITLE
Prepare presentation for fundraiser

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#744]
Joan > will speak for ~ 10 mins

**Comment by leannbyatte** [comment]
This is just a template that we can use to fill in our information, I'm not sure exactly what we want to include - so please add in as you see fit

Link to edit presentation:
https://www.canva.com/design/DAGObuZWhk0/wUgbAElRKz-pF6L0D6FpyQ/edit?utm_content=DAGObuZWhk0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by StephMcNeely** [comment]
Great presentation by the way!
It was really well done. We should definitely reuse  some or all of it.
Excellent visuals.

I do have some questions about the equity analysis. Will try to remember to
ask at an upcoming meeting ;)

Stephanie
