### ISSUE TITLE
SMARTnet Sustainability Showcase - October 5 at the Just Food Community Farm

### ISSUE THREAD

**Issue by ShellCrabtree** [ForetCapitaleForest/actions#760]
**October 5 Schedule**

8:00 am - Shelley C. on site to gather our table, signage, materials for our table (we have a spot for 1 table) and move it to the pavilion for set up
9:00 am - FCF volunteers arrive to set up table in the Pavilion (Shelleys, Kevin)
10:00 am - Event start
11:00 am - FCF Tour
1:30 pm - FCF Tour
4:00 pm - Event Close and clean up

**Materials to bring/display**

- 1 Table, 2 chairs, tablecloth, FCF sign (cloth one)
- 1 pager - [FCF about us](https://drive.google.com/drive/u/0/folders/1XeLwvmw7jJBtXGSCClfta6xh6fJ94LoV)
- FCF donation cards 
- 2 seedlings for display
- QR codes sheet for information and donations
- Package in preparation see [Edible Landscapes](https://github.com/ForetCapitaleForest/actions/issues/742) (conversion guild [plans](https://foretcapitaleforest.ca/wp-content/uploads/2024/04/Guilds-Maps-2022.pdf)
- GIVEAWAYS - frost peach pits from Sundaura, in damp vermiculite with instructions how to cold stratify, germinate, and then plant to have a peach seedling for next spring as part of a "personal edible landscape"

**Activities advertised by the Event organizers throughout the day**

- Indoor Exhibitor Showcase
- Outdoor Presentations in the
Covered Pavillion
- EV Expo including Test Drives
- Farm Tours
- FREE Parking

[SNCo Showcase Poster - Oct 5th 2024 (1).pdf](https://github.com/user-attachments/files/17229993/SNCo.Showcase.Poster.-.Oct.5th.2024.1.pdf)
[2024 SmartNet Sustainability Showcase Info Package.pdf](https://github.com/user-attachments/files/17229996/2024.SmartNet.Sustainability.Showcase.Info.Package.pdf)

**Comment by smlambert** [comment]
Peach Pit giveaway: 
- individual baggies of 3 - 5 pits in vermiculite 
- a printout of 1/3 of the double-sided printout of this [document](https://docs.google.com/document/d/1i5aCHzurXYAZB_dHJC8F28y5D6uLVjemXwR_yauUh_Q/edit?usp=sharing)
- alternative of a printout is a QR code to the info online (put it on the resource page)

**Comment by smlambert** [comment]
- Ensure we have some $5 and $10 dollar bills for the cash box float
- I have charged the Square device
- Need @ShellCrabtree info to create her Square profile

**Comment by ShellCrabtree** [comment]
@smlambert - I will print those sheets and have them ready for tomorrow ~ 50
Here is my info for SQUARE: Date of birth: December 10, 1967, address is 33 chemin de Burnthill, Wakefield, Quebec, J0X 3G0, (cell in case it's needed: 819-923-9069).
