### ISSUE TITLE
AAFC - Local Food Infrastructure Grant Application

### ISSUE THREAD

**Issue by ShellCrabtree** [ForetCapitaleForest/actions#767]
- [Folder with grant application information](https://drive.google.com/drive/u/0/folders/1IRMiy0eOqxO6hB34wPi74vQ4w-QO4omM) created
- [Summary of AAFC description of grant/requirements]()
- Running [list of existing grant submissions](https://docs.google.com/spreadsheets/d/1soSRtF1pgGc4J8X6DnGHXSg_aL-bHvq7/edit?usp=sharing&ouid=112063872730204900099&rtpof=true&sd=true)

**Comment by smlambert** [comment]
For items over $5000 need to get a written quote from the company (Miska for trailer and Grimo for Patriot nutcracker)

**Comment by smlambert** [comment]
Submitted yesterday.  Thanks @jodinewman and @ShellCrabtree !  I will put the acknowledgement of submission in the shared drive.
