### ISSUE TITLE
Update website content

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#768]
2 things:
1. Update all blog posts to have a 'category'.  Currently many of our posts have no category, which means our "News" page has a button that is for the "Uncategorized" posts.  As an additional note, we should ensure the News page shows the latest 3 blog posts, and not just buttons.

<img width="1422" alt="Screenshot 2024-10-12 at 8 03 28 AM" src="https://github.com/user-attachments/assets/1a96d77f-bf08-4f0f-ab16-17882e6e1283">

<img width="1006" alt="Screenshot 2024-10-12 at 8 08 52 AM" src="https://github.com/user-attachments/assets/3b5afc15-c0f6-4504-b3e7-ecd294a8ebcb">

2. Our front page shows a listing of Instagram posts.  This was intended as a way to have constantly changing content on the main page of the website.  It does not appear that its been updated since the summer.  Is it because we do not post regular instagram content, or is that mechanism to update the page not working.  Investigate and fix (as refreshed content on the front page increases our SEO score).  This additional relates to having a content plan that is "write once, distribute everywhere", where we make the plan for content, post it as a blog post to the webpage, which can automatically disseminate the content across all of our social media channels (Facebook, Instagram, LinkedIn).

<img width="969" alt="Screenshot 2024-10-12 at 8 08 38 AM" src="https://github.com/user-attachments/assets/f2b1cff6-4a0e-4509-bd4a-d84d0a098bc3">

**Comment by jodinewman** [comment]
![Screenshot_20241015-095540.png](https://github.com/user-attachments/assets/41f3074b-f773-488a-a21a-f8a119822357)

The Instagram feature works for me - meaning it has either been fixed or is not displaying the same for everyone.
