### ISSUE TITLE
Update Grant Calendar

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#77]

**Comment by natashafcf** [comment]
Applied Grants 2021-2022
https://docs.google.com/spreadsheets/d/1jtF5_MJ6XwVcL5kVQpqL3TQGWlwTCnl5jUvm0WmSHQM/edit#gid=0

Prospective Grannts 2022-2023
https://docs.google.com/spreadsheets/d/1EUwyPtc_ewSDaMu43ry2DDq5pCbOuub22G7Nmc2_hRs/edit#gid=0
