### ISSUE TITLE
Change Website Design

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#78]
Change website design to look more professional and ease the process of donations. However, maintain the wordpress platform so others have the ability to work on website. 

- [x] Find contacts that can update website design [Alberta contact, person who updated CAFES Ottawa website]
- [x] Request quotes and perform quote comparison

**Comment by smlambert** [comment]
In the same vein (of website facelift): https://github.com/ForetCapitaleForest/actions/issues/16

**Comment by MartinNesbitt** [comment]
I've been working on updating the "projects" page on the website. 

What we've discussed is to have a main projects page with a short summary paragraph of all the projects where you have the ability to click on a "read more" button that will take you to a page with more details about each project. Each Project will have their own page.

The working document in the FCF drive is [here](https://docs.google.com/document/d/1Fkd0jnXSQwxd5ok19NzS4yNI8WVXq4nQdJpwcyZQYog/edit?usp=sharing)

The draft pages in wordpress are below:

The main page is called: "Projects WIP"

That main page will link out to the separate project pages called; "Base of Operations", "Community Tree Hub", "Tree Planting".

When time allows, could everyone review and provide feedback on the structure of the page.
Thanks!

**Comment by MartinNesbitt** [comment]
Draft's of the updated projects page on the website are ready for feedback! Looking for feedback on the written content. The document can be found [here](https://docs.google.com/document/d/1Fkd0jnXSQwxd5ok19NzS4yNI8WVXq4nQdJpwcyZQYog/edit?usp=sharing).

You can also view the drafts on wordpress for a better idea of what it'll look like on the website. The main page is called "Projects WIP", the pages are found under posts as "Base of Operations", "Community Tree Hub", and "Tree Planting".

Thanks!
@smlambert @StephMcNeely @InnesBuck @natashafcf @Pepe-Fifi

**Comment by MartinNesbitt** [comment]
I reminder to provide feedback on the updated projects page. Note that these pages don't have to be perfect as we can edit and tweak them as we move forward, but they will provide more information than what we have currently!

Thanks!
@smlambert @StephMcNeely @InnesBuck @natashafcf @Pepe-Fifi

**Comment by smlambert** [comment]
I believe I did a first pass of reviews to the document and am good for you to proceed with changes.  My preference is to create back-dated posts for events and link to them from the main projects page, but as mentioned in today's conversation, we can iteratively improve from your initial update if desired.  This is a big step forward from what we have.

**Comment by MartinNesbitt** [comment]
Just following up on the discussion from January 29. Looking to upgrade the website as the website does not have a clear message and does not reflect what we do as an organization. 

Below is a working list of what we can do to update or improve the design of website (please provide suggestions). 

- [ ] Review mission and vision statement
- [ ] Include an updated paragraph about FCF on the home page
- [ ] Make it easy to view our maps and metrics/progress on the goals.
- [ ] Update the volunteer form
- [ ] Create a page for those who want to volunteer. A page to provide them all the information they need to come out and volunteer. This would be an effort to make it easier for the public to volunteer.
- [ ] Translate the website to French #137 
- [ ]

**Comment by smlambert** [comment]
Also, ensure that we state that we are a non-profit (and/or charity) clearly on the page.

**Comment by smlambert** [comment]
Simplify our site map and consolidate the top-level menu items into a smaller set (as we have 'bloat' now along the top of the page).  Use [earthtrust](https://earthtrust.org.uk/) site map as a guide.
<img width="1169" alt="Screenshot 2023-07-17 at 5 27 50 PM" src="https://github.com/ForetCapitaleForest/actions/assets/2836948/b14565a9-ee74-454d-b5cd-0b74147b1685">

**Comment by smlambert** [comment]
Closing this as the work is now being done by Francesco.  Any additional notes buried in comments above about updating content should be done under separate individual issues.
