### ISSUE TITLE
Create or Update Watering & Site Assessment Calendar

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#79]

**Comment by smlambert** [comment]
Phil McNeely will switch his watering day to Thursday when water is turned on, so he can use the hose and attend to the tiny forests area in addition to the greenhouse.  

There are very few things left inside the greenhouse, but Stephen Fanjoy will bring over some of his maple tree saplings and use one side of the greenhouse for those.

**Comment by smlambert** [comment]
For the pots outside the greenhouse, I have placed many into pans, so the pans can be filled so the pots can draw water up from the bottom.  This allows us to water heavily and gives extra reprieve for potted plants while we continue to work to get them in the ground.

For the remaining trees heeled in behind the greenhouse, I have put up more shade cloth to keep that area cooler, whipper-snipped and moved some potted stock into shade as well.

**Comment by natashafcf** [comment]
Just Food Watering and Maintenance Schedule
https://docs.google.com/spreadsheets/d/1-Cq9bzGffQiSzBOVkpX-WxbZ7LqIjqP38CLotyex9mc/edit#gid=0
