### ISSUE TITLE
Metric Reporting

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#80]
Ease the process of reporting metrics that are outlined in Master Plan, tree inventory, communication's growth/engagement, volunteer base. This is essential for determining a baseline in which we can measure how much we've grown and goal achievement. We can also use Tableau for data visualizations that can be inserted in Annual reports, project summary reports, communications. It also shows potential donors that we are reliable.

- [x] Group Brainstorm on metrics to measure
- [ ] Familiarize ourselves with Tableau. 
- [ ] Update existing reporting measures such as the tree inventory #75 
- [x] Figure out how to connect Tableau to live data versus a static spreadsheet https://github.com/ForetCapitaleForest/actions/issues/162

**Comment by jodinewman** [comment]
[Brainstorming JamBoard](https://jamboard.google.com/d/1R3z8Fqtc5KW4IDwL1Edx9zr66BU_AfZvPmDpJkAp5kM/viewer?pli=1)

**Comment by smlambert** [comment]
Related: https://github.com/ForetCapitaleForest/actions/issues/582#issuecomment-1890481188

**Comment by MartinNesbitt** [comment]
closing as completed as the issue is too broad. Will create more smaller tasks related to metric reporting in Github.
