### ISSUE TITLE
Brainstorm Potential Project ideas

### ISSUE THREAD

**Issue by MartinNesbitt** [ForetCapitaleForest/actions#82]
Brainstorm things/processes of the organization that can be updated or improved that the interns can work on.

**Comment by MartinNesbitt** [comment]
Creating somewhat of a large priority list or set of deliverables that the interns can work on throughout their internships.

**Comment by smlambert** [comment]
See also this 'work-in-progress' (WIP) diagram as an attempt at organizing and putting names against the various efforts: https://github.com/ForetCapitaleForest/actions/issues/103
