### ISSUE TITLE
get letter of support from NCC via Just Food

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#86]

**Comment by StephMcNeely** [comment]
@smlambert can you please request a letter from Moe for our Ottawa grant? 
Please confirm that your organization has support from the National Capital Commission to undertake this project.  The letter for property owner consent dates back to 2017 and supports Just Food’s application for an edible trees grant.  Please provide a letter or email from the NCC indicating that  they are supportive of this current initiative by Forêt Capitale Forest at the Just Food Farm.
Project overview:  The Big Plans for Small Forests project is a small-scale community based project to create demonstration
mini-food forests that will be interactive and educational tools to support an environmentally sustainable
Ottawa through the transformation of small, underused green spaces.

**Comment by smlambert** [comment]
Sent an email to request this, will follow up this week.

**Comment by smlambert** [comment]
If we create draft letters of support for Just Food and NCC, Moe will use it as a basis to get us the updates.  Need someone to draft these (based off existing stuff), and put in a location which we can share with Moe.

**Comment by smlambert** [comment]
I've shared that doc with Moe Garahan and we should also send her an email that the doc exists, so she can prompt a new letter from NCC.

**Comment by StephMcNeely** [comment]
Great - thanks Natasha.

Just checking that you can update - the text needs to spell out that it is
Foret Capitale Forest getting the CEPGP grant (as a Leasee to Just Food)
that should meet the City's requirements.

Thanks
Stephanie

**Comment by natashafcf** [comment]
I've made the above changes for review :)

https://docs.google.com/document/d/1B6paY_HHwCpsHKGv-442WxfUZn3LPlEesvcYEiWcPQ0/edit

**Comment by StephMcNeely** [comment]
@natashafcf did you send this directly to Moe, or via @smlambert ?
Need to get all this paperwork + insurance and vendor stuff back to the City ;)

**Comment by smlambert** [comment]
I've not sent an explicit email to Moe (she would have received an email saying a document has been shared), but I recommend @natashafcf to send her a note with a link to the document and the explicit request.

**Comment by natashafcf** [comment]
Sent to Moe :)

**Comment by smlambert** [comment]
Moe has intervened, contacted Tara and the letter is no longer required.  Closing as such.
