### ISSUE TITLE
Create workback plan for CIMA spring planting

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#9]
Tentative planting date on June 5th?

Need a workback plan from that date to ensure we have a successful event with all necessary resources in hand.

**Comment by StephMcNeely** [comment]
Items to bring to Hogs Back site in addition to trees

- [ ] @smlambert will need at least 250 coco mats for site.  Do we have that many available? And where to pick up for Thursday loading?
- [ ] Dave H is confirmed to be bringing: 2 tables, water container & pump, granola snacks. Unloading at 8am Saturday, June 4
- [ ] @StephMcNeely to bring: spare masks, hand sanitizer, FCF laminates (site plan and Buckthorn info sheet), FCF signs
- [ ] Shovels, wheelbarrow? (may not be necessary with the soil delivery to site)
- [ ] @StephMcNeely to check if Dave has spare gloves for CIMA team if not, need to purchase for re-use
- [ ] bring camp chairs for eating/ taking breaks

**Comment by smlambert** [comment]
@StephMcNeely - tree mats and tree guards are in boxes on either side of the door of the little greenhouse.  Not sure of numbers, there should be 2.5 boxes worth of small diameter mats, and at least a 1/2 box of large diameter mats.  Can check today how many that translates to.

**Comment by smlambert** [comment]
This can be marked as completed.
