### ISSUE TITLE
Mulch the tiny forests

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#93]
Dependent on https://github.com/ForetCapitaleForest/actions/issues/92, we should be laying down cardboard (optional) and mulch in order to reduce the amount of attention and watering that is needed for the demonstration plots.

**Comment by smlambert** [comment]
Mulch will be delivered on the afternoon of Friday July 8th, I will plan to meet the truck to show where to drop mulch.

**Comment by smlambert** [comment]
Work has begun, we will try to mulch as we plant, and when all trees are mulched, if there is any mulch left, we will cover any remaining bare ground.

**Comment by smlambert** [comment]
Progress is good, we can and should now mulch as we plant out this area until all mulch is used, then we should consider moving the pile near Wabano plot to the tiny forest site (by trailer).

**Comment by smlambert** [comment]
@InnesBuck @MartinNesbitt - a fresh chip drop has arrived so we can do a heavy layer (4inch or more mulch layer on all bare ground in the tiny forests area).

**Comment by smlambert** [comment]
Host a Mulching Party event on Aug 31st 4-7pm to accomplish some of this work.

**Comment by InnesBuck** [comment]
Event had 8 volunteers in addition, now must create a thank you post for the event
- include pictures from the event

**Comment by smlambert** [comment]
related: https://github.com/ForetCapitaleForest/actions/issues/138
