### ISSUE TITLE
Apply mycorrhizal inoculate to tiny forest plots

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#94]
This is a water soluble powder that can be watered on to the trees.  Best applied after the layer of mulch is added, so consider this task dependent on #93.

**Comment by smlambert** [comment]
Use the Mulching Party event on Aug 31st 4-7pm to accomplish some of this work.

**Comment by Pepe-Fifi** [comment]
At the mulching party ( August 31st) I applied the mycorrhizal inoculate to all the trees on the first tiny forest plot. The remaining 3 plots are to be done next.

**Comment by Pepe-Fifi** [comment]
on September 12, I applied mycorrhizal inoculate to half of the second tiny forest, as I ran out of time before the meeting at 1 pm;I  will continue with fields 2 and 3 later this week.

**Comment by Pepe-Fifi** [comment]
Sept 21/22 applied mycorrhizal inoculate on fields 2 and 4; still pending field 3 as there is some weeding to be done first. I will continue next week.
