### ISSUE TITLE
Apply Soil to hugelkultur mound in Field 3

### ISSUE THREAD

**Issue by smlambert** [ForetCapitaleForest/actions#97]
Need to:
- add manure (both chicken manure in greenhouse and donkey manure in pile beside the greenhouse)
- add compost/soil

**Comment by MartinNesbitt** [comment]
- Rockland HS (week of May 15th)

**Comment by MartinNesbitt** [comment]
- Chicken manure and mulch have been layered on the hugel mound. 
- It was suggested that the group from Norman Johnston Alternative School can apply the layer of compost when they come.

**Comment by smlambert** [comment]
Given that we will also want a fresh soil drop to bag up and take some for the Quebec side plantings, and for the alternative school visit (June 5th) and/or SAIL employee visit (TBD), I should plan to have one prior to those upcoming dates.

**Comment by smlambert** [comment]
The Norman Johnston students were only at our part of the farm for a brief period (they did a tour with Moe of the rest of the farm for most of their morning).  Soil still needs to be added to the top of this hugel.

**Comment by smlambert** [comment]
Remaining item to finish is to top this hugelkultur mound with soil (from near the nanabush greenhouse or the small pile of it behind the compost pile between Field 2 and Field 3)

**Comment by smlambert** [comment]
Soil has been dropped at one end of the hugel mound, that soil can be applied to the top of the hugel mound (on top of the potatoes that are planted into the woodchips).
